using System;
using System.Text;
using System.Text.Json.Nodes;
using Axiam.Sdk.Amqp;
using Xunit;

namespace Axiam.Sdk.Tests;

/// <summary>
/// Ground-truth parity + policy tests for NEW-4 (AMQP replay protection,
/// <c>sdks/CONTRACT.md</c> §8 "v2 — Replay Protection", <c>key_version = 2</c>).
///
/// <para>
/// The values below are copied verbatim from
/// <c>crates/axiam-amqp/tests/fixtures/v2_reference_vectors.json</c> — the
/// canonical, server-produced ground truth every SDK must reproduce
/// byte-for-byte. That file is generated by the AXIAM server's own sign path
/// (<c>crates/axiam-amqp/src/messages.rs</c>), so hardcoding its values here
/// (master key / derived subkey / canonical JSON / expected HMAC) is
/// equivalent to reading the file at test time, without adding a
/// cross-directory file dependency from this NuGet-published test project
/// onto <c>crates/</c>.
/// </para>
///
/// <para>
/// <b>No canonicalization change was needed for NEW-4.</b> <see cref="Hmac"/>
/// is schema-agnostic — it parses the body into an order-preserving
/// <see cref="JsonObject"/>, removes only <c>hmac_signature</c>, and
/// re-serializes with <see cref="JsonObject.ToJsonString(System.Text.Json.JsonSerializerOptions?)"/>.
/// Because <c>nonce</c> and <c>issued_at</c> are just two more keys in that
/// same ordered object, they are automatically covered by the HMAC with zero
/// struct/serialization changes. This test file proves that byte-parity claim
/// against the real fixture and then layers the three NEW-4 policy gates
/// (<see cref="ReplayGuard"/>) on top: <c>key_version</c>, freshness, and
/// nonce dedup.
/// </para>
///
/// <para>
/// <b>Wire-body ordering note.</b> <c>Hmac.Verify</c>'s correctness is
/// insertion-order-preserving BY DESIGN (see <see cref="Hmac"/>'s class
/// remarks) — it trusts that the bytes it receives are already in the order
/// the server actually signed them, exactly as a real AMQP delivery arrives.
/// The fixture file's <c>"message"</c> JSON object is alphabetized (an
/// artifact of the fixture-generation tool serializing a generic
/// <c>serde_json::Value</c>, which is alphabetical by internal
/// <c>BTreeMap</c> representation, not the real wire order), so the
/// <c>*WireBody</c> constants below are built from <c>canonical_signed_json</c>
/// (the authoritative declaration-order signed bytes) with <c>hmac_signature</c>
/// appended as the trailing field, NOT copied from the fixture's alphabetized
/// <c>"message"</c> text — using the latter would make <c>Hmac.Verify</c>
/// reject a genuinely valid vector for the wrong reason (order mismatch, not
/// an actual signature failure).
/// </para>
/// </summary>
[Trait("Category", "Fast")]
public class V2ReplayProtectionTests
{
    // ---- Ground truth from crates/axiam-amqp/tests/fixtures/v2_reference_vectors.json ----
    //
    // master_signing_key_hex = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"
    // tenant_id               = "11111111-1111-1111-1111-111111111111"
    // are the HKDF inputs the server used to derive DerivedSubkeyHex below;
    // recorded here for traceability back to the fixture even though this SDK
    // never performs that derivation itself (see the comment on DerivedSubkeyHex).

    // hkdf.derived_subkey_hex — HKDF-SHA256(salt="axiam-amqp-hkdf-salt-v1",
    // ikm=master_signing_key_hex, info="axiam-amqp-v1" || key_version(1 byte) ||
    // tenant_id(16 raw bytes)). This SDK receives the per-tenant subkey
    // pre-derived from the AXIAM management API (§8.1) — it never performs
    // HKDF itself — so tests use this value directly as the HMAC key, exactly
    // matching the SDK's runtime contract.
    private const string DerivedSubkeyHex = "919e125ec83799c1e113a27707cac5008a2608d0557e00dfe1b3a316abed4b89";

    // authz_request.canonical_signed_json (field order: correlation_id,
    // tenant_id, subject_id, action, resource_id, scope, key_version, nonce,
    // issued_at; hmac_signature absent).
    private const string AuthzCanonicalSignedJson =
        "{\"correlation_id\":\"22222222-2222-2222-2222-222222222222\"," +
        "\"tenant_id\":\"11111111-1111-1111-1111-111111111111\"," +
        "\"subject_id\":\"33333333-3333-3333-3333-333333333333\"," +
        "\"action\":\"documents:read\"," +
        "\"resource_id\":\"44444444-4444-4444-4444-444444444444\"," +
        "\"scope\":\"confidential\"," +
        "\"key_version\":2," +
        "\"nonce\":\"55555555-5555-5555-5555-555555555555\"," +
        "\"issued_at\":\"2026-07-10T12:00:00Z\"}";

    private const string AuthzExpectedHmacHex =
        "13d73b3aa8a400fc3f64dbc20b36952d8584142feb822b5f77495b0f587049ed";

    // authz_request's real on-the-wire body: declaration order (identical to
    // canonical_signed_json) with hmac_signature appended as the trailing
    // field — matching what the Rust server actually transmits. This is
    // deliberately NOT the alphabetically-sorted "message" object recorded in
    // the fixture JSON file: that alphabetical ordering is merely an artifact
    // of how the fixture-generation tool pretty-printed a generic
    // serde_json::Value (internally a BTreeMap, hence alphabetical) for
    // documentation purposes — it is not the literal wire bytes. Hmac.Verify
    // is insertion-order-preserving (see Hmac.cs's class remarks), so a test
    // input MUST already be in real wire (declaration) order for this
    // ground-truth parity check to be meaningful; feeding it the
    // fixture file's alphabetized "message" text would make Hmac.Verify
    // reject a genuinely valid vector for the wrong reason (order mismatch,
    // not a real signature failure).
    private const string AuthzWireBody =
        "{\"correlation_id\":\"22222222-2222-2222-2222-222222222222\"," +
        "\"tenant_id\":\"11111111-1111-1111-1111-111111111111\"," +
        "\"subject_id\":\"33333333-3333-3333-3333-333333333333\"," +
        "\"action\":\"documents:read\"," +
        "\"resource_id\":\"44444444-4444-4444-4444-444444444444\"," +
        "\"scope\":\"confidential\"," +
        "\"key_version\":2," +
        "\"nonce\":\"55555555-5555-5555-5555-555555555555\"," +
        "\"issued_at\":\"2026-07-10T12:00:00Z\"," +
        "\"hmac_signature\":\"13d73b3aa8a400fc3f64dbc20b36952d8584142feb822b5f77495b0f587049ed\"}";

    // audit_event.canonical_signed_json (field order: tenant_id, actor_id,
    // actor_type, action, resource_id, outcome, ip_address, metadata,
    // key_version, nonce, issued_at; hmac_signature absent).
    private const string AuditCanonicalSignedJson =
        "{\"tenant_id\":\"11111111-1111-1111-1111-111111111111\"," +
        "\"actor_id\":\"66666666-6666-6666-6666-666666666666\"," +
        "\"actor_type\":\"User\"," +
        "\"action\":\"user.login\"," +
        "\"resource_id\":\"77777777-7777-7777-7777-777777777777\"," +
        "\"outcome\":\"Success\"," +
        "\"ip_address\":\"203.0.113.7\"," +
        "\"metadata\":{\"method\":\"password\"}," +
        "\"key_version\":2," +
        "\"nonce\":\"88888888-8888-8888-8888-888888888888\"," +
        "\"issued_at\":\"2026-07-10T12:00:00Z\"}";

    private const string AuditExpectedHmacHex =
        "c87056dfa96bf0606949104108e5fc7296df0a22ad39bf94bbc00512b214f40f";

    // Same real-wire-order rationale as AuthzWireBody above (declaration
    // order + trailing hmac_signature, not the fixture file's alphabetized
    // "message" object).
    private const string AuditWireBody =
        "{\"tenant_id\":\"11111111-1111-1111-1111-111111111111\"," +
        "\"actor_id\":\"66666666-6666-6666-6666-666666666666\"," +
        "\"actor_type\":\"User\"," +
        "\"action\":\"user.login\"," +
        "\"resource_id\":\"77777777-7777-7777-7777-777777777777\"," +
        "\"outcome\":\"Success\"," +
        "\"ip_address\":\"203.0.113.7\"," +
        "\"metadata\":{\"method\":\"password\"}," +
        "\"key_version\":2," +
        "\"nonce\":\"88888888-8888-8888-8888-888888888888\"," +
        "\"issued_at\":\"2026-07-10T12:00:00Z\"," +
        "\"hmac_signature\":\"c87056dfa96bf0606949104108e5fc7296df0a22ad39bf94bbc00512b214f40f\"}";

    // ---- (1) Byte-parity: parse -> Remove(hmac_signature) -> ToJsonString round-trips
    //          reproduce the fixture's canonical_signed_json EXACTLY, for both message types.

    [Fact]
    public void RoundTrip_AuthzRequest_ReproducesCanonicalSignedJsonExactly()
    {
        JsonObject wire = JsonNode.Parse(AuthzWireBody)!.AsObject();
        wire.Remove("hmac_signature");
        string roundTripped = wire.ToJsonString();

        Assert.Equal(AuthzCanonicalSignedJson, roundTripped);
    }

    [Fact]
    public void RoundTrip_AuditEvent_ReproducesCanonicalSignedJsonExactly()
    {
        JsonObject wire = JsonNode.Parse(AuditWireBody)!.AsObject();
        wire.Remove("hmac_signature");
        string roundTripped = wire.ToJsonString();

        Assert.Equal(AuditCanonicalSignedJson, roundTripped);
    }

    // ---- (2) The recomputed HMAC over that round-tripped canonical form matches
    //          the fixture's expected hmac_signature_hex byte-for-byte, for both types.

    [Fact]
    public void RoundTrip_AuthzRequest_RecomputedHmacMatchesFixtureExactly()
    {
        byte[] subkey = Convert.FromHexString(DerivedSubkeyHex);

        JsonObject wire = JsonNode.Parse(AuthzWireBody)!.AsObject();
        wire.Remove("hmac_signature");
        byte[] canonicalBytes = Encoding.UTF8.GetBytes(wire.ToJsonString());

        byte[] computed = System.Security.Cryptography.HMACSHA256.HashData(subkey, canonicalBytes);
        string computedHex = Convert.ToHexString(computed).ToLowerInvariant();

        Assert.Equal(AuthzExpectedHmacHex, computedHex);
    }

    [Fact]
    public void RoundTrip_AuditEvent_RecomputedHmacMatchesFixtureExactly()
    {
        byte[] subkey = Convert.FromHexString(DerivedSubkeyHex);

        JsonObject wire = JsonNode.Parse(AuditWireBody)!.AsObject();
        wire.Remove("hmac_signature");
        byte[] canonicalBytes = Encoding.UTF8.GetBytes(wire.ToJsonString());

        byte[] computed = System.Security.Cryptography.HMACSHA256.HashData(subkey, canonicalBytes);
        string computedHex = Convert.ToHexString(computed).ToLowerInvariant();

        Assert.Equal(AuditExpectedHmacHex, computedHex);
    }

    // ---- (3) Hmac.Verify (the actual SDK verifier, not a hand-rolled recomputation)
    //          ACCEPTS both server-signed v2 reference vectors using the fixture's
    //          pre-derived per-tenant subkey as the signing key.

    [Fact]
    public void HmacVerify_AcceptsServerSignedAuthzRequestReferenceVector()
    {
        byte[] subkey = Convert.FromHexString(DerivedSubkeyHex);
        byte[] body = Encoding.UTF8.GetBytes(AuthzWireBody);

        Assert.True(Hmac.Verify(subkey, body), "Hmac.Verify must ACCEPT the server-signed v2 authz_request reference vector");
    }

    [Fact]
    public void HmacVerify_AcceptsServerSignedAuditEventReferenceVector()
    {
        byte[] subkey = Convert.FromHexString(DerivedSubkeyHex);
        byte[] body = Encoding.UTF8.GetBytes(AuditWireBody);

        Assert.True(Hmac.Verify(subkey, body), "Hmac.Verify must ACCEPT the server-signed v2 audit_event reference vector");
    }

    // ---- (4) ReplayGuard.TryExtractMetadata correctly reads key_version/nonce/issued_at
    //          off an already-verified reference-vector body.

    [Fact]
    public void TryExtractMetadata_ReadsFieldsFromAuthzRequestReferenceVector()
    {
        bool ok = ReplayGuard.TryExtractMetadata(Encoding.UTF8.GetBytes(AuthzWireBody), out ReplayMetadata meta);

        Assert.True(ok);
        Assert.Equal(2, meta.KeyVersion);
        Assert.Equal("55555555-5555-5555-5555-555555555555", meta.Nonce);
        Assert.Equal("2026-07-10T12:00:00Z", meta.IssuedAt);
    }

    [Fact]
    public void TryExtractMetadata_ReadsFieldsFromAuditEventReferenceVector()
    {
        bool ok = ReplayGuard.TryExtractMetadata(Encoding.UTF8.GetBytes(AuditWireBody), out ReplayMetadata meta);

        Assert.True(ok);
        Assert.Equal(2, meta.KeyVersion);
        Assert.Equal("88888888-8888-8888-8888-888888888888", meta.Nonce);
        Assert.Equal("2026-07-10T12:00:00Z", meta.IssuedAt);
    }

    // ---- (5) ReplayGuard.Check policy gates, exercised directly (unit-level,
    //          independent of the consumer's ack/nack matrix covered in AmqpConsumerTests) ----

    private static readonly DateTimeOffset ReferenceIssuedAt =
        DateTimeOffset.Parse("2026-07-10T12:00:00Z", System.Globalization.CultureInfo.InvariantCulture);

    [Fact]
    public void Check_AcceptsFreshKeyVersion2WithUnseenNonce()
    {
        var guard = new ReplayGuard(TimeSpan.FromMinutes(5), () => ReferenceIssuedAt);
        var meta = new ReplayMetadata(2, "nonce-accept-1", "2026-07-10T12:00:00Z");

        Assert.True(guard.Check(meta));
    }

    [Fact]
    public void Check_RejectsKeyVersion1()
    {
        var guard = new ReplayGuard(TimeSpan.FromMinutes(5), () => ReferenceIssuedAt);
        var meta = new ReplayMetadata(1, "nonce-reject-key-version", "2026-07-10T12:00:00Z");

        Assert.False(guard.Check(meta));
    }

    [Fact]
    public void Check_RejectsKeyVersion0_WhenKeyVersionFieldIsAbsentOrUnparseable()
    {
        // TryExtractMetadata yields KeyVersion == 0 for a missing/non-numeric
        // key_version field — Check must reject that exactly like an explicit
        // key_version=1, since 0 < MinKeyVersion too.
        var guard = new ReplayGuard(TimeSpan.FromMinutes(5), () => ReferenceIssuedAt);
        var meta = new ReplayMetadata(0, "nonce-reject-key-version-zero", "2026-07-10T12:00:00Z");

        Assert.False(guard.Check(meta));
    }

    [Fact]
    public void Check_RejectsStaleIssuedAt_BeyondSkewInThePast()
    {
        var guard = new ReplayGuard(TimeSpan.FromMinutes(5), () => ReferenceIssuedAt);
        string staleIssuedAt = ReferenceIssuedAt.AddMinutes(-10).ToString("yyyy-MM-ddTHH:mm:ssZ");
        var meta = new ReplayMetadata(2, "nonce-reject-stale-past", staleIssuedAt);

        Assert.False(guard.Check(meta));
    }

    [Fact]
    public void Check_RejectsFutureIssuedAt_BeyondSkewInTheFuture()
    {
        var guard = new ReplayGuard(TimeSpan.FromMinutes(5), () => ReferenceIssuedAt);
        string futureIssuedAt = ReferenceIssuedAt.AddMinutes(10).ToString("yyyy-MM-ddTHH:mm:ssZ");
        var meta = new ReplayMetadata(2, "nonce-reject-future", futureIssuedAt);

        Assert.False(guard.Check(meta));
    }

    [Fact]
    public void Check_RejectsUnparseableIssuedAt()
    {
        var guard = new ReplayGuard(TimeSpan.FromMinutes(5), () => ReferenceIssuedAt);
        var meta = new ReplayMetadata(2, "nonce-reject-unparseable", "not-a-timestamp");

        Assert.False(guard.Check(meta));
    }

    [Fact]
    public void Check_RejectsReplayedNonce_SecondCheckOfSameNonceFails()
    {
        var guard = new ReplayGuard(TimeSpan.FromMinutes(5), () => ReferenceIssuedAt);
        var meta = new ReplayMetadata(2, "nonce-replay-target", "2026-07-10T12:00:00Z");

        Assert.True(guard.Check(meta), "first use of the nonce must be accepted");
        Assert.False(guard.Check(meta), "second use of the SAME nonce must be rejected as a replay");
    }

    [Fact]
    public void Check_AllowsNonceReuse_AfterItsEntryHasExpired()
    {
        DateTimeOffset now = ReferenceIssuedAt;
        var guard = new ReplayGuard(TimeSpan.FromMinutes(5), () => now);

        var firstUse = new ReplayMetadata(2, "nonce-ttl-expiry", "2026-07-10T12:00:00Z");
        Assert.True(guard.Check(firstUse));

        // Advance the clock (and issued_at, so freshness still passes) past
        // the 2x-skew TTL (10 minutes) of the first use.
        now = ReferenceIssuedAt.AddMinutes(11);
        var secondUse = new ReplayMetadata(2, "nonce-ttl-expiry", now.ToString("yyyy-MM-ddTHH:mm:ssZ"));
        Assert.True(guard.Check(secondUse), "a nonce whose dedup entry has aged past its TTL may be reused");
    }
}
