// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using Axiam.Sdk.Core;
using Axiam.Sdk.Management;
using Axiam.Sdk.Management.Models;
using System.Globalization;
using System.Text.Json;
using System.Text.Json.Serialization;
using Xunit;
using RetryPolicy = Axiam.Sdk.Management.Models.RetryPolicy;

namespace Axiam.Sdk.Tests.Management;

/// <summary>
/// Generated &#167;27.4 rule 5 conformance: a sparse body sends what was set, and nothing else.
/// </summary>
/// <remarks>
/// <para>
/// Rule 5 draws the line between a sparse update and a replacement at ABSENCE, not at null: a
/// property the caller did not name must not appear in the body at all, because a null on the
/// wire is a request to CLEAR the field. One hand-written example proves that for one model;
/// the failure this guards against is a generator that gets it right for the model somebody
/// wrote a test for and wrong for the other seventeen.
/// </para>
/// <para>
/// Each case sets one property at a time and asserts the body carries exactly that one wire
/// key, then sets every property and asserts the body carries exactly all of them. Bodies are
/// rendered through ManagementSupport.EncodeBody, the writer the SDK actually sends with — a
/// rule proved on a lookalike serializer is not proved.
/// </para>
/// </remarks>
public sealed class ManagementSparseBodiesGeneratedTests
{
    /// <summary>Stands in for any uuid-formatted property.</summary>
    private static readonly Guid ExampleId = Guid.Parse("11111111-1111-4111-8111-111111111111");

    /// <summary>
    /// &#167;27.4 rule 5 for ApiProviderConfig: each property sets exactly its own key.
    /// </summary>
    [Fact]
    public void ApiProviderConfigSendsOnlyWhatWasSet()
    {
        AssertKeys(
            new ApiProviderConfig { ApiUrl = "example" },
            "api_url");
        AssertKeys(
            new ApiProviderConfig
            {
                ApiUrl = "example",
            },
            "api_url");
        AssertKeys(new ApiProviderConfig());
    }

    /// <summary>
    /// &#167;27.4 rule 5 for EmailConfigOverride: each property sets exactly its own key.
    /// </summary>
    [Fact]
    public void EmailConfigOverrideSendsOnlyWhatWasSet()
    {
        AssertKeys(
            new EmailConfigOverride { Enabled = true },
            "enabled");
        AssertKeys(
            new EmailConfigOverride { FromEmail = "example" },
            "from_email");
        AssertKeys(
            new EmailConfigOverride { FromName = "example" },
            "from_name");
        AssertKeys(
            new EmailConfigOverride { Provider = new ProviderConfigSmtp { Host = "example", Port = 1, Starttls = true, Username = "example" } },
            "provider");
        AssertKeys(
            new EmailConfigOverride { ReplyTo = "example" },
            "reply_to");
        AssertKeys(
            new EmailConfigOverride
            {
                Enabled = true,
                FromEmail = "example",
                FromName = "example",
                Provider = new ProviderConfigSmtp { Host = "example", Port = 1, Starttls = true, Username = "example" },
                ReplyTo = "example",
            },
            "enabled", "from_email", "from_name", "provider", "reply_to");
        AssertKeys(new EmailConfigOverride());
    }

    /// <summary>
    /// &#167;27.4 rule 5 for TenantSettingsOverride: each property sets exactly its own key.
    /// </summary>
    [Fact]
    public void TenantSettingsOverrideSendsOnlyWhatWasSet()
    {
        AssertKeys(
            new TenantSettingsOverride { AccessTokenLifetimeSecs = 1L },
            "access_token_lifetime_secs");
        AssertKeys(
            new TenantSettingsOverride { AdminNotificationsEnabled = true },
            "admin_notifications_enabled");
        AssertKeys(
            new TenantSettingsOverride { DefaultCertValidityDays = 1 },
            "default_cert_validity_days");
        AssertKeys(
            new TenantSettingsOverride { DeletionGracePeriodDays = 1 },
            "deletion_grace_period_days");
        AssertKeys(
            new TenantSettingsOverride { EmailVerificationGracePeriodHours = 1 },
            "email_verification_grace_period_hours");
        AssertKeys(
            new TenantSettingsOverride { EmailVerificationRequired = true },
            "email_verification_required");
        AssertKeys(
            new TenantSettingsOverride { HibpCheckEnabled = true },
            "hibp_check_enabled");
        AssertKeys(
            new TenantSettingsOverride { LockoutBackoffMultiplier = 1.0 },
            "lockout_backoff_multiplier");
        AssertKeys(
            new TenantSettingsOverride { LockoutDurationSecs = 1L },
            "lockout_duration_secs");
        AssertKeys(
            new TenantSettingsOverride { MaxCertValidityDays = 1 },
            "max_cert_validity_days");
        AssertKeys(
            new TenantSettingsOverride { MaxFailedLoginAttempts = 1 },
            "max_failed_login_attempts");
        AssertKeys(
            new TenantSettingsOverride { MaxLockoutDurationSecs = 1L },
            "max_lockout_duration_secs");
        AssertKeys(
            new TenantSettingsOverride { MfaChallengeLifetimeSecs = 1L },
            "mfa_challenge_lifetime_secs");
        AssertKeys(
            new TenantSettingsOverride { MfaEnforced = true },
            "mfa_enforced");
        AssertKeys(
            new TenantSettingsOverride { MinLength = 1 },
            "min_length");
        AssertKeys(
            new TenantSettingsOverride { OpaqueKsf = "example" },
            "opaque_ksf");
        AssertKeys(
            new TenantSettingsOverride { OpaqueMode = "example" },
            "opaque_mode");
        AssertKeys(
            new TenantSettingsOverride { OpaqueSuite = "example" },
            "opaque_suite");
        AssertKeys(
            new TenantSettingsOverride { PasswordHistoryCount = 1 },
            "password_history_count");
        AssertKeys(
            new TenantSettingsOverride { RefreshTokenLifetimeSecs = 1L },
            "refresh_token_lifetime_secs");
        AssertKeys(
            new TenantSettingsOverride { RequireDigits = true },
            "require_digits");
        AssertKeys(
            new TenantSettingsOverride { RequireLowercase = true },
            "require_lowercase");
        AssertKeys(
            new TenantSettingsOverride { RequireSymbols = true },
            "require_symbols");
        AssertKeys(
            new TenantSettingsOverride { RequireUppercase = true },
            "require_uppercase");
        AssertKeys(
            new TenantSettingsOverride
            {
                AccessTokenLifetimeSecs = 1L,
                AdminNotificationsEnabled = true,
                DefaultCertValidityDays = 1,
                DeletionGracePeriodDays = 1,
                EmailVerificationGracePeriodHours = 1,
                EmailVerificationRequired = true,
                HibpCheckEnabled = true,
                LockoutBackoffMultiplier = 1.0,
                LockoutDurationSecs = 1L,
                MaxCertValidityDays = 1,
                MaxFailedLoginAttempts = 1,
                MaxLockoutDurationSecs = 1L,
                MfaChallengeLifetimeSecs = 1L,
                MfaEnforced = true,
                MinLength = 1,
                OpaqueKsf = "example",
                OpaqueMode = "example",
                OpaqueSuite = "example",
                PasswordHistoryCount = 1,
                RefreshTokenLifetimeSecs = 1L,
                RequireDigits = true,
                RequireLowercase = true,
                RequireSymbols = true,
                RequireUppercase = true,
            },
            "access_token_lifetime_secs", "admin_notifications_enabled", "default_cert_validity_days",
            "deletion_grace_period_days", "email_verification_grace_period_hours",
            "email_verification_required", "hibp_check_enabled", "lockout_backoff_multiplier",
            "lockout_duration_secs", "max_cert_validity_days", "max_failed_login_attempts",
            "max_lockout_duration_secs", "mfa_challenge_lifetime_secs", "mfa_enforced",
            "min_length", "opaque_ksf", "opaque_mode", "opaque_suite", "password_history_count",
            "refresh_token_lifetime_secs", "require_digits", "require_lowercase",
            "require_symbols", "require_uppercase");
        AssertKeys(new TenantSettingsOverride());
    }

    /// <summary>
    /// &#167;27.4 rule 5 for TokenExchangeTrustRequest: each property sets exactly its own key.
    /// </summary>
    [Fact]
    public void TokenExchangeTrustRequestSendsOnlyWhatWasSet()
    {
        AssertKeys(
            new TokenExchangeTrustRequest { AcceptedAudiences = Array.Empty<string>() },
            "accepted_audiences");
        AssertKeys(
            new TokenExchangeTrustRequest { Enabled = true },
            "enabled");
        AssertKeys(
            new TokenExchangeTrustRequest { MaxLifetimeSecs = 1L },
            "max_lifetime_secs");
        AssertKeys(
            new TokenExchangeTrustRequest { MaxTokenAgeSecs = 1L },
            "max_token_age_secs");
        AssertKeys(
            new TokenExchangeTrustRequest { ScopeMap = JsonDocument.Parse("{}").RootElement },
            "scope_map");
        AssertKeys(
            new TokenExchangeTrustRequest { SubjectMapping = "example" },
            "subject_mapping");
        AssertKeys(
            new TokenExchangeTrustRequest
            {
                AcceptedAudiences = Array.Empty<string>(),
                Enabled = true,
                MaxLifetimeSecs = 1L,
                MaxTokenAgeSecs = 1L,
                ScopeMap = JsonDocument.Parse("{}").RootElement,
                SubjectMapping = "example",
            },
            "accepted_audiences", "enabled", "max_lifetime_secs", "max_token_age_secs",
            "scope_map", "subject_mapping");
        AssertKeys(new TokenExchangeTrustRequest());
    }

    /// <summary>
    /// &#167;27.4 rule 5 for UpdateFederationConfigRequest: each property sets exactly its own
    /// key.
    /// </summary>
    [Fact]
    public void UpdateFederationConfigRequestSendsOnlyWhatWasSet()
    {
        AssertKeys(
            new UpdateFederationConfigRequest { AllowedAlgorithms = Array.Empty<string>() },
            "allowed_algorithms");
        AssertKeys(
            new UpdateFederationConfigRequest { AttributeMap = JsonDocument.Parse("{}").RootElement },
            "attribute_map");
        AssertKeys(
            new UpdateFederationConfigRequest { ClientId = "example" },
            "client_id");
        AssertKeys(
            new UpdateFederationConfigRequest { ClientSecret = Sensitive<string>.Wrap("example") },
            "client_secret");
        AssertKeys(
            new UpdateFederationConfigRequest { Enabled = true },
            "enabled");
        AssertKeys(
            new UpdateFederationConfigRequest { IdpSigningCertPem = "example" },
            "idp_signing_cert_pem");
        AssertKeys(
            new UpdateFederationConfigRequest { MetadataUrl = "example" },
            "metadata_url");
        AssertKeys(
            new UpdateFederationConfigRequest { Provider = "example" },
            "provider");
        AssertKeys(
            new UpdateFederationConfigRequest { TokenExchange = new TokenExchangeTrustRequest {  } },
            "token_exchange");
        AssertKeys(
            new UpdateFederationConfigRequest
            {
                AllowedAlgorithms = Array.Empty<string>(),
                AttributeMap = JsonDocument.Parse("{}").RootElement,
                ClientId = "example",
                ClientSecret = Sensitive<string>.Wrap("example"),
                Enabled = true,
                IdpSigningCertPem = "example",
                MetadataUrl = "example",
                Provider = "example",
                TokenExchange = new TokenExchangeTrustRequest {  },
            },
            "allowed_algorithms", "attribute_map", "client_id", "client_secret",
            "enabled", "idp_signing_cert_pem", "metadata_url", "provider",
            "token_exchange");
        AssertKeys(new UpdateFederationConfigRequest());
    }

    /// <summary>
    /// &#167;27.4 rule 5 for UpdateGroup: each property sets exactly its own key.
    /// </summary>
    [Fact]
    public void UpdateGroupSendsOnlyWhatWasSet()
    {
        AssertKeys(
            new UpdateGroup { Description = "example" },
            "description");
        AssertKeys(
            new UpdateGroup { Metadata = JsonDocument.Parse("{}").RootElement },
            "metadata");
        AssertKeys(
            new UpdateGroup { Name = "example" },
            "name");
        AssertKeys(
            new UpdateGroup
            {
                Description = "example",
                Metadata = JsonDocument.Parse("{}").RootElement,
                Name = "example",
            },
            "description", "metadata", "name");
        AssertKeys(new UpdateGroup());
    }

    /// <summary>
    /// &#167;27.4 rule 5 for UpdateNotificationRuleRequest: each property sets exactly its own
    /// key.
    /// </summary>
    [Fact]
    public void UpdateNotificationRuleRequestSendsOnlyWhatWasSet()
    {
        AssertKeys(
            new UpdateNotificationRuleRequest { Description = "example" },
            "description");
        AssertKeys(
            new UpdateNotificationRuleRequest { Enabled = true },
            "enabled");
        AssertKeys(
            new UpdateNotificationRuleRequest { Events = Array.Empty<NotificationEventType>() },
            "events");
        AssertKeys(
            new UpdateNotificationRuleRequest { Name = "example" },
            "name");
        AssertKeys(
            new UpdateNotificationRuleRequest { RecipientEmails = Array.Empty<string>() },
            "recipient_emails");
        AssertKeys(
            new UpdateNotificationRuleRequest
            {
                Description = "example",
                Enabled = true,
                Events = Array.Empty<NotificationEventType>(),
                Name = "example",
                RecipientEmails = Array.Empty<string>(),
            },
            "description", "enabled", "events", "name", "recipient_emails");
        AssertKeys(new UpdateNotificationRuleRequest());
    }

    /// <summary>
    /// &#167;27.4 rule 5 for UpdateOAuth2ClientRequest: each property sets exactly its own key.
    /// </summary>
    [Fact]
    public void UpdateOAuth2ClientRequestSendsOnlyWhatWasSet()
    {
        AssertKeys(
            new UpdateOAuth2ClientRequest { BackchannelLogoutUri = "example" },
            "backchannel_logout_uri");
        AssertKeys(
            new UpdateOAuth2ClientRequest { DpopBoundAccessTokens = true },
            "dpop_bound_access_tokens");
        AssertKeys(
            new UpdateOAuth2ClientRequest { DpopRequireNonce = true },
            "dpop_require_nonce");
        AssertKeys(
            new UpdateOAuth2ClientRequest { GrantTypes = Array.Empty<string>() },
            "grant_types");
        AssertKeys(
            new UpdateOAuth2ClientRequest { Jwks = "example" },
            "jwks");
        AssertKeys(
            new UpdateOAuth2ClientRequest { JwksUri = "example" },
            "jwks_uri");
        AssertKeys(
            new UpdateOAuth2ClientRequest { Name = "example" },
            "name");
        AssertKeys(
            new UpdateOAuth2ClientRequest { PostLogoutRedirectUris = Array.Empty<string>() },
            "post_logout_redirect_uris");
        AssertKeys(
            new UpdateOAuth2ClientRequest { Profile = ClientProfile.Standard },
            "profile");
        AssertKeys(
            new UpdateOAuth2ClientRequest { RedirectUris = Array.Empty<string>() },
            "redirect_uris");
        AssertKeys(
            new UpdateOAuth2ClientRequest { RequirePar = true },
            "require_par");
        AssertKeys(
            new UpdateOAuth2ClientRequest { Scopes = Array.Empty<string>() },
            "scopes");
        AssertKeys(
            new UpdateOAuth2ClientRequest { SelfSignedTlsClientAuthThumbprints = Array.Empty<string>() },
            "self_signed_tls_client_auth_thumbprints");
        AssertKeys(
            new UpdateOAuth2ClientRequest { TlsClientAuthSanDns = "example" },
            "tls_client_auth_san_dns");
        AssertKeys(
            new UpdateOAuth2ClientRequest { TlsClientAuthSanUri = "example" },
            "tls_client_auth_san_uri");
        AssertKeys(
            new UpdateOAuth2ClientRequest { TlsClientAuthSubjectDn = "example" },
            "tls_client_auth_subject_dn");
        AssertKeys(
            new UpdateOAuth2ClientRequest { TlsClientCertificateBoundAccessTokens = true },
            "tls_client_certificate_bound_access_tokens");
        AssertKeys(
            new UpdateOAuth2ClientRequest { TokenEndpointAuthMethod = ClientAuthMethod.ClientSecretPost },
            "token_endpoint_auth_method");
        AssertKeys(
            new UpdateOAuth2ClientRequest
            {
                BackchannelLogoutUri = "example",
                DpopBoundAccessTokens = true,
                DpopRequireNonce = true,
                GrantTypes = Array.Empty<string>(),
                Jwks = "example",
                JwksUri = "example",
                Name = "example",
                PostLogoutRedirectUris = Array.Empty<string>(),
                Profile = ClientProfile.Standard,
                RedirectUris = Array.Empty<string>(),
                RequirePar = true,
                Scopes = Array.Empty<string>(),
                SelfSignedTlsClientAuthThumbprints = Array.Empty<string>(),
                TlsClientAuthSanDns = "example",
                TlsClientAuthSanUri = "example",
                TlsClientAuthSubjectDn = "example",
                TlsClientCertificateBoundAccessTokens = true,
                TokenEndpointAuthMethod = ClientAuthMethod.ClientSecretPost,
            },
            "backchannel_logout_uri", "dpop_bound_access_tokens", "dpop_require_nonce",
            "grant_types", "jwks", "jwks_uri", "name", "post_logout_redirect_uris",
            "profile", "redirect_uris", "require_par", "scopes", "self_signed_tls_client_auth_thumbprints",
            "tls_client_auth_san_dns", "tls_client_auth_san_uri", "tls_client_auth_subject_dn",
            "tls_client_certificate_bound_access_tokens", "token_endpoint_auth_method");
        AssertKeys(new UpdateOAuth2ClientRequest());
    }

    /// <summary>
    /// &#167;27.4 rule 5 for UpdateOrganizationRequest: each property sets exactly its own key.
    /// </summary>
    [Fact]
    public void UpdateOrganizationRequestSendsOnlyWhatWasSet()
    {
        AssertKeys(
            new UpdateOrganizationRequest { Metadata = JsonDocument.Parse("{}").RootElement },
            "metadata");
        AssertKeys(
            new UpdateOrganizationRequest { Name = "example" },
            "name");
        AssertKeys(
            new UpdateOrganizationRequest { Slug = "example" },
            "slug");
        AssertKeys(
            new UpdateOrganizationRequest
            {
                Metadata = JsonDocument.Parse("{}").RootElement,
                Name = "example",
                Slug = "example",
            },
            "metadata", "name", "slug");
        AssertKeys(new UpdateOrganizationRequest());
    }

    /// <summary>
    /// &#167;27.4 rule 5 for UpdatePermissionRequest: each property sets exactly its own key.
    /// </summary>
    [Fact]
    public void UpdatePermissionRequestSendsOnlyWhatWasSet()
    {
        AssertKeys(
            new UpdatePermissionRequest { Action = "example" },
            "action");
        AssertKeys(
            new UpdatePermissionRequest { Description = "example" },
            "description");
        AssertKeys(
            new UpdatePermissionRequest
            {
                Action = "example",
                Description = "example",
            },
            "action", "description");
        AssertKeys(new UpdatePermissionRequest());
    }

    /// <summary>
    /// &#167;27.4 rule 5 for UpdateReactorRequest: each property sets exactly its own key.
    /// </summary>
    [Fact]
    public void UpdateReactorRequestSendsOnlyWhatWasSet()
    {
        AssertKeys(
            new UpdateReactorRequest { Description = "example" },
            "description");
        AssertKeys(
            new UpdateReactorRequest { Enabled = true },
            "enabled");
        AssertKeys(
            new UpdateReactorRequest { Events = Array.Empty<string>() },
            "events");
        AssertKeys(
            new UpdateReactorRequest { FailurePolicy = FailurePolicy.FailClosed },
            "failure_policy");
        AssertKeys(
            new UpdateReactorRequest { Mode = ReactorMode.Intercept },
            "mode");
        AssertKeys(
            new UpdateReactorRequest { Name = "example" },
            "name");
        AssertKeys(
            new UpdateReactorRequest { Priority = 1 },
            "priority");
        AssertKeys(
            new UpdateReactorRequest { TimeoutMs = 1 },
            "timeout_ms");
        AssertKeys(
            new UpdateReactorRequest
            {
                Description = "example",
                Enabled = true,
                Events = Array.Empty<string>(),
                FailurePolicy = FailurePolicy.FailClosed,
                Mode = ReactorMode.Intercept,
                Name = "example",
                Priority = 1,
                TimeoutMs = 1,
            },
            "description", "enabled", "events", "failure_policy", "mode",
            "name", "priority", "timeout_ms");
        AssertKeys(new UpdateReactorRequest());
    }

    /// <summary>
    /// &#167;27.4 rule 5 for UpdateResourceRequest: each property sets exactly its own key.
    /// </summary>
    [Fact]
    public void UpdateResourceRequestSendsOnlyWhatWasSet()
    {
        AssertKeys(
            new UpdateResourceRequest { Metadata = JsonDocument.Parse("{}").RootElement },
            "metadata");
        AssertKeys(
            new UpdateResourceRequest { Name = "example" },
            "name");
        AssertKeys(
            new UpdateResourceRequest { ParentId = ExampleId },
            "parent_id");
        AssertKeys(
            new UpdateResourceRequest { ResourceType = "example" },
            "resource_type");
        AssertKeys(
            new UpdateResourceRequest
            {
                Metadata = JsonDocument.Parse("{}").RootElement,
                Name = "example",
                ParentId = ExampleId,
                ResourceType = "example",
            },
            "metadata", "name", "parent_id", "resource_type");
        AssertKeys(new UpdateResourceRequest());
    }

    /// <summary>&#167;27.4 rule 5 for UpdateRole: each property sets exactly its own key.</summary>
    [Fact]
    public void UpdateRoleSendsOnlyWhatWasSet()
    {
        AssertKeys(
            new UpdateRole { Description = "example" },
            "description");
        AssertKeys(
            new UpdateRole { IsGlobal = true },
            "is_global");
        AssertKeys(
            new UpdateRole { Name = "example" },
            "name");
        AssertKeys(
            new UpdateRole
            {
                Description = "example",
                IsGlobal = true,
                Name = "example",
            },
            "description", "is_global", "name");
        AssertKeys(new UpdateRole());
    }

    /// <summary>
    /// &#167;27.4 rule 5 for UpdateScopeRequest: each property sets exactly its own key.
    /// </summary>
    [Fact]
    public void UpdateScopeRequestSendsOnlyWhatWasSet()
    {
        AssertKeys(
            new UpdateScopeRequest { Description = "example" },
            "description");
        AssertKeys(
            new UpdateScopeRequest { Name = "example" },
            "name");
        AssertKeys(
            new UpdateScopeRequest
            {
                Description = "example",
                Name = "example",
            },
            "description", "name");
        AssertKeys(new UpdateScopeRequest());
    }

    /// <summary>
    /// &#167;27.4 rule 5 for UpdateServiceAccount: each property sets exactly its own key.
    /// </summary>
    [Fact]
    public void UpdateServiceAccountSendsOnlyWhatWasSet()
    {
        AssertKeys(
            new UpdateServiceAccount { Description = "example" },
            "description");
        AssertKeys(
            new UpdateServiceAccount { Name = "example" },
            "name");
        AssertKeys(
            new UpdateServiceAccount { Status = UserStatus.Active },
            "status");
        AssertKeys(
            new UpdateServiceAccount
            {
                Description = "example",
                Name = "example",
                Status = UserStatus.Active,
            },
            "description", "name", "status");
        AssertKeys(new UpdateServiceAccount());
    }

    /// <summary>
    /// &#167;27.4 rule 5 for UpdateTenant: each property sets exactly its own key.
    /// </summary>
    [Fact]
    public void UpdateTenantSendsOnlyWhatWasSet()
    {
        AssertKeys(
            new UpdateTenant { Metadata = JsonDocument.Parse("{}").RootElement },
            "metadata");
        AssertKeys(
            new UpdateTenant { Name = "example" },
            "name");
        AssertKeys(
            new UpdateTenant { Slug = "example" },
            "slug");
        AssertKeys(
            new UpdateTenant { Status = TenantStatus.Active },
            "status");
        AssertKeys(
            new UpdateTenant
            {
                Metadata = JsonDocument.Parse("{}").RootElement,
                Name = "example",
                Slug = "example",
                Status = TenantStatus.Active,
            },
            "metadata", "name", "slug", "status");
        AssertKeys(new UpdateTenant());
    }

    /// <summary>
    /// &#167;27.4 rule 5 for UpdateUserRequest: each property sets exactly its own key.
    /// </summary>
    [Fact]
    public void UpdateUserRequestSendsOnlyWhatWasSet()
    {
        AssertKeys(
            new UpdateUserRequest { Email = "example" },
            "email");
        AssertKeys(
            new UpdateUserRequest { Metadata = JsonDocument.Parse("{}").RootElement },
            "metadata");
        AssertKeys(
            new UpdateUserRequest { Status = UserStatus.Active },
            "status");
        AssertKeys(
            new UpdateUserRequest { Username = "example" },
            "username");
        AssertKeys(
            new UpdateUserRequest
            {
                Email = "example",
                Metadata = JsonDocument.Parse("{}").RootElement,
                Status = UserStatus.Active,
                Username = "example",
            },
            "email", "metadata", "status", "username");
        AssertKeys(new UpdateUserRequest());
    }

    /// <summary>
    /// &#167;27.4 rule 5 for UpdateWebhookRequest: each property sets exactly its own key.
    /// </summary>
    [Fact]
    public void UpdateWebhookRequestSendsOnlyWhatWasSet()
    {
        AssertKeys(
            new UpdateWebhookRequest { Enabled = true },
            "enabled");
        AssertKeys(
            new UpdateWebhookRequest { Events = Array.Empty<string>() },
            "events");
        AssertKeys(
            new UpdateWebhookRequest { RetryPolicy = new RetryPolicy { BackoffMultiplier = 1.0, InitialDelaySecs = 1L, MaxRetries = 1 } },
            "retry_policy");
        AssertKeys(
            new UpdateWebhookRequest { Secret = Sensitive<string>.Wrap("example") },
            "secret");
        AssertKeys(
            new UpdateWebhookRequest { Url = "example" },
            "url");
        AssertKeys(
            new UpdateWebhookRequest
            {
                Enabled = true,
                Events = Array.Empty<string>(),
                RetryPolicy = new RetryPolicy { BackoffMultiplier = 1.0, InitialDelaySecs = 1L, MaxRetries = 1 },
                Secret = Sensitive<string>.Wrap("example"),
                Url = "example",
            },
            "enabled", "events", "retry_policy", "secret", "url");
        AssertKeys(new UpdateWebhookRequest());
    }

    /// <summary>
    /// &#167;27.9: a regeneration that stopped emitting sparse bodies must fail here.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The count is asserted rather than left implicit so that dropping a sparse model from the
    /// closure is a failure, not a quietly shorter suite.
    /// </para>
    /// </remarks>
    [Fact]
    public void EverySparseBodyIsCovered()
    {
        int cases = typeof(ManagementSparseBodiesGeneratedTests)
            .GetMethods()
            .Count(m => m.Name.EndsWith("SendsOnlyWhatWasSet", StringComparison.Ordinal));
        Assert.Equal(18, cases);
    }

    /// <summary>
    /// Asserts the encoded body's key set is exactly <paramref name="expected"/>, in any order.
    /// </summary>
    /// <param name="body">the request body to render.</param>
    /// <param name="expected">the wire keys it must carry.</param>
    /// <typeparam name="T">the body type.</typeparam>
    private static void AssertKeys<T>(T body, params string[] expected)
    {
        string text = ManagementSupport.EncodeBody("test", body);
        var actual = JsonDocument.Parse(text).RootElement
            .EnumerateObject().Select(p => p.Name).OrderBy(n => n, StringComparer.Ordinal);
        Assert.Equal(expected.OrderBy(n => n, StringComparer.Ordinal), actual);
    }
}
