// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using Axiam.Sdk.Management.Models;
using System.Net.Http;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management;

/// <summary>
/// The ca_certificates management operations.
/// </summary>
/// <remarks>
/// <para>
/// A view over the client that created it, not a connection: constructing one performs no I/O
/// (&#167;27.2 rule 1), so there is nothing to cache and nothing to close.
/// </para>
/// </remarks>
public sealed class CaCertificatesApi
{
    private readonly ManagementTransport _transport;
    private readonly NamespaceScope _scope;

    internal CaCertificatesApi(ManagementTransport transport, NamespaceScope scope)
    {
        _transport = transport;
        _scope = scope;
    }

    /// <summary>
    /// Returns a handle addressing <paramref name="orgId"/> instead of the client's
    /// organization.
    /// </summary>
    /// <remarks>
    /// <para>
    /// A NEW handle: this one is unchanged, so a scoped call cannot leak into unrelated code
    /// holding the same reference (&#167;27.4 rule 3).
    /// </para>
    /// </remarks>
    /// <param name="orgId">the organization to address.</param>
    /// <returns>a CaCertificatesApi scoped to that organization</returns>
    public CaCertificatesApi InOrg(Guid orgId) =>
        new(_transport, _scope with { OrgId = orgId });

    /// <summary>
    /// Issues <c>GET /api/v1/organizations/{org_id}/ca-certificates</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Paginated: Total on the returned page is the size of the WHOLE set, not of this page
    /// (&#167;27.4 rule 4). Use ListAllAsync(...) to walk every page.
    /// </para>
    /// </remarks>
    /// <param name="page">where to start and how many to ask for, or <c>null</c> for the
    ///     server's default.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the page of results</returns>
    public async Task<Page<CaCertificate>> ListAsync(PageRequest? page = null, CancellationToken cancellationToken = default)
    {
        Guid orgId = ManagementSupport.ResolveOrg(_transport, _scope, "ca_certificates.list");
        string path = $"/api/v1/organizations/{orgId}/ca-certificates";
        Dictionary<string, string?> query = ManagementSupport.PageQuery(null, page);
        JsonElement? node = await _transport.SendAsync(
            "ca_certificates.list",
            HttpMethod.Get,
            "/api/v1/organizations/{org_id}/ca-certificates",
            path,
            query,
            null,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.DecodePage<CaCertificate>("ca_certificates.list", node);
    }

    /// <summary>
    /// Walks ListAsync to exhaustion and returns every item (&#167;27.4 rule 4).
    /// </summary>
    /// <remarks>
    /// <para>
    /// Stops on an empty page even when the server's Total disagrees, so a misreporting server
    /// costs one wasted request rather than an unbounded loop.
    /// </para>
    /// </remarks>
    /// <param name="start">the first window to request, or <c>null</c> for the server's
    ///     default.</param>
    /// <param name="cancellationToken">cancels the walk.</param>
    /// <returns>every item, in the server's order</returns>
    public Task<IReadOnlyList<CaCertificate>> ListAllAsync(PageRequest? start = null, CancellationToken cancellationToken = default) =>
        ManagementSupport.CollectPagesAsync(start, window =>
            ListAsync(page: window, cancellationToken: cancellationToken));

    /// <summary>
    /// Generate a CA. What that means depends on the configured key custodian, and deliberately
    /// not on the request: * Under <c>database</c> or <c>vault</c> custody, AXIAM generates a
    /// self-signed root and returns its private key once, in <c>private_key_pem</c>. * Under
    /// <c>vault_pki</c> custody, Vault generates a root and a signing intermediate beneath it,
    /// and the response has **no** <c>private_key_pem</c> because the key never existed outside
    /// Vault. The root's certificate comes back in <c>chain_pem</c>, which is the only copy
    /// anything outside Vault will see.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Issues <c>POST /api/v1/organizations/{org_id}/ca-certificates</c>.
    /// </para>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="body">the request body.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<GeneratedCaCertificate> GenerateAsync(CreateCaCertificateRequest body, CancellationToken cancellationToken = default)
    {
        Guid orgId = ManagementSupport.ResolveOrg(_transport, _scope, "ca_certificates.generate");
        string path = $"/api/v1/organizations/{orgId}/ca-certificates";
        string payload = ManagementSupport.EncodeBody("ca_certificates.generate", body);
        JsonElement? node = await _transport.SendAsync(
            "ca_certificates.generate",
            HttpMethod.Post,
            "/api/v1/organizations/{org_id}/ca-certificates",
            path,
            null,
            payload,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.Decode<GeneratedCaCertificate>("ca_certificates.generate", node);
    }

    /// <summary>
    /// Register a CA an organization already has, instead of generating one. The case this
    /// exists for: an organization whose root lives offline, in an HSM, or in an existing
    /// internal PKI, and which wants AXIAM in the chain rather than at the top of it. Without
    /// it, the only CA AXIAM could use was one it generated, which means every AXIAM-issued
    /// certificate chains to a root nothing else in the estate trusts. With a private key,
    /// AXIAM takes custody of it and can issue against the CA. Where it goes is the configured
    /// custodian's business: sealed into the row, written to Vault's KV engine, or — under
    /// <c>vault_pki</c> — imported into Vault's PKI engine as an issuer, after which AXIAM
    /// signs through Vault and holds nothing. That last one is the BYOK counterpart to
    /// generating in Vault: the key does pass through AXIAM's memory on the way in, because
    /// AXIAM is what received the request, but it is never stored here and every later use of
    /// it is Vault's. Without a private key, the certificate is a trust anchor and
    /// <c>/api/v1/certificates</c> says so rather than failing at the point of use. Gated on
    /// <c>ca_certificates:generate</c>: importing a CA is the same act as generating one from
    /// every relying party's point of view — it decides what this organization's certificates
    /// chain to.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Issues <c>POST /api/v1/organizations/{org_id}/ca-certificates/import</c>.
    /// </para>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="body">the request body.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<CaCertificate> ImportCaAsync(ImportCaCertificateRequest body, CancellationToken cancellationToken = default)
    {
        Guid orgId = ManagementSupport.ResolveOrg(_transport, _scope, "ca_certificates.import_ca");
        string path = $"/api/v1/organizations/{orgId}/ca-certificates/import";
        string payload = ManagementSupport.EncodeBody("ca_certificates.import_ca", body);
        JsonElement? node = await _transport.SendAsync(
            "ca_certificates.import_ca",
            HttpMethod.Post,
            "/api/v1/organizations/{org_id}/ca-certificates/import",
            path,
            null,
            payload,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.Decode<CaCertificate>("ca_certificates.import_ca", node);
    }

    /// <summary>
    /// Issues <c>GET /api/v1/organizations/{org_id}/ca-certificates/{id}</c>.
    /// </summary>
    /// <param name="id">the id to address.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<CaCertificate> GetAsync(Guid id, CancellationToken cancellationToken = default)
    {
        Guid orgId = ManagementSupport.ResolveOrg(_transport, _scope, "ca_certificates.get");
        string path = $"/api/v1/organizations/{orgId}/ca-certificates/{id}";
        JsonElement? node = await _transport.SendAsync(
            "ca_certificates.get",
            HttpMethod.Get,
            "/api/v1/organizations/{org_id}/ca-certificates/{id}",
            path,
            null,
            null,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.Decode<CaCertificate>("ca_certificates.get", node);
    }

    /// <summary>
    /// Issues <c>POST /api/v1/organizations/{org_id}/ca-certificates/{id}/revoke</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="id">the id to address.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>a task that completes when the server has answered</returns>
    public async Task RevokeAsync(Guid id, CancellationToken cancellationToken = default)
    {
        Guid orgId = ManagementSupport.ResolveOrg(_transport, _scope, "ca_certificates.revoke");
        string path = $"/api/v1/organizations/{orgId}/ca-certificates/{id}/revoke";
        await _transport.SendAsync(
            "ca_certificates.revoke",
            HttpMethod.Post,
            "/api/v1/organizations/{org_id}/ca-certificates/{id}/revoke",
            path,
            null,
            null,
            cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Move this CA's signing key to the custodian the deployment is configured for. Custody is
    /// recorded per CA rather than read from configuration, so adopting Vault does not move the
    /// CAs that already exist — their keys stay sealed in their rows until something moves
    /// them. This is that something, and without it the only route out of database custody is
    /// to generate a new CA and re-issue every leaf beneath it, which for a trust anchor means
    /// touching every relying party. Takes effect immediately; no restart. The row is the
    /// authority on where a key lives, and the signing path reads it per request.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Issues <c>POST /api/v1/organizations/{org_id}/ca-certificates/{id}/migrate-custody</c>.
    /// </para>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="id">the id to address.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<MigrateCustodyResponse> MigrateCustodyAsync(Guid id, CancellationToken cancellationToken = default)
    {
        Guid orgId = ManagementSupport.ResolveOrg(_transport, _scope, "ca_certificates.migrate_custody");
        string path = $"/api/v1/organizations/{orgId}/ca-certificates/{id}/migrate-custody";
        JsonElement? node = await _transport.SendAsync(
            "ca_certificates.migrate_custody",
            HttpMethod.Post,
            "/api/v1/organizations/{org_id}/ca-certificates/{id}/migrate-custody",
            path,
            null,
            null,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.Decode<MigrateCustodyResponse>("ca_certificates.migrate_custody", node);
    }

    /// <summary>
    /// Offer this CA — or stop offering it — as a trust anchor for mutual TLS. When enabled,
    /// the next server start exports this CA's **public** certificate into the client-CA bundle
    /// and turns on client-certificate verification in <c>optional</c> mode, unless the
    /// operator has configured <c>AXIAM__SERVER__TLS__CLIENT_AUTH</c> / <c>CLIENT_CA_PATH</c>
    /// themselves, which is never overridden. The signing key is not copied and stays with its
    /// custodian. <c>restart_required</c> is always true, and is the point of the response:
    /// there is no supported way to add a root to a rustls listener that is already serving.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Issues <c>PUT /api/v1/organizations/{org_id}/ca-certificates/{id}/mtls-trust-anchor</c>.
    /// </para>
    /// <para>
    /// A REPLACEMENT, not a patch: every field of the body is written, so read the current
    /// value first and carry over the parts you mean to keep (&#167;27.4 rule 5).
    /// </para>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="id">the id to address.</param>
    /// <param name="body">the request body.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<MtlsTrustAnchorResponse> SetMtlsTrustAnchorAsync(Guid id, SetMtlsTrustAnchor body, CancellationToken cancellationToken = default)
    {
        Guid orgId = ManagementSupport.ResolveOrg(_transport, _scope, "ca_certificates.set_mtls_trust_anchor");
        string path = $"/api/v1/organizations/{orgId}/ca-certificates/{id}/mtls-trust-anchor";
        string payload = ManagementSupport.EncodeBody("ca_certificates.set_mtls_trust_anchor", body);
        JsonElement? node = await _transport.SendAsync(
            "ca_certificates.set_mtls_trust_anchor",
            HttpMethod.Put,
            "/api/v1/organizations/{org_id}/ca-certificates/{id}/mtls-trust-anchor",
            path,
            null,
            payload,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.Decode<MtlsTrustAnchorResponse>("ca_certificates.set_mtls_trust_anchor", node);
    }

    /// <summary>
    /// Issues <c>GET /api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Paginated: Total on the returned page is the size of the WHOLE set, not of this page
    /// (&#167;27.4 rule 4). Use ListSigningCasAllAsync(...) to walk every page.
    /// </para>
    /// </remarks>
    /// <param name="tenantId">the tenant id to address.</param>
    /// <param name="page">where to start and how many to ask for, or <c>null</c> for the
    ///     server's default.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the page of results</returns>
    public async Task<Page<CaCertificate>> ListSigningCasAsync(Guid tenantId, PageRequest? page = null, CancellationToken cancellationToken = default)
    {
        Guid orgId = ManagementSupport.ResolveOrg(_transport, _scope, "ca_certificates.list_signing_cas");
        string path = $"/api/v1/organizations/{orgId}/tenants/{tenantId}/signing-cas";
        Dictionary<string, string?> query = ManagementSupport.PageQuery(null, page);
        JsonElement? node = await _transport.SendAsync(
            "ca_certificates.list_signing_cas",
            HttpMethod.Get,
            "/api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas",
            path,
            query,
            null,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.DecodePage<CaCertificate>("ca_certificates.list_signing_cas", node);
    }

    /// <summary>
    /// Walks ListSigningCasAsync to exhaustion and returns every item (&#167;27.4 rule 4).
    /// </summary>
    /// <remarks>
    /// <para>
    /// Stops on an empty page even when the server's Total disagrees, so a misreporting server
    /// costs one wasted request rather than an unbounded loop.
    /// </para>
    /// </remarks>
    /// <param name="tenantId">the tenant id to address.</param>
    /// <param name="start">the first window to request, or <c>null</c> for the server's
    ///     default.</param>
    /// <param name="cancellationToken">cancels the walk.</param>
    /// <returns>every item, in the server's order</returns>
    public Task<IReadOnlyList<CaCertificate>> ListSigningCasAllAsync(Guid tenantId, PageRequest? start = null, CancellationToken cancellationToken = default) =>
        ManagementSupport.CollectPagesAsync(start, window =>
            ListSigningCasAsync(tenantId: tenantId, page: window, cancellationToken: cancellationToken));

    /// <summary>
    /// Create a tenant signing CA beneath one of the organization's CAs, with the key generated
    /// by whoever the deployment's custodian is. The private key is returned exactly once — and
    /// not at all under <c>vault_pki</c>, where it was born inside Vault and no API exports it.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Issues <c>POST /api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas</c>.
    /// </para>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="tenantId">the tenant id to address.</param>
    /// <param name="body">the request body.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<GeneratedCaCertificate> GenerateSigningCaAsync(Guid tenantId, CreateIntermediateCaRequest body, CancellationToken cancellationToken = default)
    {
        Guid orgId = ManagementSupport.ResolveOrg(_transport, _scope, "ca_certificates.generate_signing_ca");
        string path = $"/api/v1/organizations/{orgId}/tenants/{tenantId}/signing-cas";
        string payload = ManagementSupport.EncodeBody("ca_certificates.generate_signing_ca", body);
        JsonElement? node = await _transport.SendAsync(
            "ca_certificates.generate_signing_ca",
            HttpMethod.Post,
            "/api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas",
            path,
            null,
            payload,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.Decode<GeneratedCaCertificate>("ca_certificates.generate_signing_ca", node);
    }

    /// <summary>
    /// Sign a certificate signing request the tenant produced elsewhere. The response has no
    /// <c>private_key_pem</c> because the key never reached AXIAM: it is wherever the CSR was
    /// made, and that is the point of this endpoint rather than a shortcoming of it.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Issues <c>POST
    /// /api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas/sign-csr</c>.
    /// </para>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="tenantId">the tenant id to address.</param>
    /// <param name="body">the request body.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<CaCertificate> SignSigningCaCsrAsync(Guid tenantId, SignIntermediateCsrRequest body, CancellationToken cancellationToken = default)
    {
        Guid orgId = ManagementSupport.ResolveOrg(_transport, _scope, "ca_certificates.sign_signing_ca_csr");
        string path = $"/api/v1/organizations/{orgId}/tenants/{tenantId}/signing-cas/sign-csr";
        string payload = ManagementSupport.EncodeBody("ca_certificates.sign_signing_ca_csr", body);
        JsonElement? node = await _transport.SendAsync(
            "ca_certificates.sign_signing_ca_csr",
            HttpMethod.Post,
            "/api/v1/organizations/{org_id}/tenants/{tenant_id}/signing-cas/sign-csr",
            path,
            null,
            payload,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.Decode<CaCertificate>("ca_certificates.sign_signing_ca_csr", node);
    }
}
