// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using Axiam.Sdk.Management.Models;
using System.Net.Http;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management;

/// <summary>
/// The certificates management operations.
/// </summary>
/// <remarks>
/// <para>
/// A view over the client that created it, not a connection: constructing one performs no I/O
/// (&#167;27.2 rule 1), so there is nothing to cache and nothing to close.
/// </para>
/// </remarks>
public sealed class CertificatesApi
{
    private readonly ManagementTransport _transport;
    private readonly NamespaceScope _scope;

    internal CertificatesApi(ManagementTransport transport, NamespaceScope scope)
    {
        _transport = transport;
        _scope = scope;
    }

    /// <summary>
    /// Issues <c>GET /api/v1/certificates</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Paginated: Total on the returned page is the size of the WHOLE set, not of this page
    /// (&#167;27.4 rule 4). Use ListAllAsync(...) to walk every page.
    /// </para>
    /// </remarks>
    /// <param name="page">where to start and how many to ask for, or <c>null</c> for the
    ///     server's default.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the page of results</returns>
    public async Task<Page<Certificate>> ListAsync(PageRequest? page = null, CancellationToken cancellationToken = default)
    {
        string path = $"/api/v1/certificates";
        Dictionary<string, string?> query = ManagementSupport.PageQuery(null, page);
        JsonElement? node = await _transport.SendAsync(
            "certificates.list",
            HttpMethod.Get,
            "/api/v1/certificates",
            path,
            query,
            null,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.DecodePage<Certificate>("certificates.list", node);
    }

    /// <summary>
    /// Walks ListAsync to exhaustion and returns every item (&#167;27.4 rule 4).
    /// </summary>
    /// <remarks>
    /// <para>
    /// Stops on an empty page even when the server's Total disagrees, so a misreporting server
    /// costs one wasted request rather than an unbounded loop.
    /// </para>
    /// </remarks>
    /// <param name="start">the first window to request, or <c>null</c> for the server's
    ///     default.</param>
    /// <param name="cancellationToken">cancels the walk.</param>
    /// <returns>every item, in the server's order</returns>
    public Task<IReadOnlyList<Certificate>> ListAllAsync(PageRequest? start = null, CancellationToken cancellationToken = default) =>
        ManagementSupport.CollectPagesAsync(start, window =>
            ListAsync(page: window, cancellationToken: cancellationToken));

    /// <summary>
    /// Issues <c>POST /api/v1/certificates</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="body">the request body.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<GeneratedCertificate> GenerateAsync(CreateCertificateRequest body, CancellationToken cancellationToken = default)
    {
        string path = $"/api/v1/certificates";
        string payload = ManagementSupport.EncodeBody("certificates.generate", body);
        JsonElement? node = await _transport.SendAsync(
            "certificates.generate",
            HttpMethod.Post,
            "/api/v1/certificates",
            path,
            null,
            payload,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.Decode<GeneratedCertificate>("certificates.generate", node);
    }

    /// <summary>
    /// Issues <c>GET /api/v1/certificates/{id}</c>.
    /// </summary>
    /// <param name="id">the id to address.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<Certificate> GetAsync(Guid id, CancellationToken cancellationToken = default)
    {
        string path = $"/api/v1/certificates/{id}";
        JsonElement? node = await _transport.SendAsync(
            "certificates.get",
            HttpMethod.Get,
            "/api/v1/certificates/{id}",
            path,
            null,
            null,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.Decode<Certificate>("certificates.get", node);
    }

    /// <summary>
    /// Issues <c>POST /api/v1/certificates/{id}/revoke</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="id">the id to address.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>a task that completes when the server has answered</returns>
    public async Task RevokeAsync(Guid id, CancellationToken cancellationToken = default)
    {
        string path = $"/api/v1/certificates/{id}/revoke";
        await _transport.SendAsync(
            "certificates.revoke",
            HttpMethod.Post,
            "/api/v1/certificates/{id}/revoke",
            path,
            null,
            null,
            cancellationToken).ConfigureAwait(false);
    }
}
