// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using Axiam.Sdk.Management.Models;
using System.Net.Http;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management;

/// <summary>
/// The directory management operations.
/// </summary>
/// <remarks>
/// <para>
/// A view over the client that created it, not a connection: constructing one performs no I/O
/// (&#167;27.2 rule 1), so there is nothing to cache and nothing to close.
/// </para>
/// </remarks>
public sealed class DirectoryApi
{
    private readonly ManagementTransport _transport;
    private readonly NamespaceScope _scope;

    internal DirectoryApi(ManagementTransport transport, NamespaceScope scope)
    {
        _transport = transport;
        _scope = scope;
    }

    /// <summary>
    /// Returns a handle addressing <paramref name="tenantId"/> instead of the client's tenant.
    /// </summary>
    /// <remarks>
    /// <para>
    /// A NEW handle: this one is unchanged (&#167;27.4 rule 3).
    /// </para>
    /// </remarks>
    /// <param name="tenantId">the tenant to address.</param>
    /// <returns>a DirectoryApi scoped to that tenant</returns>
    public DirectoryApi ForTenant(Guid tenantId) =>
        new(_transport, _scope with { TenantId = tenantId });

    /// <summary>
    /// Issues <c>GET /api/v1/tenants/{tenant_id}/directory</c>.
    /// </summary>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<DirectoryConfig> GetAsync(CancellationToken cancellationToken = default)
    {
        Guid tenantId = ManagementSupport.ResolveTenant(_transport, _scope, "directory.get");
        string path = $"/api/v1/tenants/{tenantId}/directory";
        JsonElement? node = await _transport.SendAsync(
            "directory.get",
            HttpMethod.Get,
            "/api/v1/tenants/{tenant_id}/directory",
            path,
            null,
            null,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.Decode<DirectoryConfig>("directory.get", node);
    }

    /// <summary>
    /// A replacement resets every omitted optional member to its default. <c>bind_secret</c> is
    /// required on create; on a replacement, absent keeps the stored secret — unless the write
    /// moves <c>url</c>, <c>start_tls</c>, <c>bind_dn</c> or <c>trust_anchors_pem</c>, which is
    /// a <c>400</c> without it.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Issues <c>PUT /api/v1/tenants/{tenant_id}/directory</c>.
    /// </para>
    /// <para>
    /// A REPLACEMENT, not a patch: what the body does not carry is not preserved (a member left
    /// unset is omitted from the wire, not sent as null), so read the current value first and
    /// carry over the parts you mean to keep (&#167;27.4 rule 5).
    /// </para>
    /// <para>
    /// <b>Moving the connection requires the secret again</b> (&#167;30.3 rule 2): a
    /// <c>SetAsync</c> that changes <c>url</c>, <c>start_tls</c>, <c>bind_dn</c> or
    /// <c>trust_anchors_pem</c> without <c>bind_secret</c> is refused <c>400</c> and changes
    /// nothing. The SDK holds no copy of the secret and cannot re-send one for you.
    /// <c>bind_secret</c> is required while the tenant has no configuration; otherwise absent
    /// keeps the stored secret. Every other optional member left out is <b>reset to its
    /// default</b>. An enabled directory and an effective <c>opaque_mode = required</c> never
    /// coexist (<c>409</c>); without the deployment's directory key a write carrying a secret
    /// is <c>503</c>.
    /// </para>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="body">the request body.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<DirectoryConfig> SetAsync(SetDirectoryConfig body, CancellationToken cancellationToken = default)
    {
        Guid tenantId = ManagementSupport.ResolveTenant(_transport, _scope, "directory.set");
        string path = $"/api/v1/tenants/{tenantId}/directory";
        string payload = ManagementSupport.EncodeBody("directory.set", body);
        JsonElement? node = await _transport.SendAsync(
            "directory.set",
            HttpMethod.Put,
            "/api/v1/tenants/{tenant_id}/directory",
            path,
            null,
            payload,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.Decode<DirectoryConfig>("directory.set", node);
    }

    /// <summary>
    /// Issues <c>PATCH /api/v1/tenants/{tenant_id}/directory</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// A SPARSE update: the properties you leave unset are omitted from the wire body entirely
    /// and left unchanged (&#167;27.4 rule 5).
    /// </para>
    /// <para>
    /// <b>Moving the connection requires the secret again</b> (&#167;30.3 rule 2): an
    /// <c>UpdateAsync</c> that changes <c>url</c>, <c>start_tls</c>, <c>bind_dn</c> or
    /// <c>trust_anchors_pem</c> without <c>bind_secret</c> is refused <c>400</c> and changes
    /// nothing; the SDK holds no copy of the secret to re-send. A member left unset
    /// (<c>null</c>) is not sent and stays as stored; <c>GroupBaseDn</c> / <c>GroupFilter</c>
    /// set to <c>JsonNullable&lt;string&gt;.Null</c> are sent as <c>null</c> and clear the
    /// value. An enabled directory and an effective <c>opaque_mode = required</c> never coexist
    /// (<c>409</c>).
    /// </para>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="body">the request body.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<DirectoryConfig> UpdateAsync(UpdateDirectoryConfig body, CancellationToken cancellationToken = default)
    {
        Guid tenantId = ManagementSupport.ResolveTenant(_transport, _scope, "directory.update");
        string path = $"/api/v1/tenants/{tenantId}/directory";
        string payload = ManagementSupport.EncodeBody("directory.update", body);
        JsonElement? node = await _transport.SendAsync(
            "directory.update",
            HttpMethod.Patch,
            "/api/v1/tenants/{tenant_id}/directory",
            path,
            null,
            payload,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.Decode<DirectoryConfig>("directory.update", node);
    }

    /// <summary>
    /// Removes the configuration and its sync state. Directory accounts can no longer sign in
    /// with a password (there is no fallback to a local hash) and the sync job stops for the
    /// tenant; sessions, refresh tokens and passkeys they already hold keep working until they
    /// expire or an administrator deactivates the accounts. There is no unlink.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Issues <c>DELETE /api/v1/tenants/{tenant_id}/directory</c>.
    /// </para>
    /// <para>
    /// <b>Deleting stops the directory, and only that</b> (&#167;30.3 rule 5): directory
    /// accounts can no longer sign in with a password &#8212; there is no fallback to a local
    /// hash &#8212; and the sync stops. Sessions, refresh tokens and passkeys those accounts
    /// already hold keep working until they expire or the accounts are deactivated. There is no
    /// unlink: a linked account stays a directory account.
    /// </para>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>a task that completes when the server has answered</returns>
    public async Task DeleteAsync(CancellationToken cancellationToken = default)
    {
        Guid tenantId = ManagementSupport.ResolveTenant(_transport, _scope, "directory.delete");
        string path = $"/api/v1/tenants/{tenantId}/directory";
        await _transport.SendAsync(
            "directory.delete",
            HttpMethod.Delete,
            "/api/v1/tenants/{tenant_id}/directory",
            path,
            null,
            null,
            cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// The directory resolves the entry from the account's own username; the caller supplies
    /// only the account. Marks the account, deletes its WebAuthn credentials and federation
    /// links, revokes its <c>User</c>-type certificates and then all its sessions and OAuth2
    /// refresh tokens (TOTP is kept): **the owner is signed out everywhere**. Idempotent: an
    /// account already linked to that entry gets <c>200</c> with <c>was_already_linked:
    /// true</c> and the revocations run again.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Issues <c>POST /api/v1/tenants/{tenant_id}/directory/links</c>.
    /// </para>
    /// <para>
    /// <b>Signs the account's owner out everywhere</b> (&#167;30.3 rule 6): linking deletes the
    /// account's WebAuthn credentials and federation links, revokes its <c>User</c>
    /// certificates, all its sessions and its OAuth2 refresh tokens (TOTP is kept). The entry
    /// is found by the account's own username; a repeat on an already-linked account answers
    /// <c>was_already_linked</c> and repeats the revocations.
    /// </para>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="body">the request body.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<DirectoryLinkResult> LinkAccountAsync(LinkDirectoryAccount body, CancellationToken cancellationToken = default)
    {
        Guid tenantId = ManagementSupport.ResolveTenant(_transport, _scope, "directory.link_account");
        string path = $"/api/v1/tenants/{tenantId}/directory/links";
        string payload = ManagementSupport.EncodeBody("directory.link_account", body);
        JsonElement? node = await _transport.SendAsync(
            "directory.link_account",
            HttpMethod.Post,
            "/api/v1/tenants/{tenant_id}/directory/links",
            path,
            null,
            payload,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.Decode<DirectoryLinkResult>("directory.link_account", node);
    }

    /// <summary>
    /// Issues <c>GET /api/v1/tenants/{tenant_id}/directory/sync-status</c>.
    /// </summary>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<DirectorySyncStatus> GetSyncStatusAsync(CancellationToken cancellationToken = default)
    {
        Guid tenantId = ManagementSupport.ResolveTenant(_transport, _scope, "directory.get_sync_status");
        string path = $"/api/v1/tenants/{tenantId}/directory/sync-status";
        JsonElement? node = await _transport.SendAsync(
            "directory.get_sync_status",
            HttpMethod.Get,
            "/api/v1/tenants/{tenant_id}/directory/sync-status",
            path,
            null,
            null,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.Decode<DirectorySyncStatus>("directory.get_sync_status", node);
    }
}
