// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using Axiam.Sdk.Management.Models;
using System.Net.Http;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management;

/// <summary>
/// The federation management operations.
/// </summary>
/// <remarks>
/// <para>
/// A view over the client that created it, not a connection: constructing one performs no I/O
/// (&#167;27.2 rule 1), so there is nothing to cache and nothing to close.
/// </para>
/// </remarks>
public sealed class FederationApi
{
    private readonly ManagementTransport _transport;
    private readonly NamespaceScope _scope;

    internal FederationApi(ManagementTransport transport, NamespaceScope scope)
    {
        _transport = transport;
        _scope = scope;
    }

    /// <summary>
    /// Issues <c>GET /api/v1/federation-configs</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Paginated: Total on the returned page is the size of the WHOLE set, not of this page
    /// (&#167;27.4 rule 4). Use ListConfigsAllAsync(...) to walk every page.
    /// </para>
    /// </remarks>
    /// <param name="page">where to start and how many to ask for, or <c>null</c> for the
    ///     server's default.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the page of results</returns>
    public async Task<Page<FederationConfigResponse>> ListConfigsAsync(PageRequest? page = null, CancellationToken cancellationToken = default)
    {
        string path = $"/api/v1/federation-configs";
        Dictionary<string, string?> query = ManagementSupport.PageQuery(null, page);
        JsonElement? node = await _transport.SendAsync(
            "federation.list_configs",
            HttpMethod.Get,
            "/api/v1/federation-configs",
            path,
            query,
            null,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.DecodePage<FederationConfigResponse>("federation.list_configs", node);
    }

    /// <summary>
    /// Walks ListConfigsAsync to exhaustion and returns every item (&#167;27.4 rule 4).
    /// </summary>
    /// <remarks>
    /// <para>
    /// Stops on an empty page even when the server's Total disagrees, so a misreporting server
    /// costs one wasted request rather than an unbounded loop.
    /// </para>
    /// </remarks>
    /// <param name="start">the first window to request, or <c>null</c> for the server's
    ///     default.</param>
    /// <param name="cancellationToken">cancels the walk.</param>
    /// <returns>every item, in the server's order</returns>
    public Task<IReadOnlyList<FederationConfigResponse>> ListConfigsAllAsync(PageRequest? start = null, CancellationToken cancellationToken = default) =>
        ManagementSupport.CollectPagesAsync(start, window =>
            ListConfigsAsync(page: window, cancellationToken: cancellationToken));

    /// <summary>
    /// Issues <c>POST /api/v1/federation-configs</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="body">the request body.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<FederationConfigResponse> CreateConfigAsync(CreateFederationConfigRequest body, CancellationToken cancellationToken = default)
    {
        string path = $"/api/v1/federation-configs";
        string payload = ManagementSupport.EncodeBody("federation.create_config", body);
        JsonElement? node = await _transport.SendAsync(
            "federation.create_config",
            HttpMethod.Post,
            "/api/v1/federation-configs",
            path,
            null,
            payload,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.Decode<FederationConfigResponse>("federation.create_config", node);
    }

    /// <summary>
    /// Issues <c>GET /api/v1/federation-configs/{id}</c>.
    /// </summary>
    /// <param name="id">the id to address.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<FederationConfigResponse> GetConfigAsync(Guid id, CancellationToken cancellationToken = default)
    {
        string path = $"/api/v1/federation-configs/{id}";
        JsonElement? node = await _transport.SendAsync(
            "federation.get_config",
            HttpMethod.Get,
            "/api/v1/federation-configs/{id}",
            path,
            null,
            null,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.Decode<FederationConfigResponse>("federation.get_config", node);
    }

    /// <summary>
    /// Issues <c>PUT /api/v1/federation-configs/{id}</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// A SPARSE update: the properties you leave unset are omitted from the wire body entirely
    /// and left unchanged (&#167;27.4 rule 5).
    /// </para>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="id">the id to address.</param>
    /// <param name="body">the request body.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<FederationConfigResponse> UpdateConfigAsync(Guid id, UpdateFederationConfigRequest body, CancellationToken cancellationToken = default)
    {
        string path = $"/api/v1/federation-configs/{id}";
        string payload = ManagementSupport.EncodeBody("federation.update_config", body);
        JsonElement? node = await _transport.SendAsync(
            "federation.update_config",
            HttpMethod.Put,
            "/api/v1/federation-configs/{id}",
            path,
            null,
            payload,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.Decode<FederationConfigResponse>("federation.update_config", node);
    }

    /// <summary>
    /// Issues <c>DELETE /api/v1/federation-configs/{id}</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="id">the id to address.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>a task that completes when the server has answered</returns>
    public async Task DeleteConfigAsync(Guid id, CancellationToken cancellationToken = default)
    {
        string path = $"/api/v1/federation-configs/{id}";
        await _transport.SendAsync(
            "federation.delete_config",
            HttpMethod.Delete,
            "/api/v1/federation-configs/{id}",
            path,
            null,
            null,
            cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Issues <c>GET /api/v1/federation-links/user/{user_id}</c>.
    /// </summary>
    /// <param name="userId">the user id to address.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<IReadOnlyList<FederationLinkResponse>> ListUserLinksAsync(Guid userId, CancellationToken cancellationToken = default)
    {
        string path = $"/api/v1/federation-links/user/{userId}";
        JsonElement? node = await _transport.SendAsync(
            "federation.list_user_links",
            HttpMethod.Get,
            "/api/v1/federation-links/user/{user_id}",
            path,
            null,
            null,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.DecodeList<FederationLinkResponse>("federation.list_user_links", node);
    }

    /// <summary>
    /// Issues <c>DELETE /api/v1/federation-links/{id}</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="id">the id to address.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>a task that completes when the server has answered</returns>
    public async Task DeleteLinkAsync(Guid id, CancellationToken cancellationToken = default)
    {
        string path = $"/api/v1/federation-links/{id}";
        await _transport.SendAsync(
            "federation.delete_link",
            HttpMethod.Delete,
            "/api/v1/federation-links/{id}",
            path,
            null,
            null,
            cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Builds the authorization URL for the external OIDC provider. The caller is responsible
    /// for generating and storing <c>state</c> and <c>nonce</c> values for CSRF and replay
    /// protection. TODO(T19.9): This endpoint currently requires authentication, making it
    /// usable only for account-linking (already-authenticated users). Add separate
    /// unauthenticated federation login endpoints that complete the external flow and return
    /// access/refresh tokens for first-time login.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Issues <c>POST /api/v1/federation/oidc/authorize</c>.
    /// </para>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="body">the request body.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<OidcAuthorizeResponse> OidcAuthorizeAsync(OidcAuthorizeRequest body, CancellationToken cancellationToken = default)
    {
        string path = $"/api/v1/federation/oidc/authorize";
        string payload = ManagementSupport.EncodeBody("federation.oidc_authorize", body);
        JsonElement? node = await _transport.SendAsync(
            "federation.oidc_authorize",
            HttpMethod.Post,
            "/api/v1/federation/oidc/authorize",
            path,
            null,
            payload,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.Decode<OidcAuthorizeResponse>("federation.oidc_authorize", node);
    }

    /// <summary>
    /// Handles the callback from the external OIDC provider after user authentication.
    /// Exchanges the authorization code for tokens, validates the ID token, and provisions or
    /// links the local user.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Issues <c>POST /api/v1/federation/oidc/callback</c>.
    /// </para>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="body">the request body.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<OidcCallbackResponse> OidcCallbackAsync(OidcCallbackRequest body, CancellationToken cancellationToken = default)
    {
        string path = $"/api/v1/federation/oidc/callback";
        string payload = ManagementSupport.EncodeBody("federation.oidc_callback", body);
        JsonElement? node = await _transport.SendAsync(
            "federation.oidc_callback",
            HttpMethod.Post,
            "/api/v1/federation/oidc/callback",
            path,
            null,
            payload,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.Decode<OidcCallbackResponse>("federation.oidc_callback", node);
    }
}
