// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management;

/// <summary>
/// The CONTRACT.md &#167;27 management API: 147 operations across 24 namespaces.
/// </summary>
/// <remarks>
/// <para>
/// Obtained from <c>client.Management</c>. Each accessor returns a namespace handle, which is a
/// view over the same session — acquiring one performs no I/O (&#167;27.2 rule 1).
/// </para>
/// <para>
/// The namespaces are grouped behind this one accessor rather than added to AxiamClient
/// directly: &#167;27.2's own argument for handles is that a flat surface of 147 methods buries
/// the twenty a given caller needs, and hanging 24 more members off AxiamClient would do to it
/// exactly what the handles exist to prevent.
/// </para>
/// </remarks>
public sealed class ManagementApi
{
    private readonly ManagementTransport _transport;

    internal ManagementApi(ManagementTransport transport)
    {
        _transport = transport;
    }

    /// <summary>
    /// The organizations operations.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Acquiring the handle performs no I/O (&#167;27.2 rule 1).
    /// </para>
    /// </remarks>
    public OrganizationsApi Organizations => new(_transport, new NamespaceScope());

    /// <summary>
    /// The tenants operations.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Acquiring the handle performs no I/O (&#167;27.2 rule 1).
    /// </para>
    /// </remarks>
    public TenantsApi Tenants => new(_transport, new NamespaceScope());

    /// <summary>
    /// The users operations.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Acquiring the handle performs no I/O (&#167;27.2 rule 1).
    /// </para>
    /// </remarks>
    public UsersApi Users => new(_transport, new NamespaceScope());

    /// <summary>
    /// The groups operations.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Acquiring the handle performs no I/O (&#167;27.2 rule 1).
    /// </para>
    /// </remarks>
    public GroupsApi Groups => new(_transport, new NamespaceScope());

    /// <summary>
    /// The roles operations.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Acquiring the handle performs no I/O (&#167;27.2 rule 1).
    /// </para>
    /// </remarks>
    public RolesApi Roles => new(_transport, new NamespaceScope());

    /// <summary>
    /// The permissions operations.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Acquiring the handle performs no I/O (&#167;27.2 rule 1).
    /// </para>
    /// </remarks>
    public PermissionsApi Permissions => new(_transport, new NamespaceScope());

    /// <summary>
    /// The resources operations.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Acquiring the handle performs no I/O (&#167;27.2 rule 1).
    /// </para>
    /// </remarks>
    public ResourcesApi Resources => new(_transport, new NamespaceScope());

    /// <summary>
    /// The scopes operations.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Acquiring the handle performs no I/O (&#167;27.2 rule 1).
    /// </para>
    /// </remarks>
    public ScopesApi Scopes => new(_transport, new NamespaceScope());

    /// <summary>
    /// The service_accounts operations.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Acquiring the handle performs no I/O (&#167;27.2 rule 1).
    /// </para>
    /// </remarks>
    public ServiceAccountsApi ServiceAccounts => new(_transport, new NamespaceScope());

    /// <summary>
    /// The certificates operations.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Acquiring the handle performs no I/O (&#167;27.2 rule 1).
    /// </para>
    /// </remarks>
    public CertificatesApi Certificates => new(_transport, new NamespaceScope());

    /// <summary>
    /// The ca_certificates operations.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Acquiring the handle performs no I/O (&#167;27.2 rule 1).
    /// </para>
    /// </remarks>
    public CaCertificatesApi CaCertificates => new(_transport, new NamespaceScope());

    /// <summary>
    /// The pgp_keys operations.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Acquiring the handle performs no I/O (&#167;27.2 rule 1).
    /// </para>
    /// </remarks>
    public PgpKeysApi PgpKeys => new(_transport, new NamespaceScope());

    /// <summary>
    /// The webhooks operations.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Acquiring the handle performs no I/O (&#167;27.2 rule 1).
    /// </para>
    /// </remarks>
    public WebhooksApi Webhooks => new(_transport, new NamespaceScope());

    /// <summary>
    /// The oauth2_clients operations.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Acquiring the handle performs no I/O (&#167;27.2 rule 1).
    /// </para>
    /// </remarks>
    public Oauth2ClientsApi Oauth2Clients => new(_transport, new NamespaceScope());

    /// <summary>
    /// The federation operations.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Acquiring the handle performs no I/O (&#167;27.2 rule 1).
    /// </para>
    /// </remarks>
    public FederationApi Federation => new(_transport, new NamespaceScope());

    /// <summary>
    /// The notification_rules operations.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Acquiring the handle performs no I/O (&#167;27.2 rule 1).
    /// </para>
    /// </remarks>
    public NotificationRulesApi NotificationRules => new(_transport, new NamespaceScope());

    /// <summary>
    /// The email_config operations.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Acquiring the handle performs no I/O (&#167;27.2 rule 1).
    /// </para>
    /// </remarks>
    public EmailConfigApi EmailConfig => new(_transport, new NamespaceScope());

    /// <summary>
    /// The settings operations.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Acquiring the handle performs no I/O (&#167;27.2 rule 1).
    /// </para>
    /// </remarks>
    public SettingsApi Settings => new(_transport, new NamespaceScope());

    /// <summary>
    /// The scim_tokens operations.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Acquiring the handle performs no I/O (&#167;27.2 rule 1).
    /// </para>
    /// </remarks>
    public ScimTokensApi ScimTokens => new(_transport, new NamespaceScope());

    /// <summary>
    /// The reactors operations.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Acquiring the handle performs no I/O (&#167;27.2 rule 1).
    /// </para>
    /// </remarks>
    public ReactorsApi Reactors => new(_transport, new NamespaceScope());

    /// <summary>
    /// The webauthn_policy operations.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Acquiring the handle performs no I/O (&#167;27.2 rule 1).
    /// </para>
    /// </remarks>
    public WebauthnPolicyApi WebauthnPolicy => new(_transport, new NamespaceScope());

    /// <summary>
    /// The audit operations.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Acquiring the handle performs no I/O (&#167;27.2 rule 1).
    /// </para>
    /// </remarks>
    public AuditApi Audit => new(_transport, new NamespaceScope());

    /// <summary>
    /// The privacy operations.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Acquiring the handle performs no I/O (&#167;27.2 rule 1).
    /// </para>
    /// </remarks>
    public PrivacyApi Privacy => new(_transport, new NamespaceScope());

    /// <summary>
    /// The platform operations.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Acquiring the handle performs no I/O (&#167;27.2 rule 1).
    /// </para>
    /// </remarks>
    public PlatformApi Platform => new(_transport, new NamespaceScope());

    /// <summary>
    /// The &#167;27.6 declarative layer: describe the tenant you want, then reconcile.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Acquiring the handle performs no I/O (&#167;27.2 rule 1).
    /// </para>
    /// </remarks>
    public ManifestApi Manifest => new(this);
}
