// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using Axiam.Sdk.Management.Models;
using System.Net.Http;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management;

/// <summary>
/// The privacy management operations.
/// </summary>
/// <remarks>
/// <para>
/// A view over the client that created it, not a connection: constructing one performs no I/O
/// (&#167;27.2 rule 1), so there is nothing to cache and nothing to close.
/// </para>
/// </remarks>
public sealed class PrivacyApi
{
    private readonly ManagementTransport _transport;
    private readonly NamespaceScope _scope;

    internal PrivacyApi(ManagementTransport transport, NamespaceScope scope)
    {
        _transport = transport;
        _scope = scope;
    }

    /// <summary>
    /// Enqueues an async GDPR Art. 15 data-export job. Returns immediately with <c>{"queued":
    /// true}</c>; the cleanup sweep generates the encrypted JSON, stores it, and emails a
    /// single-use 24 h download link (D-12). Self-service (own account) or admin with
    /// <c>gdpr:export</c> permission.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Issues <c>POST /api/v1/account/export</c>.
    /// </para>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>a task that completes when the server has answered</returns>
    public async Task RequestExportAsync(CancellationToken cancellationToken = default)
    {
        string path = $"/api/v1/account/export";
        await _transport.SendAsync(
            "privacy.request_export",
            HttpMethod.Post,
            "/api/v1/account/export",
            path,
            null,
            null,
            cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Single-use download of the GDPR export blob (D-13). Looks up the job by SHA-256(token),
    /// verifies it is ready and not expired/used, decrypts the blob, marks it as downloaded,
    /// and deletes the record. Requires authentication (self or admin with <c>gdpr:export</c>).
    /// </summary>
    /// <remarks>
    /// <para>
    /// Issues <c>GET /api/v1/account/export/{token}</c>.
    /// </para>
    /// </remarks>
    /// <param name="token">the token to address.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>a task that completes when the server has answered</returns>
    public async Task DownloadExportAsync(Guid token, CancellationToken cancellationToken = default)
    {
        string path = $"/api/v1/account/export/{token}";
        await _transport.SendAsync(
            "privacy.download_export",
            HttpMethod.Get,
            "/api/v1/account/export/{token}",
            path,
            null,
            null,
            cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Initiates Art. 17 erasure: immediately disables the account, revokes all sessions,
    /// emails a single-use cancel link, and schedules purge at +30 d (D-07/D-08/D-09).
    /// Self-service (own account) or admin with <c>users:erase</c> permission.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Issues <c>POST /api/v1/account/delete</c>.
    /// </para>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>a task that completes when the server has answered</returns>
    public async Task RequestDeleteAsync(CancellationToken cancellationToken = default)
    {
        string path = $"/api/v1/account/delete";
        await _transport.SendAsync(
            "privacy.request_delete",
            HttpMethod.Post,
            "/api/v1/account/delete",
            path,
            null,
            null,
            cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// **Public endpoint** (token-authenticated; listed in <c>PUBLIC_PATHS</c>). Validates the
    /// single-use cancel token; if the deletion is still pending and within the grace window,
    /// aborts it and re-enables the account (D-09). A second call with the same token is
    /// rejected (single-use).
    /// </summary>
    /// <remarks>
    /// <para>
    /// Issues <c>GET /api/v1/auth/account/delete/cancel</c>.
    /// </para>
    /// </remarks>
    /// <param name="token">the optional token filter, or <c>null</c> to omit it.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>a task that completes when the server has answered</returns>
    public async Task CancelDeleteAsync(string? token = null, CancellationToken cancellationToken = default)
    {
        string path = $"/api/v1/auth/account/delete/cancel";
        Dictionary<string, string?> query = new Dictionary<string, string?>(StringComparer.Ordinal) { ["token"] = token };
        await _transport.SendAsync(
            "privacy.cancel_delete",
            HttpMethod.Get,
            "/api/v1/auth/account/delete/cancel",
            path,
            query,
            null,
            cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Art. 7(1) says a controller must be able to demonstrate that consent was given; Art.
    /// 15(1)(a) says the subject may see what is held about them. This endpoint is the second,
    /// and it is also the page the withdrawal control lives on.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Issues <c>GET /api/v1/account/consents</c>.
    /// </para>
    /// </remarks>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<IReadOnlyList<ConsentView>> ListConsentsAsync(CancellationToken cancellationToken = default)
    {
        string path = $"/api/v1/account/consents";
        JsonElement? node = await _transport.SendAsync(
            "privacy.list_consents",
            HttpMethod.Get,
            "/api/v1/account/consents",
            path,
            null,
            null,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.DecodeList<ConsentView>("privacy.list_consents", node);
    }

    /// <summary>
    /// What the SPA's consent screen calls when the end user says yes. Everything it accepts is
    /// checked against the registration rather than taken on trust, because a consent record is
    /// the thing UserInfo releases personal data on the strength of: * the scopes must be
    /// sensitive ones — nothing else belongs in this namespace, and a record naming
    /// <c>openid</c> would be a record that never matches and never expires; * the client must
    /// exist in the caller's tenant; * the client must have every named scope **registered**,
    /// so a consent cannot be recorded for a release the client could never have been
    /// authorised for; * the tenant switch must be on, so consent collected while the
    /// capability is off cannot sit waiting for somebody to turn it on. Idempotent: the
    /// <c>(tenant, user, type, version)</c> index makes a repeated grant the same grant, and a
    /// second call is answered <c>200</c> rather than a conflict. A consent screen the user
    /// double-submits has consented once.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Issues <c>POST /api/v1/account/consents/oidc-scopes</c>.
    /// </para>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="body">the request body.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>a task that completes when the server has answered</returns>
    public async Task GrantScopeConsentAsync(GrantScopeConsent body, CancellationToken cancellationToken = default)
    {
        string path = $"/api/v1/account/consents/oidc-scopes";
        string payload = ManagementSupport.EncodeBody("privacy.grant_scope_consent", body);
        await _transport.SendAsync(
            "privacy.grant_scope_consent",
            HttpMethod.Post,
            "/api/v1/account/consents/oidc-scopes",
            path,
            null,
            payload,
            cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Art. 7(3): as easy to withdraw as to give. One call, no grace period, no confirmation
    /// step, and it takes effect on the **next UserInfo call with the token the relying party
    /// already holds** — not on the next token. That is the property T8.4 asserts, and it is
    /// why the release gate re-reads the record on every call rather than trusting the one
    /// taken at authorization. Withdraws every scope set consented to for this relying party,
    /// not one of them: a subject saying "stop giving my address to this app" does not mean
    /// "stop giving it under the two-scope record but carry on under the one-scope one".
    /// Answers <c>200</c> whether or not anything was there, and says how many records went. A
    /// subject who withdraws twice is not told off, and an attacker who guesses
    /// <c>client_id</c>s learns nothing from the status code — though they would have to be the
    /// subject to ask at all.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Issues <c>DELETE /api/v1/account/consents/oidc-scopes/{client_id}</c>.
    /// </para>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="clientId">the client id to address.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>a task that completes when the server has answered</returns>
    public async Task WithdrawScopeConsentAsync(Guid clientId, CancellationToken cancellationToken = default)
    {
        string path = $"/api/v1/account/consents/oidc-scopes/{clientId}";
        await _transport.SendAsync(
            "privacy.withdraw_scope_consent",
            HttpMethod.Delete,
            "/api/v1/account/consents/oidc-scopes/{client_id}",
            path,
            null,
            null,
            cancellationToken).ConfigureAwait(false);
    }
}
