// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using Axiam.Sdk.Management.Models;
using System.Net.Http;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management;

/// <summary>
/// The resources management operations.
/// </summary>
/// <remarks>
/// <para>
/// A view over the client that created it, not a connection: constructing one performs no I/O
/// (&#167;27.2 rule 1), so there is nothing to cache and nothing to close.
/// </para>
/// </remarks>
public sealed class ResourcesApi
{
    private readonly ManagementTransport _transport;
    private readonly NamespaceScope _scope;

    internal ResourcesApi(ManagementTransport transport, NamespaceScope scope)
    {
        _transport = transport;
        _scope = scope;
    }

    /// <summary>
    /// Issues <c>GET /api/v1/resources</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Paginated: Total on the returned page is the size of the WHOLE set, not of this page
    /// (&#167;27.4 rule 4). Use ListAllAsync(...) to walk every page.
    /// </para>
    /// </remarks>
    /// <param name="page">where to start and how many to ask for, or <c>null</c> for the
    ///     server's default.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the page of results</returns>
    public async Task<Page<Resource>> ListAsync(PageRequest? page = null, CancellationToken cancellationToken = default)
    {
        string path = $"/api/v1/resources";
        Dictionary<string, string?> query = ManagementSupport.PageQuery(null, page);
        JsonElement? node = await _transport.SendAsync(
            "resources.list",
            HttpMethod.Get,
            "/api/v1/resources",
            path,
            query,
            null,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.DecodePage<Resource>("resources.list", node);
    }

    /// <summary>
    /// Walks ListAsync to exhaustion and returns every item (&#167;27.4 rule 4).
    /// </summary>
    /// <remarks>
    /// <para>
    /// Stops on an empty page even when the server's Total disagrees, so a misreporting server
    /// costs one wasted request rather than an unbounded loop.
    /// </para>
    /// </remarks>
    /// <param name="start">the first window to request, or <c>null</c> for the server's
    ///     default.</param>
    /// <param name="cancellationToken">cancels the walk.</param>
    /// <returns>every item, in the server's order</returns>
    public Task<IReadOnlyList<Resource>> ListAllAsync(PageRequest? start = null, CancellationToken cancellationToken = default) =>
        ManagementSupport.CollectPagesAsync(start, window =>
            ListAsync(page: window, cancellationToken: cancellationToken));

    /// <summary>
    /// Issues <c>POST /api/v1/resources</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="body">the request body.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<Resource> CreateAsync(CreateResourceRequest body, CancellationToken cancellationToken = default)
    {
        string path = $"/api/v1/resources";
        string payload = ManagementSupport.EncodeBody("resources.create", body);
        JsonElement? node = await _transport.SendAsync(
            "resources.create",
            HttpMethod.Post,
            "/api/v1/resources",
            path,
            null,
            payload,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.Decode<Resource>("resources.create", node);
    }

    /// <summary>
    /// Issues <c>GET /api/v1/resources/{resource_id}</c>.
    /// </summary>
    /// <param name="resourceId">the resource id to address.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<Resource> GetAsync(Guid resourceId, CancellationToken cancellationToken = default)
    {
        string path = $"/api/v1/resources/{resourceId}";
        JsonElement? node = await _transport.SendAsync(
            "resources.get",
            HttpMethod.Get,
            "/api/v1/resources/{resource_id}",
            path,
            null,
            null,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.Decode<Resource>("resources.get", node);
    }

    /// <summary>
    /// Issues <c>PUT /api/v1/resources/{resource_id}</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// A SPARSE update: the properties you leave unset are omitted from the wire body entirely
    /// and left unchanged (&#167;27.4 rule 5).
    /// </para>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="resourceId">the resource id to address.</param>
    /// <param name="body">the request body.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<Resource> UpdateAsync(Guid resourceId, UpdateResourceRequest body, CancellationToken cancellationToken = default)
    {
        string path = $"/api/v1/resources/{resourceId}";
        string payload = ManagementSupport.EncodeBody("resources.update", body);
        JsonElement? node = await _transport.SendAsync(
            "resources.update",
            HttpMethod.Put,
            "/api/v1/resources/{resource_id}",
            path,
            null,
            payload,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.Decode<Resource>("resources.update", node);
    }

    /// <summary>
    /// Issues <c>DELETE /api/v1/resources/{resource_id}</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="resourceId">the resource id to address.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>a task that completes when the server has answered</returns>
    public async Task DeleteAsync(Guid resourceId, CancellationToken cancellationToken = default)
    {
        string path = $"/api/v1/resources/{resourceId}";
        await _transport.SendAsync(
            "resources.delete",
            HttpMethod.Delete,
            "/api/v1/resources/{resource_id}",
            path,
            null,
            null,
            cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Issues <c>GET /api/v1/resources/{resource_id}/children</c>.
    /// </summary>
    /// <param name="resourceId">the resource id to address.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<IReadOnlyList<Resource>> ListChildrenAsync(Guid resourceId, CancellationToken cancellationToken = default)
    {
        string path = $"/api/v1/resources/{resourceId}/children";
        JsonElement? node = await _transport.SendAsync(
            "resources.list_children",
            HttpMethod.Get,
            "/api/v1/resources/{resource_id}/children",
            path,
            null,
            null,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.DecodeList<Resource>("resources.list_children", node);
    }

    /// <summary>
    /// Issues <c>GET /api/v1/resources/{resource_id}/ancestors</c>.
    /// </summary>
    /// <param name="resourceId">the resource id to address.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<IReadOnlyList<Resource>> ListAncestorsAsync(Guid resourceId, CancellationToken cancellationToken = default)
    {
        string path = $"/api/v1/resources/{resourceId}/ancestors";
        JsonElement? node = await _transport.SendAsync(
            "resources.list_ancestors",
            HttpMethod.Get,
            "/api/v1/resources/{resource_id}/ancestors",
            path,
            null,
            null,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.DecodeList<Resource>("resources.list_ancestors", node);
    }
}
