// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using Axiam.Sdk.Management.Models;
using System.Net.Http;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management;

/// <summary>
/// The saml management operations.
/// </summary>
/// <remarks>
/// <para>
/// A view over the client that created it, not a connection: constructing one performs no I/O
/// (&#167;27.2 rule 1), so there is nothing to cache and nothing to close.
/// </para>
/// </remarks>
public sealed class SamlApi
{
    private readonly ManagementTransport _transport;
    private readonly NamespaceScope _scope;

    internal SamlApi(ManagementTransport transport, NamespaceScope scope)
    {
        _transport = transport;
        _scope = scope;
    }

    /// <summary>
    /// Returns a handle addressing <paramref name="tenantId"/> instead of the client's tenant.
    /// </summary>
    /// <remarks>
    /// <para>
    /// A NEW handle: this one is unchanged (&#167;27.4 rule 3).
    /// </para>
    /// </remarks>
    /// <param name="tenantId">the tenant to address.</param>
    /// <returns>a SamlApi scoped to that tenant</returns>
    public SamlApi ForTenant(Guid tenantId) =>
        new(_transport, _scope with { TenantId = tenantId });

    /// <summary>
    /// The tenant's IdP as an SP will meet it, and whether it answers yet: readiness is visible
    /// only here, never on the unauthenticated metadata route (T-368).
    /// </summary>
    /// <remarks>
    /// <para>
    /// Issues <c>GET /api/v1/tenants/{tenant_id}/saml/idp</c>.
    /// </para>
    /// </remarks>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<SamlIdpInfo> GetIdpAsync(CancellationToken cancellationToken = default)
    {
        Guid tenantId = ManagementSupport.ResolveTenant(_transport, _scope, "saml.get_idp");
        string path = $"/api/v1/tenants/{tenantId}/saml/idp";
        JsonElement? node = await _transport.SendAsync(
            "saml.get_idp",
            HttpMethod.Get,
            "/api/v1/tenants/{tenant_id}/saml/idp",
            path,
            null,
            null,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.Decode<SamlIdpInfo>("saml.get_idp", node);
    }

    /// <summary>
    /// Issues <c>GET /api/v1/tenants/{tenant_id}/saml/service-providers</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Paginated: Total on the returned page is the size of the WHOLE set, not of this page
    /// (&#167;27.4 rule 4). Use ListServiceProvidersAllAsync(...) to walk every page.
    /// </para>
    /// </remarks>
    /// <param name="page">where to start and how many to ask for, or <c>null</c> for the
    ///     server's default.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the page of results</returns>
    public async Task<Page<SamlServiceProvider>> ListServiceProvidersAsync(PageRequest? page = null, CancellationToken cancellationToken = default)
    {
        Guid tenantId = ManagementSupport.ResolveTenant(_transport, _scope, "saml.list_service_providers");
        string path = $"/api/v1/tenants/{tenantId}/saml/service-providers";
        Dictionary<string, string?> query = ManagementSupport.PageQuery(null, page);
        JsonElement? node = await _transport.SendAsync(
            "saml.list_service_providers",
            HttpMethod.Get,
            "/api/v1/tenants/{tenant_id}/saml/service-providers",
            path,
            query,
            null,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.DecodePage<SamlServiceProvider>("saml.list_service_providers", node);
    }

    /// <summary>
    /// Walks ListServiceProvidersAsync to exhaustion and returns every item (&#167;27.4 rule
    /// 4).
    /// </summary>
    /// <remarks>
    /// <para>
    /// Stops on an empty page even when the server's Total disagrees, so a misreporting server
    /// costs one wasted request rather than an unbounded loop.
    /// </para>
    /// </remarks>
    /// <param name="start">the first window to request, or <c>null</c> for the server's
    ///     default.</param>
    /// <param name="cancellationToken">cancels the walk.</param>
    /// <returns>every item, in the server's order</returns>
    public Task<IReadOnlyList<SamlServiceProvider>> ListServiceProvidersAllAsync(PageRequest? start = null, CancellationToken cancellationToken = default) =>
        ManagementSupport.CollectPagesAsync(start, window =>
            ListServiceProvidersAsync(page: window, cancellationToken: cancellationToken));

    /// <summary>
    /// Issues <c>POST /api/v1/tenants/{tenant_id}/saml/service-providers</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <c>sp_signing_cert_pem</c> must be RSA (2048 bits or more) or ECDSA on P-256, P-384 or
    /// P-521; an <b>ECDSA certificate verifies HTTP-POST requests only</b> &#8212; the
    /// HTTP-Redirect binding is RSA-only (&#167;29.3 rule 2). <c>encrypt_assertions: true</c>
    /// is refused while encryption is unimplemented. <c>entity_id</c> is unique per tenant
    /// (<c>409</c>) and immutable once created.
    /// </para>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="body">the request body.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<SamlServiceProvider> CreateServiceProviderAsync(SamlServiceProviderInput body, CancellationToken cancellationToken = default)
    {
        Guid tenantId = ManagementSupport.ResolveTenant(_transport, _scope, "saml.create_service_provider");
        string path = $"/api/v1/tenants/{tenantId}/saml/service-providers";
        string payload = ManagementSupport.EncodeBody("saml.create_service_provider", body);
        JsonElement? node = await _transport.SendAsync(
            "saml.create_service_provider",
            HttpMethod.Post,
            "/api/v1/tenants/{tenant_id}/saml/service-providers",
            path,
            null,
            payload,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.Decode<SamlServiceProvider>("saml.create_service_provider", node);
    }

    /// <summary>
    /// Issues <c>GET /api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}</c>.
    /// </summary>
    /// <param name="spId">the sp id to address.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<SamlServiceProvider> GetServiceProviderAsync(Guid spId, CancellationToken cancellationToken = default)
    {
        Guid tenantId = ManagementSupport.ResolveTenant(_transport, _scope, "saml.get_service_provider");
        string path = $"/api/v1/tenants/{tenantId}/saml/service-providers/{spId}";
        JsonElement? node = await _transport.SendAsync(
            "saml.get_service_provider",
            HttpMethod.Get,
            "/api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}",
            path,
            null,
            null,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.Decode<SamlServiceProvider>("saml.get_service_provider", node);
    }

    /// <summary>
    /// Issues <c>PUT /api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// A REPLACEMENT, not a patch: what the body does not carry is not preserved (a member left
    /// unset is omitted from the wire, not sent as null), so read the current value first and
    /// carry over the parts you mean to keep (&#167;27.4 rule 5).
    /// </para>
    /// <para>
    /// An omitted member takes its <b>default</b>, not its stored value: <c>enabled</c> and
    /// <c>sign_responses</c> default to <c>true</c>, <c>name_id_format</c> to
    /// <c>persistent</c>, the other flags to <c>false</c>, certificates and <c>slo_url</c> /
    /// <c>slo_binding</c> to null, the lists to empty (&#167;29.2). Start from
    /// <c>GetServiceProviderAsync</c> (<c>ManagementReplacements.ToInput</c> turns its result
    /// into this body). <c>entity_id</c> is immutable: changing it is <c>400</c> &#8212;
    /// register a new service provider instead (&#167;29.3 rule 3). An ECDSA
    /// <c>sp_signing_cert_pem</c> verifies HTTP-POST requests only; HTTP-Redirect is RSA-only.
    /// </para>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="spId">the sp id to address.</param>
    /// <param name="body">the request body.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<SamlServiceProvider> UpdateServiceProviderAsync(Guid spId, SamlServiceProviderInput body, CancellationToken cancellationToken = default)
    {
        Guid tenantId = ManagementSupport.ResolveTenant(_transport, _scope, "saml.update_service_provider");
        string path = $"/api/v1/tenants/{tenantId}/saml/service-providers/{spId}";
        string payload = ManagementSupport.EncodeBody("saml.update_service_provider", body);
        JsonElement? node = await _transport.SendAsync(
            "saml.update_service_provider",
            HttpMethod.Put,
            "/api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}",
            path,
            null,
            payload,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.Decode<SamlServiceProvider>("saml.update_service_provider", node);
    }

    /// <summary>
    /// Removes the registration and what the datastore holds for it, in one transaction. Ends
    /// no session: users already signed in to the SP stay signed in there until their SP
    /// session ends.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Issues <c>DELETE /api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}</c>.
    /// </para>
    /// <para>
    /// Ends no session: users already signed in to the SP stay signed in there until their SP
    /// session ends (&#167;29.3 rule 5).
    /// </para>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="spId">the sp id to address.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>a task that completes when the server has answered</returns>
    public async Task DeleteServiceProviderAsync(Guid spId, CancellationToken cancellationToken = default)
    {
        Guid tenantId = ManagementSupport.ResolveTenant(_transport, _scope, "saml.delete_service_provider");
        string path = $"/api/v1/tenants/{tenantId}/saml/service-providers/{spId}";
        await _transport.SendAsync(
            "saml.delete_service_provider",
            HttpMethod.Delete,
            "/api/v1/tenants/{tenant_id}/saml/service-providers/{sp_id}",
            path,
            null,
            null,
            cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// **A parse to a draft, never a write.** Takes exactly one of <c>metadata_xml</c> and
    /// <c>metadata_url</c> and returns what a registration of that SP could look like, the
    /// fingerprints of the certificates it carries and warnings. A URL is fetched once, through
    /// the SSRF guard (<c>https</c> only; loopback, private, link-local and cloud-metadata
    /// addresses refused; every redirect hop checked); a document is refused if it holds a DTD
    /// or entity declaration, is not UTF-8, is over 512 KiB, or is not exactly one
    /// <c>EntityDescriptor</c> with one SAML 2.0 <c>SPSSODescriptor</c>. Every refusal is a
    /// generic message that never carries the document, a status line or an address. The
    /// document's own signature is not evaluated.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Issues <c>POST /api/v1/tenants/{tenant_id}/saml/parse-sp-metadata</c>.
    /// </para>
    /// <para>
    /// <b>Parses and stores nothing</b> (&#167;29.3 rule 6): the result is a draft to review
    /// and pass to <c>CreateServiceProviderAsync</c>. Exactly one of <c>metadata_xml</c> and
    /// <c>metadata_url</c> must be set (build the body with <c>ParseSamlSpMetadata.FromUrl</c>
    /// or <c>ParseSamlSpMetadata.FromXml</c>); both or neither is refused locally with a
    /// <c>ValidationError</c>, before any request. The metadata's own signature is not
    /// evaluated. <c>503</c> in a server built without SAML.
    /// </para>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="body">the request body.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<SamlSpMetadataDraft> ParseSpMetadataAsync(ParseSamlSpMetadata body, CancellationToken cancellationToken = default)
    {
        Guid tenantId = ManagementSupport.ResolveTenant(_transport, _scope, "saml.parse_sp_metadata");
        string path = $"/api/v1/tenants/{tenantId}/saml/parse-sp-metadata";
        ManagementChecks.ParseSpMetadataExactlyOne(body);
        string payload = ManagementSupport.EncodeBody("saml.parse_sp_metadata", body);
        JsonElement? node = await _transport.SendAsync(
            "saml.parse_sp_metadata",
            HttpMethod.Post,
            "/api/v1/tenants/{tenant_id}/saml/parse-sp-metadata",
            path,
            null,
            payload,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.Decode<SamlSpMetadataDraft>("saml.parse_sp_metadata", node);
    }

    /// <summary>
    /// Issues <c>GET /api/v1/tenants/{tenant_id}/saml/idp-credentials</c>.
    /// </summary>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<IReadOnlyList<SamlIdpCredential>> ListIdpCredentialsAsync(CancellationToken cancellationToken = default)
    {
        Guid tenantId = ManagementSupport.ResolveTenant(_transport, _scope, "saml.list_idp_credentials");
        string path = $"/api/v1/tenants/{tenantId}/saml/idp-credentials";
        JsonElement? node = await _transport.SendAsync(
            "saml.list_idp_credentials",
            HttpMethod.Get,
            "/api/v1/tenants/{tenant_id}/saml/idp-credentials",
            path,
            null,
            null,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.DecodeList<SamlIdpCredential>("saml.list_idp_credentials", node);
    }

    /// <summary>
    /// Generates an RSA-4096 key and a leaf under <c>issuer_ca_id</c> into an **empty** slot.
    /// Takes seconds. The key is sealed at rest and never returned.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Issues <c>POST /api/v1/tenants/{tenant_id}/saml/idp-credentials</c>.
    /// </para>
    /// <para>
    /// Generates an RSA-4096 key on the server, which takes seconds; the key is never returned.
    /// An occupied slot is <c>409</c> (&#167;29.3 rule 7).
    /// </para>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="body">the request body.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<SamlIdpCredential> IssueIdpCredentialAsync(IssueSamlIdpCredential body, CancellationToken cancellationToken = default)
    {
        Guid tenantId = ManagementSupport.ResolveTenant(_transport, _scope, "saml.issue_idp_credential");
        string path = $"/api/v1/tenants/{tenantId}/saml/idp-credentials";
        string payload = ManagementSupport.EncodeBody("saml.issue_idp_credential", body);
        JsonElement? node = await _transport.SendAsync(
            "saml.issue_idp_credential",
            HttpMethod.Post,
            "/api/v1/tenants/{tenant_id}/saml/idp-credentials",
            path,
            null,
            payload,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.Decode<SamlIdpCredential>("saml.issue_idp_credential", node);
    }

    /// <summary>
    /// In **one transaction**, retires the <c>active</c> credential (its key destroyed) and
    /// makes the <c>next</c> one <c>active</c>. The id must be the tenant's current <c>next</c>
    /// credential and inside its validity window.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Issues <c>POST
    /// /api/v1/tenants/{tenant_id}/saml/idp-credentials/{credential_id}/promote</c>.
    /// </para>
    /// <para>
    /// <c>credential_id</c> must be the tenant's current <c>next</c> credential; in one
    /// transaction the old <c>active</c> is retired &#8212; its key destroyed &#8212; and
    /// <c>next</c> becomes <c>active</c> (&#167;29.3 rule 7).
    /// </para>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="credentialId">the credential id to address.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<SamlIdpCredentialPromotion> PromoteIdpCredentialAsync(Guid credentialId, CancellationToken cancellationToken = default)
    {
        Guid tenantId = ManagementSupport.ResolveTenant(_transport, _scope, "saml.promote_idp_credential");
        string path = $"/api/v1/tenants/{tenantId}/saml/idp-credentials/{credentialId}/promote";
        JsonElement? node = await _transport.SendAsync(
            "saml.promote_idp_credential",
            HttpMethod.Post,
            "/api/v1/tenants/{tenant_id}/saml/idp-credentials/{credential_id}/promote",
            path,
            null,
            null,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.Decode<SamlIdpCredentialPromotion>("saml.promote_idp_credential", node);
    }

    /// <summary>
    /// Retires a <c>next</c> or an <c>active</c> credential and destroys its key. Retiring the
    /// **<c>active</c>** one with no successor stops SAML sign-on for the whole tenant at once
    /// — the incident response to a leaked key. Retiring a retired credential returns it
    /// unchanged and writes no audit row.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Issues <c>POST
    /// /api/v1/tenants/{tenant_id}/saml/idp-credentials/{credential_id}/retire</c>.
    /// </para>
    /// <para>
    /// <b>Retiring the <c>active</c> credential with no successor stops SAML sign-on for the
    /// whole tenant at once</b> (&#167;29.3 rule 7) &#8212; it is the incident response to a
    /// leaked key. The key is destroyed. The safe rotation is: issue into <c>next</c>, wait
    /// until every SP has refreshed the metadata, then promote.
    /// </para>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="credentialId">the credential id to address.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<SamlIdpCredential> RetireIdpCredentialAsync(Guid credentialId, CancellationToken cancellationToken = default)
    {
        Guid tenantId = ManagementSupport.ResolveTenant(_transport, _scope, "saml.retire_idp_credential");
        string path = $"/api/v1/tenants/{tenantId}/saml/idp-credentials/{credentialId}/retire";
        JsonElement? node = await _transport.SendAsync(
            "saml.retire_idp_credential",
            HttpMethod.Post,
            "/api/v1/tenants/{tenant_id}/saml/idp-credentials/{credential_id}/retire",
            path,
            null,
            null,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.Decode<SamlIdpCredential>("saml.retire_idp_credential", node);
    }
}
