// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using Axiam.Sdk.Management.Models;
using System.Net.Http;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management;

/// <summary>
/// The scim_tokens management operations.
/// </summary>
/// <remarks>
/// <para>
/// A view over the client that created it, not a connection: constructing one performs no I/O
/// (&#167;27.2 rule 1), so there is nothing to cache and nothing to close.
/// </para>
/// </remarks>
public sealed class ScimTokensApi
{
    private readonly ManagementTransport _transport;
    private readonly NamespaceScope _scope;

    internal ScimTokensApi(ManagementTransport transport, NamespaceScope scope)
    {
        _transport = transport;
        _scope = scope;
    }

    /// <summary>
    /// Issues <c>GET /api/v1/scim-tokens</c>.
    /// </summary>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<IReadOnlyList<ScimTokenResponse>> ListAsync(CancellationToken cancellationToken = default)
    {
        string path = $"/api/v1/scim-tokens";
        JsonElement? node = await _transport.SendAsync(
            "scim_tokens.list",
            HttpMethod.Get,
            "/api/v1/scim-tokens",
            path,
            null,
            null,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.DecodeList<ScimTokenResponse>("scim_tokens.list", node);
    }

    /// <summary>
    /// Issues <c>POST /api/v1/scim-tokens</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="body">the request body.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<CreateScimTokenResponse> CreateAsync(CreateScimTokenRequest body, CancellationToken cancellationToken = default)
    {
        string path = $"/api/v1/scim-tokens";
        string payload = ManagementSupport.EncodeBody("scim_tokens.create", body);
        JsonElement? node = await _transport.SendAsync(
            "scim_tokens.create",
            HttpMethod.Post,
            "/api/v1/scim-tokens",
            path,
            null,
            payload,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.Decode<CreateScimTokenResponse>("scim_tokens.create", node);
    }

    /// <summary>
    /// Revokes rather than deletes: the row is what lets an operator later answer "was this
    /// credential still live on the day of the incident?", and a deleted row answers nothing.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Issues <c>DELETE /api/v1/scim-tokens/{id}</c>.
    /// </para>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="id">the id to address.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>a task that completes when the server has answered</returns>
    public async Task RevokeAsync(Guid id, CancellationToken cancellationToken = default)
    {
        string path = $"/api/v1/scim-tokens/{id}";
        await _transport.SendAsync(
            "scim_tokens.revoke",
            HttpMethod.Delete,
            "/api/v1/scim-tokens/{id}",
            path,
            null,
            null,
            cancellationToken).ConfigureAwait(false);
    }
}
