// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using Axiam.Sdk.Management.Models;
using System.Net.Http;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management;

/// <summary>
/// The webauthn_policy management operations.
/// </summary>
/// <remarks>
/// <para>
/// A view over the client that created it, not a connection: constructing one performs no I/O
/// (&#167;27.2 rule 1), so there is nothing to cache and nothing to close.
/// </para>
/// </remarks>
public sealed class WebauthnPolicyApi
{
    private readonly ManagementTransport _transport;
    private readonly NamespaceScope _scope;

    internal WebauthnPolicyApi(ManagementTransport transport, NamespaceScope scope)
    {
        _transport = transport;
        _scope = scope;
    }

    /// <summary>
    /// Returns a handle addressing <paramref name="tenantId"/> instead of the client's tenant.
    /// </summary>
    /// <remarks>
    /// <para>
    /// A NEW handle: this one is unchanged (&#167;27.4 rule 3).
    /// </para>
    /// </remarks>
    /// <param name="tenantId">the tenant to address.</param>
    /// <returns>a WebauthnPolicyApi scoped to that tenant</returns>
    public WebauthnPolicyApi ForTenant(Guid tenantId) =>
        new(_transport, _scope with { TenantId = tenantId });

    /// <summary>
    /// Issues <c>GET /api/v1/tenants/{tenant_id}/webauthn/attestation-policy</c>.
    /// </summary>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<PolicyResponse> GetAsync(CancellationToken cancellationToken = default)
    {
        Guid tenantId = ManagementSupport.ResolveTenant(_transport, _scope, "webauthn_policy.get");
        string path = $"/api/v1/tenants/{tenantId}/webauthn/attestation-policy";
        JsonElement? node = await _transport.SendAsync(
            "webauthn_policy.get",
            HttpMethod.Get,
            "/api/v1/tenants/{tenant_id}/webauthn/attestation-policy",
            path,
            null,
            null,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.Decode<PolicyResponse>("webauthn_policy.get", node);
    }

    /// <summary>
    /// Issues <c>PUT /api/v1/tenants/{tenant_id}/webauthn/attestation-policy</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// A REPLACEMENT, not a patch: every field of the body is written, so read the current
    /// value first and carry over the parts you mean to keep (&#167;27.4 rule 5).
    /// </para>
    /// <para>
    /// Not retried: &#167;27.4 rule 8 makes every write on this surface single-shot, including
    /// the ones that look idempotent.
    /// </para>
    /// </remarks>
    /// <param name="body">the request body.</param>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<WebauthnAttestationPolicy> SetAsync(WebauthnAttestationPolicy body, CancellationToken cancellationToken = default)
    {
        Guid tenantId = ManagementSupport.ResolveTenant(_transport, _scope, "webauthn_policy.set");
        string path = $"/api/v1/tenants/{tenantId}/webauthn/attestation-policy";
        string payload = ManagementSupport.EncodeBody("webauthn_policy.set", body);
        JsonElement? node = await _transport.SendAsync(
            "webauthn_policy.set",
            HttpMethod.Put,
            "/api/v1/tenants/{tenant_id}/webauthn/attestation-policy",
            path,
            null,
            payload,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.Decode<WebauthnAttestationPolicy>("webauthn_policy.set", node);
    }

    /// <summary>
    /// Issues <c>GET /api/v1/tenants/{tenant_id}/webauthn/compliance-report</c>.
    /// </summary>
    /// <param name="cancellationToken">cancels the request.</param>
    /// <returns>the server response</returns>
    public async Task<IReadOnlyList<ComplianceReportEntry>> ComplianceReportAsync(CancellationToken cancellationToken = default)
    {
        Guid tenantId = ManagementSupport.ResolveTenant(_transport, _scope, "webauthn_policy.compliance_report");
        string path = $"/api/v1/tenants/{tenantId}/webauthn/compliance-report";
        JsonElement? node = await _transport.SendAsync(
            "webauthn_policy.compliance_report",
            HttpMethod.Get,
            "/api/v1/tenants/{tenant_id}/webauthn/compliance-report",
            path,
            null,
            null,
            cancellationToken).ConfigureAwait(false);
        return ManagementSupport.DecodeList<ComplianceReportEntry>("webauthn_policy.compliance_report", node);
    }
}
