// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// One <c>AssertionConsumerService</c> endpoint of a service provider. The list of these is an
/// **allow-list**, checked the way OAuth2 redirect URIs are: an <c>AuthnRequest</c> naming an
/// ACS URL is honoured only when the URL equals one registered here, byte for byte. No globs,
/// no prefix match.
/// </summary>
public sealed record AcsEndpoint
{
    /// <summary>
    /// The binding the endpoint accepts.
    /// </summary>
    [JsonPropertyName("binding")]
    public required SamlBinding Binding { get; init; }

    /// <summary>
    /// The <c>index</c> an <c>AuthnRequest</c> may use instead of a URL. Unique per SP.
    /// </summary>
    [JsonPropertyName("index")]
    public required int Index { get; init; }

    /// <summary>
    /// Whether this is the SP's default endpoint. At most one is; when none is marked, the
    /// first listed is the default (SAML Metadata §2.4.4.1).
    /// </summary>
    [JsonPropertyName("is_default")]
    public bool? IsDefault { get; init; }

    /// <summary>
    /// The endpoint URL.
    /// </summary>
    [JsonPropertyName("url")]
    public required string Url { get; init; }
}
