// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// The AddServiceAccountMemberRequest schema from the server's OpenAPI document.
/// </summary>
public sealed record AddServiceAccountMemberRequest
{
    /// <summary>
    /// the server's service_account_id field
    /// </summary>
    [JsonPropertyName("service_account_id")]
    public required Guid ServiceAccountId { get; init; }
}
