// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// API-based provider configuration (SendGrid, Postmark, Resend, Brevo). <c>api_key</c> follows
/// the same write-only + omit-preserving contract as [<c>SmtpConfig::password</c>] (D-01/D-02).
/// </summary>
/// <remarks>
/// <para>
/// Every property is optional, so this is a SPARSE body: what you leave unset is left
/// unchanged, and is omitted from the wire request entirely rather than sent as null
/// (&#167;27.4 rule 5). Naming the properties you mean to change is the whole API — there is no
/// builder because C# object initializers already are one, and no way to accidentally send a
/// field you did not name.
/// </para>
/// </remarks>
public sealed record ApiProviderConfig
{
    /// <summary>
    /// Override base URL (useful for testing / self-hosted instances).
    /// </summary>
    [JsonPropertyName("api_url")]
    public string? ApiUrl { get; init; }
}
