// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// The AssignRoleToUserRequest schema from the server's OpenAPI document.
/// </summary>
public sealed record AssignRoleToUserRequest
{
    /// <summary>
    /// Whether the assignment also reaches the descendants of <c>resource_id</c>. Omitted — the
    /// default — or <c>true</c> is today's behaviour: a resource-scoped assignment applies at
    /// its resource and everywhere below it. <c>false</c> applies it at <c>resource_id</c>
    /// only, "here and no further", for allow and deny grants alike. Refused with 400 when
    /// <c>false</c> is sent with no <c>resource_id</c> (a tenant-wide assignment has no node to
    /// stop at) or for a role with <c>is_global: true</c> (a global role applies everywhere by
    /// definition). The flag is part of the assignment: to change it, unassign and assign
    /// again.
    /// </summary>
    [JsonPropertyName("inherit")]
    public bool? Inherit { get; init; }

    /// <summary>
    /// the server's resource_id field
    /// </summary>
    [JsonPropertyName("resource_id")]
    public Guid? ResourceId { get; init; }

    /// <summary>
    /// The tenants this assignment reaches. Only meaningful for an assignment made in an
    /// organization's scope, whose global roles otherwise reach every tenant of the
    /// organization; naming tenants here confines the assignment to those and to nothing else,
    /// the organization's own scope included. Omitted — the default — reaches wherever the role
    /// does. Refused with 400 outside an organization scope, when empty, and when it names a
    /// tenant of another organization or the organization's own scope tenant.
    /// </summary>
    [JsonPropertyName("tenant_scope")]
    public IReadOnlyList<Guid>? TenantScope
    {
        get => _tenantScope;
        init => _tenantScope = value is { Count: 0 } ? null : value;
    }

    private readonly IReadOnlyList<Guid>? _tenantScope;

    /// <summary>
    /// the server's user_id field
    /// </summary>
    [JsonPropertyName("user_id")]
    public required Guid UserId { get; init; }
}
