// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using Axiam.Sdk.Management;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// What attestation conveyance a registration ceremony requests, and whether the policy is
/// enforced at all. <c>None</c> is the default and reproduces today's behavior byte-for-byte:
/// <c>evaluate</c> allows every registration unconditionally, with no MDS lookup (D8 step 1).
/// </summary>
/// <remarks>
/// <para>
/// Each member carries the spelling the server uses on the wire via WireName, so the C# name
/// can follow C# conventions without changing what is sent. An unknown value throws rather than
/// silently becoming the zero member.
/// </para>
/// </remarks>
[JsonConverter(typeof(WireEnumConverter<AttestationMode>))]
public enum AttestationMode
{
    /// <summary>The server's <c>none</c> value.</summary>
    [WireName("none")]
    None,

    /// <summary>The server's <c>indirect</c> value.</summary>
    [WireName("indirect")]
    Indirect,

    /// <summary>The server's <c>direct_required</c> value.</summary>
    [WireName("direct_required")]
    DirectRequired,
}
