// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// One entry of an SP's attribute mapping table.
/// </summary>
public sealed record AttributeMapping
{
    /// <summary>
    /// The <c>NameFormat</c>, one of [<c>ATTRIBUTE_NAME_FORMATS</c>]. <c>None</c> leaves the
    /// attribute unqualified (<c>unspecified</c>).
    /// </summary>
    [JsonPropertyName("name_format")]
    public string? NameFormat { get; init; }

    /// <summary>
    /// The <c>Name</c> of the emitted <c>&lt;saml:Attribute&gt;</c>. Unique within one SP,
    /// compared exactly (SAML attribute names are case-sensitive).
    /// </summary>
    [JsonPropertyName("saml_name")]
    public required string SamlName { get; init; }

    /// <summary>
    /// Where the value comes from.
    /// </summary>
    [JsonPropertyName("source")]
    public required AttributeSource Source { get; init; }
}
