// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// Request to bind a certificate to a service account.
/// </summary>
public sealed record BindCertificate
{
    /// <summary>
    /// the server's certificate_id field
    /// </summary>
    [JsonPropertyName("certificate_id")]
    public required Guid CertificateId { get; init; }
}
