// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using Axiam.Sdk.Management;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// FIDO certification level, as recorded in an MDS <c>statusReports</c> entry's
/// <c>FIDO_CERTIFIED*</c> status. Variant order is significant: <c>derive(PartialOrd, Ord)</c>
/// gives <c>L1 &lt; L1Plus &lt; L2 &lt; L2Plus &lt; L3 &lt; L3Plus</c>, which
/// <c>WebauthnAttestationPolicy::evaluate</c> (D8 step 9) relies on directly for the
/// <c>min_certification</c> boundary check (<c>entry_level &gt;= policy_min</c>).
/// </summary>
/// <remarks>
/// <para>
/// Each member carries the spelling the server uses on the wire via WireName, so the C# name
/// can follow C# conventions without changing what is sent. An unknown value throws rather than
/// silently becoming the zero member.
/// </para>
/// </remarks>
[JsonConverter(typeof(WireEnumConverter<CertificationLevel>))]
public enum CertificationLevel
{
    /// <summary>The server's <c>L1</c> value.</summary>
    [WireName("L1")]
    L1,

    /// <summary>The server's <c>L1Plus</c> value.</summary>
    [WireName("L1Plus")]
    L1Plus,

    /// <summary>The server's <c>L2</c> value.</summary>
    [WireName("L2")]
    L2,

    /// <summary>The server's <c>L2Plus</c> value.</summary>
    [WireName("L2Plus")]
    L2Plus,

    /// <summary>The server's <c>L3</c> value.</summary>
    [WireName("L3")]
    L3,

    /// <summary>The server's <c>L3Plus</c> value.</summary>
    [WireName("L3Plus")]
    L3Plus,
}
