// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using Axiam.Sdk.Management;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// The JWS algorithm a CIBA client signs its authentication requests with (CIBA Core §4
/// <c>backchannel_authentication_request_signing_alg</c>, §7.1.1). Exactly the three algorithms
/// AXIAM verifies on any client-signed JWT (<c>axiam_oauth2::jose::PERMITTED_ALGORITHMS</c>):
/// FAPI 2.0 §5.3.1.1's list. A registration naming anything else — <c>RS256</c>, <c>HS256</c>,
/// <c>none</c> — is refused rather than stored, so no row can hold an algorithm the verifier
/// would not honour (D-61).
/// </summary>
/// <remarks>
/// <para>
/// Each member carries the spelling the server uses on the wire via WireName, so the C# name
/// can follow C# conventions without changing what is sent.
/// </para>
/// <para>
/// An <b>open</b> enum. A value this SDK’s copy of the spec does not list decodes to
/// <c>CibaRequestSigningAlg.Unknown</c> rather than failing the response it arrived in
/// (&#167;27.11 rule 1) — a closed enum turns the next value the server adds into a parse error
/// on the whole list, taking down every record on the page over one field of one of them. A
/// <c>switch</c> over these members needs an <c>Unknown</c> arm.
/// </para>
/// </remarks>
[JsonConverter(typeof(WireEnumConverter<CibaRequestSigningAlg>))]
public enum CibaRequestSigningAlg
{
    /// <summary>The server's <c>PS256</c> value.</summary>
    [WireName("PS256")]
    PS256,

    /// <summary>The server's <c>ES256</c> value.</summary>
    [WireName("ES256")]
    ES256,

    /// <summary>The server's <c>EdDSA</c> value.</summary>
    [WireName("EdDSA")]
    EdDSA,

    /// <summary>
    /// A value this SDK’s copy of the spec does not list.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Its wire spelling is the empty string, which no server value is: carrying an
    /// unrecognised value back into an update is refused by the server rather than silently
    /// written as a spelling it never used. Fifteen of these enums appear in request bodies,
    /// which is what makes that distinction worth having.
    /// </para>
    /// <para>
    /// It is deliberately <b>not</b> the zero member — defaulting to it would make “the server
    /// said nothing” and “the server said something new” the same value.
    /// </para>
    /// </remarks>
    [WireName("")]
    Unknown,
}
