// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using Axiam.Sdk.Management;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// How a client proves its identity at the token endpoint (RFC 8705 §2, OIDC Core §9 naming).
/// Only the methods AXIAM actually implements are representable. There is deliberately no
/// <c>none</c> variant: every AXIAM client is confidential today (see
/// <c>handle_authorization_code</c>), and adding a public-client value here before the rest of
/// the server understands one would let an operator register a client whose authentication is
/// silently skipped.
/// </summary>
/// <remarks>
/// <para>
/// Each member carries the spelling the server uses on the wire via WireName, so the C# name
/// can follow C# conventions without changing what is sent. An unknown value throws rather than
/// silently becoming the zero member.
/// </para>
/// </remarks>
[JsonConverter(typeof(WireEnumConverter<ClientAuthMethod>))]
public enum ClientAuthMethod
{
    /// <summary>The server's <c>client_secret_post</c> value.</summary>
    [WireName("client_secret_post")]
    ClientSecretPost,

    /// <summary>The server's <c>tls_client_auth</c> value.</summary>
    [WireName("tls_client_auth")]
    TlsClientAuth,

    /// <summary>The server's <c>self_signed_tls_client_auth</c> value.</summary>
    [WireName("self_signed_tls_client_auth")]
    SelfSignedTlsClientAuth,

    /// <summary>The server's <c>private_key_jwt</c> value.</summary>
    [WireName("private_key_jwt")]
    PrivateKeyJwt,
}
