// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// The CreateResourceRequest schema from the server's OpenAPI document.
/// </summary>
public sealed record CreateResourceRequest
{
    /// <summary>
    /// the server's metadata field
    /// </summary>
    [JsonPropertyName("metadata")]
    public JsonElement? Metadata { get; init; }

    /// <summary>
    /// the server's name field
    /// </summary>
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    /// <summary>
    /// the server's parent_id field
    /// </summary>
    [JsonPropertyName("parent_id")]
    public Guid? ParentId { get; init; }

    /// <summary>
    /// the server's resource_type field
    /// </summary>
    [JsonPropertyName("resource_type")]
    public required string ResourceType { get; init; }
}
