// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// The CreateCertificateRequest schema from the server's OpenAPI document.
/// </summary>
public sealed record CreateCertificateRequest
{
    /// <summary>
    /// the server's cert_type field
    /// </summary>
    [JsonPropertyName("cert_type")]
    public required CertificateType CertType { get; init; }

    /// <summary>
    /// the server's issuer_ca_id field
    /// </summary>
    [JsonPropertyName("issuer_ca_id")]
    public required Guid IssuerCaId { get; init; }

    /// <summary>
    /// the server's key_algorithm field
    /// </summary>
    [JsonPropertyName("key_algorithm")]
    public required KeyAlgorithm KeyAlgorithm { get; init; }

    /// <summary>
    /// the server's metadata field
    /// </summary>
    [JsonPropertyName("metadata")]
    public JsonElement? Metadata { get; init; }

    /// <summary>
    /// the server's subject field
    /// </summary>
    [JsonPropertyName("subject")]
    public required string Subject { get; init; }

    /// <summary>
    /// Validity duration in days.
    /// </summary>
    [JsonPropertyName("validity_days")]
    public required int ValidityDays { get; init; }
}
