// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// The CreatePermissionRequest schema from the server's OpenAPI document.
/// </summary>
public sealed record CreatePermissionRequest
{
    /// <summary>
    /// the server's action field
    /// </summary>
    [JsonPropertyName("action")]
    public required string Action { get; init; }

    /// <summary>
    /// the server's description field
    /// </summary>
    [JsonPropertyName("description")]
    public required string Description { get; init; }
}
