// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// Request body for tenant creation (organization_id comes from the URL path).
/// </summary>
public sealed record CreateTenantRequest
{
    /// <summary>
    /// the server's metadata field
    /// </summary>
    [JsonPropertyName("metadata")]
    public JsonElement? Metadata { get; init; }

    /// <summary>
    /// the server's name field
    /// </summary>
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    /// <summary>
    /// the server's slug field
    /// </summary>
    [JsonPropertyName("slug")]
    public required string Slug { get; init; }
}
