// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using Axiam.Sdk.Core;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// The CreateFederationConfigRequest schema from the server's OpenAPI document.
/// </summary>
public sealed record CreateFederationConfigRequest
{
    /// <summary>
    /// Accepted JWT signing algorithms (OIDC) or signature algorithms (SAML). Defaults to
    /// <c>["RS256"]</c> when not provided (CQ-B40/REQ-14 AC-5).
    /// </summary>
    [JsonPropertyName("allowed_algorithms")]
    public IReadOnlyList<string>? AllowedAlgorithms { get; init; }

    /// <summary>
    /// Maps external IdP attributes to AXIAM user fields.
    /// </summary>
    [JsonPropertyName("attribute_map")]
    public JsonElement? AttributeMap { get; init; }

    /// <summary>
    /// OAuth2 client ID registered with the external IdP.
    /// </summary>
    [JsonPropertyName("client_id")]
    public required string ClientId { get; init; }

    /// <summary>
    /// OAuth2 client secret registered with the external IdP. -- SECRET: redacted from ToString
    /// and from every rendering except the one request body it is sent in.
    /// </summary>
    [JsonPropertyName("client_secret")]
    public required Sensitive<string> ClientSecret { get; init; }

    /// <summary>
    /// PEM-encoded X.509 certificate for verifying SAML assertions or OIDC signatures
    /// (CQ-B40/REQ-14 AC-5). Required for SAML configs.
    /// </summary>
    [JsonPropertyName("idp_signing_cert_pem")]
    public string? IdpSigningCertPem { get; init; }

    /// <summary>
    /// OIDC discovery URL or SAML metadata URL.
    /// </summary>
    [JsonPropertyName("metadata_url")]
    public string? MetadataUrl { get; init; }

    /// <summary>
    /// Federation protocol: "OidcConnect" or "Saml".
    /// </summary>
    [JsonPropertyName("protocol")]
    public required string Protocol { get; init; }

    /// <summary>
    /// Display name for the identity provider (e.g., "Google", "Okta").
    /// </summary>
    [JsonPropertyName("provider")]
    public required string Provider { get; init; }

    /// <summary>
    /// the server's token_exchange field
    /// </summary>
    [JsonPropertyName("token_exchange")]
    public TokenExchangeTrustRequest? TokenExchange { get; init; }
}
