// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// The CreatePgpKeyRequest schema from the server's OpenAPI document.
/// </summary>
public sealed record CreatePgpKeyRequest
{
    /// <summary>
    /// the server's algorithm field
    /// </summary>
    [JsonPropertyName("algorithm")]
    public required PgpKeyAlgorithm Algorithm { get; init; }

    /// <summary>
    /// Email for the OpenPGP User ID.
    /// </summary>
    [JsonPropertyName("email")]
    public required string Email { get; init; }

    /// <summary>
    /// the server's name field
    /// </summary>
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    /// <summary>
    /// the server's purpose field
    /// </summary>
    [JsonPropertyName("purpose")]
    public required PgpKeyPurpose Purpose { get; init; }
}
