// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// The CreateOAuth2ClientRequest schema from the server's OpenAPI document.
/// </summary>
public sealed record CreateOAuth2ClientRequest
{
    /// <summary>
    /// B5 — where OIDC back-channel logout tokens are delivered. Omit for a client that does
    /// not participate.
    /// </summary>
    [JsonPropertyName("backchannel_logout_uri")]
    public string? BackchannelLogoutUri { get; init; }

    /// <summary>
    /// RFC 9449 §5.2 — issue DPoP-bound (sender-constrained) access tokens to this client.
    /// Independent of both the authentication method and
    /// <c>tls_client_certificate_bound_access_tokens</c>; a client may ask for both
    /// constraints, and a token carrying both must satisfy both.
    /// </summary>
    [JsonPropertyName("dpop_bound_access_tokens")]
    public bool? DpopBoundAccessTokens { get; init; }

    /// <summary>
    /// RFC 9449 §8 — require this client's DPoP proofs to carry a server-issued nonce. **Not
    /// implemented in this build (SEC-097).** <c>true</c> is refused with <c>400</c>; only
    /// <c>false</c> (the default) is accepted. Nothing reads the stored value, so accepting
    /// <c>true</c> would persist and echo back a security switch that does nothing. DPoP proofs
    /// are made single-use at the token endpoint by <c>jti</c> replay detection instead — see
    /// <c>docs/security-profiles.md</c>.
    /// </summary>
    [JsonPropertyName("dpop_require_nonce")]
    public bool? DpopRequireNonce { get; init; }

    /// <summary>
    /// Grant types this client is authorized to use.
    /// </summary>
    [JsonPropertyName("grant_types")]
    public required IReadOnlyList<string> GrantTypes { get; init; }

    /// <summary>
    /// RFC 7591 §2 — the client's public key set, inline, for <c>private_key_jwt</c>. Exactly
    /// one of <c>jwks</c> and <c>jwks_uri</c> may be set.
    /// </summary>
    [JsonPropertyName("jwks")]
    public string? Jwks { get; init; }

    /// <summary>
    /// RFC 7591 §2 — where the client publishes its public key set. Must be an absolute
    /// <c>https</c> URL, and is fetched through the SSRF-guarded JWKS cache, which refuses
    /// private and loopback addresses.
    /// </summary>
    [JsonPropertyName("jwks_uri")]
    public string? JwksUri { get; init; }

    /// <summary>
    /// Human-readable name for the client.
    /// </summary>
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    /// <summary>
    /// B5 — allow-list for RP-initiated logout's <c>post_logout_redirect_uri</c>. Separate from
    /// <c>redirect_uris</c> on purpose: that list receives authorization codes, this one
    /// receives a browser after logout.
    /// </summary>
    [JsonPropertyName("post_logout_redirect_uris")]
    public IReadOnlyList<string>? PostLogoutRedirectUris { get; init; }

    /// <summary>
    /// X5.1 — the security posture this client is registered under. <c>"standard"</c> (the
    /// default) is every AXIAM client that has ever existed. <c>"fapi2"</c> turns on the whole
    /// FAPI 2.0 constraint bundle at once, and the registration is refused unless it also sets
    /// <c>require_par</c>, a strong <c>token_endpoint_auth_method</c> (either mTLS method or
    /// <c>private_key_jwt</c>), and at least one sender-constraining mechanism
    /// (<c>tls_client_certificate_bound_access_tokens</c> or <c>dpop_bound_access_tokens</c>).
    /// See the FAPI operator guide.
    /// </summary>
    [JsonPropertyName("profile")]
    public ClientProfile? Profile { get; init; }

    /// <summary>
    /// Allowed redirect URIs (must be HTTPS, except localhost for dev). SEC-089: this list
    /// doubles as the token-exchange audience allow-list — adding a URI here also authorises it
    /// as a token audience for this client, so review additions on exchange-capable clients
    /// with that in mind (see <c>docs/api/token-exchange.md#audience</c>).
    /// </summary>
    [JsonPropertyName("redirect_uris")]
    public required IReadOnlyList<string> RedirectUris { get; init; }

    /// <summary>
    /// B5 — require this client to push its authorization parameters to <c>/oauth2/par</c> (RFC
    /// 9126) rather than sending them through the browser.
    /// </summary>
    [JsonPropertyName("require_par")]
    public bool? RequirePar { get; init; }

    /// <summary>
    /// Scopes the client may request.
    /// </summary>
    [JsonPropertyName("scopes")]
    public required IReadOnlyList<string> Scopes { get; init; }

    /// <summary>
    /// Accepted certificate thumbprints for <c>self_signed_tls_client_auth</c>, as
    /// base64url-unpadded SHA-256 digests of the DER certificate (the same <c>x5t#S256</c>
    /// encoding as the <c>cnf</c> claim). More than one permits an overlapping rotation.
    /// </summary>
    [JsonPropertyName("self_signed_tls_client_auth_thumbprints")]
    public IReadOnlyList<string>? SelfSignedTlsClientAuthThumbprints { get; init; }

    /// <summary>
    /// RFC 8705 §2.1.2 — expected <c>dNSName</c> SAN.
    /// </summary>
    [JsonPropertyName("tls_client_auth_san_dns")]
    public string? TlsClientAuthSanDns { get; init; }

    /// <summary>
    /// RFC 8705 §2.1.2 — expected <c>uniformResourceIdentifier</c> SAN.
    /// </summary>
    [JsonPropertyName("tls_client_auth_san_uri")]
    public string? TlsClientAuthSanUri { get; init; }

    /// <summary>
    /// RFC 8705 §2.1.2 — expected certificate subject DN, RFC 4514 form. Exactly one of the
    /// three <c>tls_client_auth_*</c> parameters may be set.
    /// </summary>
    [JsonPropertyName("tls_client_auth_subject_dn")]
    public string? TlsClientAuthSubjectDn { get; init; }

    /// <summary>
    /// RFC 8705 §3.4 — issue certificate-bound (sender-constrained) access tokens to this
    /// client. Independent of the authentication method.
    /// </summary>
    [JsonPropertyName("tls_client_certificate_bound_access_tokens")]
    public bool? TlsClientCertificateBoundAccessTokens { get; init; }

    /// <summary>
    /// X5.1 — how this client authenticates at the token endpoint (RFC 8705 §2). Defaults to
    /// <c>client_secret_post</c>.
    /// </summary>
    [JsonPropertyName("token_endpoint_auth_method")]
    public ClientAuthMethod? TokenEndpointAuthMethod { get; init; }
}
