// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// The one response that carries the handle.
/// </summary>
public sealed record CreateRegistrationTokenResponse
{
    /// <summary>
    /// The plaintext handle, shown exactly once. Presented by the registering client as
    /// <c>Authorization: Bearer &lt;this&gt;</c>.
    /// </summary>
    [JsonPropertyName("initial_access_token")]
    public required string InitialAccessToken { get; init; }

    /// <summary>
    /// The token's metadata.
    /// </summary>
    [JsonPropertyName("token")]
    public required RegistrationTokenResponse Token { get; init; }
}
