// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// The CreateNotificationRuleRequest schema from the server's OpenAPI document.
/// </summary>
public sealed record CreateNotificationRuleRequest
{
    /// <summary>
    /// Description of what this rule monitors.
    /// </summary>
    [JsonPropertyName("description")]
    public required string Description { get; init; }

    /// <summary>
    /// Event types that trigger this rule.
    /// </summary>
    [JsonPropertyName("events")]
    public required IReadOnlyList<NotificationEventType> Events { get; init; }

    /// <summary>
    /// Human-readable name for the rule.
    /// </summary>
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    /// <summary>
    /// Email addresses to notify.
    /// </summary>
    [JsonPropertyName("recipient_emails")]
    public required IReadOnlyList<string> RecipientEmails { get; init; }

    /// <summary>
    /// Minutes in which one event type mails each recipient at most once: the first event of a
    /// window is mailed, the rest are counted and the next mail says how many were not sent
    /// (#551). 1 … 1440; 15 when omitted.
    /// </summary>
    [JsonPropertyName("window_minutes")]
    public int? WindowMinutes { get; init; }
}
