// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// Body of <c>POST .../tenants/{tenant_id}/signing-cas</c>.
/// </summary>
public sealed record CreateIntermediateCaRequest
{
    /// <summary>
    /// the server's key_algorithm field
    /// </summary>
    [JsonPropertyName("key_algorithm")]
    public required KeyAlgorithm KeyAlgorithm { get; init; }

    /// <summary>
    /// The organization CA that signs it.
    /// </summary>
    [JsonPropertyName("parent_ca_id")]
    public required Guid ParentCaId { get; init; }

    /// <summary>
    /// The signing CA's common name, e.g. <c>ACME R&amp;D Signing CA</c>. A **common name**,
    /// not a distinguished name. A single <c>CN=</c> prefix is accepted and stripped; anything
    /// else containing <c>=</c> is refused with <c>400</c>.
    /// </summary>
    [JsonPropertyName("subject")]
    public required string Subject { get; init; }

    /// <summary>
    /// Validity duration in days, capped to the parent's own expiry.
    /// </summary>
    [JsonPropertyName("validity_days")]
    public required int ValidityDays { get; init; }
}
