// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using Axiam.Sdk.Management;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// Which kind of directory server a configuration points at. It drives **defaults only**: the
/// external-id attribute, the group-membership strategy and the change attribute the sync job
/// reads. Every one of them is still an explicit, editable field of the configuration (or, for
/// the strategy and change attribute, derived from this value at the point of use); nothing
/// about the kind changes what is *allowed*.
/// </summary>
/// <remarks>
/// <para>
/// Each member carries the spelling the server uses on the wire via WireName, so the C# name
/// can follow C# conventions without changing what is sent.
/// </para>
/// <para>
/// An <b>open</b> enum. A value this SDK’s copy of the spec does not list decodes to
/// <c>DirectoryKind.Unknown</c> rather than failing the response it arrived in (&#167;27.11
/// rule 1) — a closed enum turns the next value the server adds into a parse error on the whole
/// list, taking down every record on the page over one field of one of them. A <c>switch</c>
/// over these members needs an <c>Unknown</c> arm.
/// </para>
/// </remarks>
[JsonConverter(typeof(WireEnumConverter<DirectoryKind>))]
public enum DirectoryKind
{
    /// <summary>The server's <c>open_ldap</c> value.</summary>
    [WireName("open_ldap")]
    OpenLdap,

    /// <summary>The server's <c>active_directory</c> value.</summary>
    [WireName("active_directory")]
    ActiveDirectory,

    /// <summary>
    /// A value this SDK’s copy of the spec does not list.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Its wire spelling is the empty string, which no server value is: carrying an
    /// unrecognised value back into an update is refused by the server rather than silently
    /// written as a spelling it never used. Fifteen of these enums appear in request bodies,
    /// which is what makes that distinction worth having.
    /// </para>
    /// <para>
    /// It is deliberately <b>not</b> the zero member — defaulting to it would make “the server
    /// said nothing” and “the server said something new” the same value.
    /// </para>
    /// </remarks>
    [WireName("")]
    Unknown,
}
