// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// What linking did.
/// </summary>
public sealed record DirectoryLinkResult
{
    /// <summary>
    /// <c>User</c>-type certificates revoked.
    /// </summary>
    [JsonPropertyName("certificates_revoked")]
    public required long CertificatesRevoked { get; init; }

    /// <summary>
    /// The entry's <c>entryUUID</c> or <c>objectGUID</c> as text: an identifier, not a secret.
    /// </summary>
    [JsonPropertyName("directory_external_id")]
    public required string DirectoryExternalId { get; init; }

    /// <summary>
    /// The account that was linked.
    /// </summary>
    [JsonPropertyName("user_id")]
    public required Guid UserId { get; init; }

    /// <summary>
    /// <c>true</c> when the account was already linked to that very entry and the call only
    /// re-ran the revocations (an interrupted link completed).
    /// </summary>
    [JsonPropertyName("was_already_linked")]
    public required bool WasAlreadyLinked { get; init; }

    /// <summary>
    /// Passkeys and security keys deleted.
    /// </summary>
    [JsonPropertyName("webauthn_credentials_deleted")]
    public required long WebauthnCredentialsDeleted { get; init; }
}
