// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// Partial tenant overrides for email configuration. <c>None</c> = inherit from org baseline.
/// </summary>
/// <remarks>
/// <para>
/// Every property is optional, so this is a SPARSE body: what you leave unset is left
/// unchanged, and is omitted from the wire request entirely rather than sent as null
/// (&#167;27.4 rule 5). Naming the properties you mean to change is the whole API — there is no
/// builder because C# object initializers already are one, and no way to accidentally send a
/// field you did not name.
/// </para>
/// </remarks>
public sealed record EmailConfigOverride
{
    /// <summary>
    /// the server's enabled field
    /// </summary>
    [JsonPropertyName("enabled")]
    public bool? Enabled { get; init; }

    /// <summary>
    /// the server's from_email field
    /// </summary>
    [JsonPropertyName("from_email")]
    public string? FromEmail { get; init; }

    /// <summary>
    /// the server's from_name field
    /// </summary>
    [JsonPropertyName("from_name")]
    public string? FromName { get; init; }

    /// <summary>
    /// the server's provider field
    /// </summary>
    [JsonPropertyName("provider")]
    public ProviderConfig? Provider { get; init; }

    /// <summary>
    /// <c>Some(None)</c> explicitly clears reply-to; <c>None</c> inherits.
    /// </summary>
    [JsonPropertyName("reply_to")]
    public string? ReplyTo { get; init; }
}
