// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// Result of encrypting data with a PGP public key.
/// </summary>
public sealed record EncryptedExport
{
    /// <summary>
    /// ASCII-armored PGP encrypted data.
    /// </summary>
    [JsonPropertyName("ciphertext_armored")]
    public required string CiphertextArmored { get; init; }

    /// <summary>
    /// the server's recipient_key_id field
    /// </summary>
    [JsonPropertyName("recipient_key_id")]
    public required Guid RecipientKeyId { get; init; }
}
