// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// Request body for encrypting data.
/// </summary>
public sealed record EncryptRequest
{
    /// <summary>
    /// Base64-encoded plaintext to encrypt.
    /// </summary>
    [JsonPropertyName("data_base64")]
    public required string DataBase64 { get; init; }
}
