// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// The FederationLinkResponse schema from the server's OpenAPI document.
/// </summary>
public sealed record FederationLinkResponse
{
    /// <summary>
    /// the server's created_at field
    /// </summary>
    [JsonPropertyName("created_at")]
    public required DateTimeOffset CreatedAt { get; init; }

    /// <summary>
    /// the server's external_email field
    /// </summary>
    [JsonPropertyName("external_email")]
    public string? ExternalEmail { get; init; }

    /// <summary>
    /// the server's external_subject field
    /// </summary>
    [JsonPropertyName("external_subject")]
    public required string ExternalSubject { get; init; }

    /// <summary>
    /// the server's federation_config_id field
    /// </summary>
    [JsonPropertyName("federation_config_id")]
    public required Guid FederationConfigId { get; init; }

    /// <summary>
    /// the server's id field
    /// </summary>
    [JsonPropertyName("id")]
    public required Guid Id { get; init; }

    /// <summary>
    /// the server's tenant_id field
    /// </summary>
    [JsonPropertyName("tenant_id")]
    public required Guid TenantId { get; init; }

    /// <summary>
    /// the server's updated_at field
    /// </summary>
    [JsonPropertyName("updated_at")]
    public required DateTimeOffset UpdatedAt { get; init; }

    /// <summary>
    /// the server's user_id field
    /// </summary>
    [JsonPropertyName("user_id")]
    public required Guid UserId { get; init; }
}
