// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using Axiam.Sdk.Core;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// Response returned when a tenant certificate is generated. Includes the private key PEM,
/// returned **once** and never stored.
/// </summary>
public sealed record GeneratedCertificate
{
    /// <summary>
    /// the server's cert_type field
    /// </summary>
    [JsonPropertyName("cert_type")]
    public required CertificateType CertType { get; init; }

    /// <summary>
    /// The issuing chain, concatenated PEM, nearest issuer first. Present only when the signer
    /// returned one — which is the <c>vault_pki</c> case, where the root's certificate exists
    /// nowhere a client could fetch it from. For a CA AXIAM signed with itself the chain is the
    /// CA certificate, which <c>GET .../ca-certificates/{id}</c> already serves, so the field
    /// is omitted rather than restating it.
    /// </summary>
    [JsonPropertyName("chain_pem")]
    public string? ChainPem { get; init; }

    /// <summary>
    /// the server's created_at field
    /// </summary>
    [JsonPropertyName("created_at")]
    public required DateTimeOffset CreatedAt { get; init; }

    /// <summary>
    /// SHA-256 fingerprint of the certificate.
    /// </summary>
    [JsonPropertyName("fingerprint")]
    public required string Fingerprint { get; init; }

    /// <summary>
    /// the server's id field
    /// </summary>
    [JsonPropertyName("id")]
    public required Guid Id { get; init; }

    /// <summary>
    /// The CA certificate that signed this certificate.
    /// </summary>
    [JsonPropertyName("issuer_ca_id")]
    public required Guid IssuerCaId { get; init; }

    /// <summary>
    /// the server's key_algorithm field
    /// </summary>
    [JsonPropertyName("key_algorithm")]
    public required KeyAlgorithm KeyAlgorithm { get; init; }

    /// <summary>
    /// Arbitrary key-value metadata (e.g., device serial, user ID binding).
    /// </summary>
    [JsonPropertyName("metadata")]
    public required JsonElement Metadata { get; init; }

    /// <summary>
    /// Validity end.
    /// </summary>
    [JsonPropertyName("not_after")]
    public required DateTimeOffset NotAfter { get; init; }

    /// <summary>
    /// Validity start.
    /// </summary>
    [JsonPropertyName("not_before")]
    public required DateTimeOffset NotBefore { get; init; }

    /// <summary>
    /// PEM-encoded private key — returned only on generation. -- SECRET: redacted from ToString
    /// and from every rendering except the one request body it is sent in.
    /// </summary>
    [JsonPropertyName("private_key_pem")]
    public required Sensitive<string> PrivateKeyPem { get; init; }

    /// <summary>
    /// PEM-encoded public certificate.
    /// </summary>
    [JsonPropertyName("public_cert_pem")]
    public required string PublicCertPem { get; init; }

    /// <summary>
    /// the server's status field
    /// </summary>
    [JsonPropertyName("status")]
    public required CertificateStatus Status { get; init; }

    /// <summary>
    /// The certificate subject (e.g., <c>CN=device-001</c>).
    /// </summary>
    [JsonPropertyName("subject")]
    public required string Subject { get; init; }

    /// <summary>
    /// The tenant this certificate belongs to.
    /// </summary>
    [JsonPropertyName("tenant_id")]
    public required Guid TenantId { get; init; }
}
