// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// The GrantPermissionRequest schema from the server's OpenAPI document.
/// </summary>
public sealed record GrantPermissionRequest
{
    /// <summary>
    /// B1: <c>"allow"</c> (the default) or <c>"deny"</c>. A deny grant **overrides every
    /// allow**, at any depth of the resource hierarchy and at equal specificity — it is not
    /// most-specific-wins. See <c>claude_dev/deny-override-design.md</c> for the precedence
    /// table and for why that trade was made. Omitting the field means <c>"allow"</c>, so every
    /// existing client keeps working unchanged and no migration is required.
    /// </summary>
    [JsonPropertyName("effect")]
    public PermissionEffect? Effect { get; init; }

    /// <summary>
    /// the server's permission_id field
    /// </summary>
    [JsonPropertyName("permission_id")]
    public required Guid PermissionId { get; init; }

    /// <summary>
    /// the server's scope_ids field
    /// </summary>
    [JsonPropertyName("scope_ids")]
    public IReadOnlyList<Guid>? ScopeIds { get; init; }
}
