// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// One row of the group-mapping table (G-3, T23.3.4, D-30): a directory group, named by its
/// distinguished name, and the AXIAM group a member of it is put into. **The table is the only
/// way a directory group reaches an AXIAM group.** There is no match by name, no prefix or
/// wildcard, and no AXIAM group is ever created from a directory one: a directory administrator
/// who names a group <c>admins</c> gains nothing unless a tenant administrator mapped it here.
/// The DN is stored as the administrator typed it and compared after RFC 4514 normalisation
/// (<c>axiam_directory::dn</c>), so <c>CN=Staff, OU=Groups</c> and <c>cn=staff,ou=groups</c>
/// are the same row. One DN may map to several AXIAM groups; the same (DN, group) pair twice is
/// refused as redundant.
/// </summary>
public sealed record GroupMapping
{
    /// <summary>
    /// The directory group's distinguished name.
    /// </summary>
    [JsonPropertyName("directory_group_dn")]
    public required string DirectoryGroupDn { get; init; }

    /// <summary>
    /// The AXIAM group of the same tenant a member of that directory group is put into. Checked
    /// to exist in the tenant when the configuration is written.
    /// </summary>
    [JsonPropertyName("group_id")]
    public required Guid GroupId { get; init; }
}
