// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using Axiam.Sdk.Core;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// Body of <c>POST /api/v1/organizations/{org_id}/ca-certificates/import</c>. Deliberately
/// carries no subject, validity window or key algorithm: all three are read out of the
/// certificate itself. A caller that could name them separately could name a subject the
/// certificate does not have, and AXIAM would enforce the claim while every relying party read
/// the certificate.
/// </summary>
public sealed record ImportCaCertificateRequest
{
    /// <summary>
    /// PEM-encoded private key, if AXIAM is to take custody of it. Omit it to register the
    /// certificate as a trust anchor only. Write-only: it goes to the configured custodian on
    /// the way in and no endpoint returns it. -- SECRET: redacted from ToString and from every
    /// rendering except the one request body it is sent in.
    /// </summary>
    [JsonPropertyName("private_key_pem")]
    public Sensitive<string>? PrivateKeyPem { get; init; }

    /// <summary>
    /// PEM-encoded CA certificate.
    /// </summary>
    [JsonPropertyName("public_cert_pem")]
    public required string PublicCertPem { get; init; }
}
