// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// <c>POST …/saml/idp-credentials</c> body.
/// </summary>
public sealed record IssueSamlIdpCredential
{
    /// <summary>
    /// An active signing CA the caller may issue from.
    /// </summary>
    [JsonPropertyName("issuer_ca_id")]
    public required Guid IssuerCaId { get; init; }

    /// <summary>
    /// The slot to fill; it must be empty.
    /// </summary>
    [JsonPropertyName("slot")]
    public required SamlIdpSlot Slot { get; init; }

    /// <summary>
    /// 1 to 730, default 365; never beyond the CA's own expiry.
    /// </summary>
    [JsonPropertyName("validity_days")]
    public long? ValidityDays { get; init; }
}
