// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// <c>POST /api/v1/mds/refresh</c> response — the outcome of one ingestion attempt (mirrors
/// <c>axiam_db::mds_ingest::MdsIngestOutcome</c>).
/// </summary>
/// <remarks>
/// <para>
/// A closed set of shapes discriminated by the outcome field. System.Text.Json resolves the
/// derived type from that discriminator, so a caller pattern-matches on the record type rather
/// than reading a string and hoping.
/// </para>
/// </remarks>
[JsonPolymorphic(TypeDiscriminatorPropertyName = "outcome")]
[JsonDerivedType(typeof(MdsRefreshOutcomeInitial), "initial")]
[JsonDerivedType(typeof(MdsRefreshOutcomeReplaced), "replaced")]
[JsonDerivedType(typeof(MdsRefreshOutcomeNoOpRefresh), "no_op_refresh")]
[JsonDerivedType(typeof(MdsRefreshOutcomeRollbackRejected), "rollback_rejected")]
public abstract record MdsRefreshOutcome;
