// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// The 'no_op_refresh' arm of MdsRefreshOutcome.
/// </summary>
public sealed record MdsRefreshOutcomeNoOpRefresh : MdsRefreshOutcome
{
    /// <summary>
    /// the server's no field
    /// </summary>
    [JsonPropertyName("no")]
    public required long No { get; init; }
}
