// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// <c>GET /api/v1/mds/status</c> response.
/// <c>no</c>/<c>next_update</c>/<c>last_refreshed_at</c> are <c>None</c> and <c>stale</c> is
/// <c>false</c> when MDS has never been ingested — a meaningful, valid answer ("nothing
/// ingested yet"), not an error.
/// </summary>
public sealed record MdsStatusResponse
{
    /// <summary>
    /// the server's entry_count field
    /// </summary>
    [JsonPropertyName("entry_count")]
    public required long EntryCount { get; init; }

    /// <summary>
    /// the server's last_refreshed_at field
    /// </summary>
    [JsonPropertyName("last_refreshed_at")]
    public DateTimeOffset? LastRefreshedAt { get; init; }

    /// <summary>
    /// the server's next_update field
    /// </summary>
    [JsonPropertyName("next_update")]
    public string? NextUpdate { get; init; }

    /// <summary>
    /// the server's no field
    /// </summary>
    [JsonPropertyName("no")]
    public long? No { get; init; }

    /// <summary>
    /// the server's stale field
    /// </summary>
    [JsonPropertyName("stale")]
    public required bool Stale { get; init; }
}
