// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// Multi-factor authentication policy.
/// </summary>
public sealed record MfaPolicy
{
    /// <summary>
    /// the server's mfa_challenge_lifetime_secs field
    /// </summary>
    [JsonPropertyName("mfa_challenge_lifetime_secs")]
    public required long MfaChallengeLifetimeSecs { get; init; }

    /// <summary>
    /// the server's mfa_enforced field
    /// </summary>
    [JsonPropertyName("mfa_enforced")]
    public required bool MfaEnforced { get; init; }
}
