// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// The acknowledgement, which is mostly about the restart.
/// </summary>
public sealed record MtlsTrustAnchorResponse
{
    /// <summary>
    /// The CA this is about.
    /// </summary>
    [JsonPropertyName("ca_certificate_id")]
    public required Guid CaCertificateId { get; init; }

    /// <summary>
    /// A sentence an operator can act on, rather than a bare boolean.
    /// </summary>
    [JsonPropertyName("message")]
    public required string Message { get; init; }

    /// <summary>
    /// The flag as now stored.
    /// </summary>
    [JsonPropertyName("mtls_trust_anchor")]
    public required bool MtlsTrustAnchor { get; init; }

    /// <summary>
    /// Always <c>true</c>: rustls builds its client trust store once, when the listener is
    /// constructed, so this takes effect at the next start.
    /// </summary>
    [JsonPropertyName("restart_required")]
    public required bool RestartRequired { get; init; }
}
