// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// OAuth2 client response -- omits client_secret_hash.
/// </summary>
public sealed record OAuth2ClientResponse
{
    /// <summary>
    /// T21.3 — echoed in its stored, normalised form, so an operator auditing which audiences a
    /// client may mint tokens for reads the strings the server actually compares rather than
    /// the ones they typed.
    /// </summary>
    [JsonPropertyName("allowed_resources")]
    public required IReadOnlyList<string> AllowedResources { get; init; }

    /// <summary>
    /// X7.1 — echoed so an operator can audit which clients act on the OIDC
    /// authentication-request parameters, from this endpoint rather than from the database.
    /// </summary>
    [JsonPropertyName("authn_request_params")]
    public required AuthnRequestParamsMode AuthnRequestParams { get; init; }

    /// <summary>
    /// X7.3 — echoed for the same reason.
    /// </summary>
    [JsonPropertyName("browser_sso")]
    public required bool BrowserSso { get; init; }

    /// <summary>
    /// the server's client_id field
    /// </summary>
    [JsonPropertyName("client_id")]
    public required string ClientId { get; init; }

    /// <summary>
    /// the server's created_at field
    /// </summary>
    [JsonPropertyName("created_at")]
    public required DateTimeOffset CreatedAt { get; init; }

    /// <summary>
    /// the server's dpop_bound_access_tokens field
    /// </summary>
    [JsonPropertyName("dpop_bound_access_tokens")]
    public required bool DpopBoundAccessTokens { get; init; }

    /// <summary>
    /// the server's dpop_require_nonce field
    /// </summary>
    [JsonPropertyName("dpop_require_nonce")]
    public required bool DpopRequireNonce { get; init; }

    /// <summary>
    /// the server's grant_types field
    /// </summary>
    [JsonPropertyName("grant_types")]
    public required IReadOnlyList<string> GrantTypes { get; init; }

    /// <summary>
    /// the server's id field
    /// </summary>
    [JsonPropertyName("id")]
    public required Guid Id { get; init; }

    /// <summary>
    /// X5.1 — echoed so an operator can confirm which key source is registered. The document
    /// itself is public key material, so returning it leaks nothing; a <c>jwks_uri</c> is
    /// likewise public by construction.
    /// </summary>
    [JsonPropertyName("jwks")]
    public string? Jwks { get; init; }

    /// <summary>
    /// the server's jwks_uri field
    /// </summary>
    [JsonPropertyName("jwks_uri")]
    public string? JwksUri { get; init; }

    /// <summary>
    /// T21.4 — when this client was last issued an authorization code, for the sweeper that
    /// deletes self-registered clients nobody uses. Always absent for an <c>admin</c> client:
    /// the stamp is written only for a non-<c>admin</c> one, so that an administrator's client
    /// takes exactly the path it took before T21.4 (I1). <c>null</c> on a self-registered
    /// client means it has never been authorized, and the sweeper reads <c>created_at</c>
    /// instead.
    /// </summary>
    [JsonPropertyName("last_authorized_at")]
    public DateTimeOffset? LastAuthorizedAt { get; init; }

    /// <summary>
    /// T21.4 / D5 — who created this registration: <c>admin</c>, <c>dcr</c> or <c>cimd</c>.
    /// Echoed because an operator auditing a tenant needs to answer "which of these did we
    /// create?" from this endpoint rather than from the database, and because three behaviours
    /// hang off it: a non-<c>admin</c> client may never carry the FAPI profile, is always
    /// consent-gated, and is the only kind the unused-client sweeper touches. Read-only. There
    /// is no corresponding member on the update DTO: a registration's provenance is a fact
    /// about how it came to exist, and a field that could be edited to <c>admin</c> would be a
    /// field that launders one.
    /// </summary>
    [JsonPropertyName("managed_by")]
    public required ManagedBy ManagedBy { get; init; }

    /// <summary>
    /// the server's name field
    /// </summary>
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    /// <summary>
    /// X5.1 — the registered posture and mTLS credentials. Read-back matters: an operator
    /// auditing which clients are financial-grade should be able to answer it from this
    /// endpoint rather than from the database.
    /// </summary>
    [JsonPropertyName("profile")]
    public required ClientProfile Profile { get; init; }

    /// <summary>
    /// the server's redirect_uris field
    /// </summary>
    [JsonPropertyName("redirect_uris")]
    public required IReadOnlyList<string> RedirectUris { get; init; }

    /// <summary>
    /// the server's require_par field
    /// </summary>
    [JsonPropertyName("require_par")]
    public required bool RequirePar { get; init; }

    /// <summary>
    /// the server's scopes field
    /// </summary>
    [JsonPropertyName("scopes")]
    public required IReadOnlyList<string> Scopes { get; init; }

    /// <summary>
    /// the server's self_signed_tls_client_auth_thumbprints field
    /// </summary>
    [JsonPropertyName("self_signed_tls_client_auth_thumbprints")]
    public required IReadOnlyList<string> SelfSignedTlsClientAuthThumbprints { get; init; }

    /// <summary>
    /// the server's tenant_id field
    /// </summary>
    [JsonPropertyName("tenant_id")]
    public required Guid TenantId { get; init; }

    /// <summary>
    /// the server's tls_client_auth_san_dns field
    /// </summary>
    [JsonPropertyName("tls_client_auth_san_dns")]
    public string? TlsClientAuthSanDns { get; init; }

    /// <summary>
    /// the server's tls_client_auth_san_uri field
    /// </summary>
    [JsonPropertyName("tls_client_auth_san_uri")]
    public string? TlsClientAuthSanUri { get; init; }

    /// <summary>
    /// the server's tls_client_auth_subject_dn field
    /// </summary>
    [JsonPropertyName("tls_client_auth_subject_dn")]
    public string? TlsClientAuthSubjectDn { get; init; }

    /// <summary>
    /// the server's tls_client_certificate_bound_access_tokens field
    /// </summary>
    [JsonPropertyName("tls_client_certificate_bound_access_tokens")]
    public required bool TlsClientCertificateBoundAccessTokens { get; init; }

    /// <summary>
    /// the server's token_endpoint_auth_method field
    /// </summary>
    [JsonPropertyName("token_endpoint_auth_method")]
    public required ClientAuthMethod TokenEndpointAuthMethod { get; init; }

    /// <summary>
    /// the server's updated_at field
    /// </summary>
    [JsonPropertyName("updated_at")]
    public required DateTimeOffset UpdatedAt { get; init; }
}
