// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// The OidcCallbackRequest schema from the server's OpenAPI document.
/// </summary>
public sealed record OidcCallbackRequest
{
    /// <summary>
    /// Authorization code returned by the external IdP.
    /// </summary>
    [JsonPropertyName("code")]
    public required string Code { get; init; }

    /// <summary>
    /// ID of the federation config used in the authorization request.
    /// </summary>
    [JsonPropertyName("config_id")]
    public required Guid ConfigId { get; init; }

    /// <summary>
    /// Client-supplied nonce (SECHRD-07/D-04: retained for backward compatibility with older
    /// callers, but IGNORED for verification — <c>expected_nonce</c> always comes from the
    /// server-side <c>FederationLoginState</c> row looked up via <c>state</c>, never from this
    /// field).
    /// </summary>
    [JsonPropertyName("nonce")]
    public required string Nonce { get; init; }

    /// <summary>
    /// Redirect URI that was used in the authorization request.
    /// </summary>
    [JsonPropertyName("redirect_uri")]
    public required string RedirectUri { get; init; }

    /// <summary>
    /// CSRF state value from the authorization request. Used to look up the server-side
    /// <c>FederationLoginState</c> row that holds the real nonce (SECHRD-07/D-04) — required so
    /// the callback can find its login state.
    /// </summary>
    [JsonPropertyName("state")]
    public required string State { get; init; }
}
