// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// <c>POST …/saml/parse-sp-metadata</c> body: **exactly one** of the two members.
/// </summary>
/// <remarks>
/// <para>
/// Every property is optional: one you leave unset is omitted from the wire entirely rather
/// than sent as null.
/// </para>
/// </remarks>
public sealed partial record ParseSamlSpMetadata
{
    /// <summary>
    /// An <c>https</c> URL the server fetches the document from, once, through its SSRF guard.
    /// </summary>
    [JsonPropertyName("metadata_url")]
    public string? MetadataUrl { get; init; }

    /// <summary>
    /// A metadata document, at most 512 KiB.
    /// </summary>
    [JsonPropertyName("metadata_xml")]
    public string? MetadataXml { get; init; }
}
