// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// Password complexity and history requirements.
/// </summary>
public sealed record PasswordPolicy
{
    /// <summary>
    /// the server's hibp_check_enabled field
    /// </summary>
    [JsonPropertyName("hibp_check_enabled")]
    public required bool HibpCheckEnabled { get; init; }

    /// <summary>
    /// the server's min_length field
    /// </summary>
    [JsonPropertyName("min_length")]
    public required int MinLength { get; init; }

    /// <summary>
    /// the server's password_history_count field
    /// </summary>
    [JsonPropertyName("password_history_count")]
    public required int PasswordHistoryCount { get; init; }

    /// <summary>
    /// the server's require_digits field
    /// </summary>
    [JsonPropertyName("require_digits")]
    public required bool RequireDigits { get; init; }

    /// <summary>
    /// the server's require_lowercase field
    /// </summary>
    [JsonPropertyName("require_lowercase")]
    public required bool RequireLowercase { get; init; }

    /// <summary>
    /// the server's require_symbols field
    /// </summary>
    [JsonPropertyName("require_symbols")]
    public required bool RequireSymbols { get; init; }

    /// <summary>
    /// the server's require_uppercase field
    /// </summary>
    [JsonPropertyName("require_uppercase")]
    public required bool RequireUppercase { get; init; }
}
