// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using Axiam.Sdk.Management;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// Key algorithm for OpenPGP keys.
/// </summary>
/// <remarks>
/// <para>
/// Each member carries the spelling the server uses on the wire via WireName, so the C# name
/// can follow C# conventions without changing what is sent. An unknown value throws rather than
/// silently becoming the zero member.
/// </para>
/// </remarks>
[JsonConverter(typeof(WireEnumConverter<PgpKeyAlgorithm>))]
public enum PgpKeyAlgorithm
{
    /// <summary>The server's <c>Rsa4096</c> value.</summary>
    [WireName("Rsa4096")]
    Rsa4096,

    /// <summary>The server's <c>Ed25519</c> value.</summary>
    [WireName("Ed25519")]
    Ed25519,
}
