// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// <c>GET</c> response: the stored policy plus the unknown-AAGUID action it currently *resolves
/// to*. <c>unknown_aaguid</c> is nullable, where <c>null</c> means "use this mode's default"
/// (deny under <c>direct_required</c>, allow otherwise). A client that only saw the stored
/// <c>null</c> would have to re-derive that rule itself to display what the policy actually
/// does — and a security rule implemented twice is a security rule that will eventually
/// disagree with itself. So the server resolves it once, here, and reports both: the admin's
/// stored intent and its effect.
/// </summary>
public sealed record PolicyResponse
{
    /// <summary>
    /// <c>None</c> = every AAGUID is allowed except <c>blocked_aaguids</c>. <c>Some(vec![])</c>
    /// is a deliberate "nothing may register" policy and is accepted as such: <c>evaluate</c>
    /// denies every AAGUID against an empty allow-list. Nothing rejects it, precisely because
    /// the failure direction is safe — a client that sends <c>[]</c> when it meant <c>null</c>
    /// gets a locked-down tenant, which is visible immediately, rather than an open one, which
    /// is not.
    /// </summary>
    [JsonPropertyName("allowed_aaguids")]
    public IReadOnlyList<Guid>? AllowedAaguids { get; init; }

    /// <summary>
    /// Deny registration if the MDS entry has ever reported <c>REVOKED</c> or any
    /// <c>*_COMPROMISE</c> status (sticky — D8 step 7).
    /// </summary>
    [JsonPropertyName("block_revoked_status")]
    public required bool BlockRevokedStatus { get; init; }

    /// <summary>
    /// the server's blocked_aaguids field
    /// </summary>
    [JsonPropertyName("blocked_aaguids")]
    public IReadOnlyList<Guid>? BlockedAaguids { get; init; }

    /// <summary>
    /// The action actually applied to an AAGUID with no MDS metadata, with <c>unknown_aaguid:
    /// null</c> resolved against <c>mode</c>. Read-only — <c>PUT</c> ignores it.
    /// </summary>
    [JsonPropertyName("effective_unknown_aaguid")]
    public required UnknownAaguidAction EffectiveUnknownAaguid { get; init; }

    /// <summary>
    /// the server's min_certification field
    /// </summary>
    [JsonPropertyName("min_certification")]
    public CertificationLevel? MinCertification { get; init; }

    /// <summary>
    /// the server's mode field
    /// </summary>
    [JsonPropertyName("mode")]
    public required AttestationMode Mode { get; init; }

    /// <summary>
    /// Require *some* <c>FIDO_CERTIFIED*</c> status, any level. Independent of (and checked
    /// before) <c>min_certification</c>.
    /// </summary>
    [JsonPropertyName("require_fido_certified")]
    public required bool RequireFidoCertified { get; init; }

    /// <summary>
    /// the server's unknown_aaguid field
    /// </summary>
    [JsonPropertyName("unknown_aaguid")]
    public UnknownAaguidAction? UnknownAaguid { get; init; }
}
