// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// API-based provider configuration (SendGrid, Postmark, Resend, Brevo). <c>api_key</c> follows
/// the same write-only + omit-preserving contract as [<c>SmtpConfig::password</c>] (D-01/D-02).
/// </summary>
public sealed record ProviderConfigSendGrid : ProviderConfig
{
    /// <summary>
    /// Override base URL (useful for testing / self-hosted instances).
    /// </summary>
    [JsonPropertyName("api_url")]
    public string? ApiUrl { get; init; }
}
