// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// A user together with the resource scope of their assignment of this role.
/// </summary>
public sealed record RoleUserAssignment
{
    /// <summary>
    /// <c>None</c> means the role was assigned globally (no resource scope).
    /// </summary>
    [JsonPropertyName("resource_id")]
    public Guid? ResourceId { get; init; }

    /// <summary>
    /// The tenants this assignment reaches, or omitted for "wherever the role does". Shown next
    /// to the assignment so an operator can tell a deliberately narrowed grant from an
    /// organization-wide one.
    /// </summary>
    [JsonPropertyName("tenant_scope")]
    public IReadOnlyList<Guid>? TenantScope
    {
        get => _tenantScope;
        init => _tenantScope = value is { Count: 0 } ? null : value;
    }

    private readonly IReadOnlyList<Guid>? _tenantScope;

    /// <summary>
    /// The assigned user.
    /// </summary>
    [JsonPropertyName("user")]
    public required UserResponse User { get; init; }
}
