// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// The tenant's SAML IdP, as the administrator needs to see it before and while switching it
/// on: what an SP will be given, and whether it answers yet.
/// </summary>
public sealed record SamlIdpInfo
{
    /// <summary>
    /// The <c>active</c> credential, or null.
    /// </summary>
    [JsonPropertyName("active_credential_id")]
    public Guid? ActiveCredentialId { get; init; }

    /// <summary>
    /// The IdP's entity id (the metadata URL itself).
    /// </summary>
    [JsonPropertyName("entity_id")]
    public required string EntityId { get; init; }

    /// <summary>
    /// Whether <c>metadata_url</c> answers now: SAML is available, enabled for the tenant, and
    /// an <c>active</c> or <c>next</c> credential exists (D-40).
    /// </summary>
    [JsonPropertyName("metadata_served")]
    public required bool MetadataServed { get; init; }

    /// <summary>
    /// Where the IdP metadata is served.
    /// </summary>
    [JsonPropertyName("metadata_url")]
    public required string MetadataUrl { get; init; }

    /// <summary>
    /// The <c>next</c> credential, or null.
    /// </summary>
    [JsonPropertyName("next_credential_id")]
    public Guid? NextCredentialId { get; init; }

    /// <summary>
    /// Whether this server build serves SAML at all (it was built with the <c>saml</c>
    /// feature).
    /// </summary>
    [JsonPropertyName("saml_available")]
    public required bool SamlAvailable { get; init; }

    /// <summary>
    /// The tenant's **effective** <c>saml_idp_enabled</c> setting (D-20). Written through the
    /// <c>settings</c> operations, not here.
    /// </summary>
    [JsonPropertyName("saml_idp_enabled")]
    public required bool SamlIdpEnabled { get; init; }

    /// <summary>
    /// The single-logout endpoint.
    /// </summary>
    [JsonPropertyName("slo_url")]
    public required string SloUrl { get; init; }

    /// <summary>
    /// The single-sign-on endpoint.
    /// </summary>
    [JsonPropertyName("sso_url")]
    public required string SsoUrl { get; init; }

    /// <summary>
    /// The tenant.
    /// </summary>
    [JsonPropertyName("tenant_id")]
    public required Guid TenantId { get; init; }
}
