// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// The tenant's IdP signing credential, **public facts only**. There is no key on it and no
/// field a key could be put in: the private key is generated by the server, sealed at rest,
/// never returned by any route and destroyed on retirement (D-21).
/// </summary>
public sealed record SamlIdpCredential
{
    /// <summary>
    /// The leaf certificate, PEM. Public: it is what the metadata publishes.
    /// </summary>
    [JsonPropertyName("certificate_pem")]
    public required string CertificatePem { get; init; }

    /// <summary>
    /// When the credential was issued.
    /// </summary>
    [JsonPropertyName("created_at")]
    public required DateTimeOffset CreatedAt { get; init; }

    /// <summary>
    /// Lower-case hex SHA-256 of the certificate's DER — what an SP administrator compares out
    /// of band.
    /// </summary>
    [JsonPropertyName("fingerprint")]
    public required string Fingerprint { get; init; }

    /// <summary>
    /// Credential id.
    /// </summary>
    [JsonPropertyName("id")]
    public required Guid Id { get; init; }

    /// <summary>
    /// The signing CA that issued the leaf.
    /// </summary>
    [JsonPropertyName("issuer_ca_id")]
    public required Guid IssuerCaId { get; init; }

    /// <summary>
    /// End of the certificate's validity (at most 730 days after the start).
    /// </summary>
    [JsonPropertyName("not_after")]
    public required DateTimeOffset NotAfter { get; init; }

    /// <summary>
    /// Start of the certificate's validity.
    /// </summary>
    [JsonPropertyName("not_before")]
    public required DateTimeOffset NotBefore { get; init; }

    /// <summary>
    /// When it was retired, or null.
    /// </summary>
    [JsonPropertyName("retired_at")]
    public DateTimeOffset? RetiredAt { get; init; }

    /// <summary>
    /// The certificate's serial, lower-case hex.
    /// </summary>
    [JsonPropertyName("serial")]
    public required string Serial { get; init; }

    /// <summary>
    /// <c>active</c>, <c>next</c> or <c>retired</c>. At most one <c>active</c> and one
    /// <c>next</c> per tenant.
    /// </summary>
    [JsonPropertyName("status")]
    public required SamlIdpCredentialStatus Status { get; init; }

    /// <summary>
    /// The tenant it signs for.
    /// </summary>
    [JsonPropertyName("tenant_id")]
    public required Guid TenantId { get; init; }
}
