// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using Axiam.Sdk.Management;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// Which users a target provisions.
/// </summary>
/// <remarks>
/// <para>
/// An <b>open</b> set of shapes discriminated by the <c>type</c> field (CONTRACT.md &#167;31.2,
/// &#167;27.13): a caller pattern-matches on the record type, and a <c>type</c> this SDK does
/// not know decodes to <see cref="ScimTargetScopeUnknown"/> rather than failing the response it
/// arrived in. That arm is never sent: the request encoder refuses it locally, before any
/// request, with a <see cref="Axiam.Sdk.Management.ValidationError"/>. Serializing it anywhere
/// else, for a log line, never fails: it renders its <c>type</c> and nothing else (CONTRACT.md
/// &#167;34.2 P12.2).
/// </para>
/// </remarks>
[JsonConverter(typeof(ScimTargetScopeConverter))]
public abstract record ScimTargetScope;

/// <summary>
/// A <c>type</c> this SDK does not know. Reachable only by decoding; the members it arrived
/// with are not kept, and it is never sent (CONTRACT.md &#167;31.2).
/// </summary>
public sealed record ScimTargetScopeUnknown : ScimTargetScope
{
    internal ScimTargetScopeUnknown(string? type)
    {
        Type = type;
    }

    /// <summary>The <c>type</c> the server sent, or <c>null</c> when it sent none.</summary>
    public string? Type { get; }
}

/// <summary>
/// Wire converter for ScimTargetScope: dispatches on <c>type</c> when reading (an unknown value
/// becomes ScimTargetScopeUnknown) and writes the arm's members after the tag.
/// ScimTargetScopeUnknown is refused by the request encoder (<c>ManagementJson.Wire</c>) and
/// rendered as its <c>type</c> alone by every other serializer.
/// </summary>
internal sealed class ScimTargetScopeConverter : JsonConverter<ScimTargetScope>
{
    /// <inheritdoc/>
    public override ScimTargetScope Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using JsonDocument doc = JsonDocument.ParseValue(ref reader);
        JsonElement root = doc.RootElement;
        if (root.ValueKind != JsonValueKind.Object)
        {
            throw new JsonException("ScimTargetScope must be a JSON object");
        }

        string? tag = root.TryGetProperty("type", out JsonElement tagEl) && tagEl.ValueKind == JsonValueKind.String ? tagEl.GetString() : null;
        return tag switch
        {
            "all_users" => root.Deserialize<ScimTargetScopeAllUsers>(options)!,
            "groups" => root.Deserialize<ScimTargetScopeGroups>(options)!,
            _ => new ScimTargetScopeUnknown(tag),
        };
    }

    /// <inheritdoc/>
    public override void Write(Utf8JsonWriter writer, ScimTargetScope value, JsonSerializerOptions options)
    {
        if (value is ScimTargetScopeUnknown unknown)
        {
            // CONTRACT.md §34.2 P12.2: refused on the request path, never in a rendering.
            if (ManagementJson.IsWire(options))
            {
                throw new ValidationError(
                    "ScimTargetScope: refusing to send a type this SDK does not know (CONTRACT.md §31.2); "
                    + "replace it with a known arm before writing back",
                    Array.Empty<FieldError>());
            }

            writer.WriteStartObject();
            if (unknown.Type is not null)
            {
                writer.WriteString("type", unknown.Type);
            }

            writer.WriteEndObject();
            return;
        }

        string tag = value switch
        {
            ScimTargetScopeAllUsers => "all_users",
            ScimTargetScopeGroups => "groups",
            _ => throw new ValidationError(
                "ScimTargetScope: refusing to send a type this SDK does not know (CONTRACT.md §31.2); "
                + "replace it with a known arm before writing back",
                Array.Empty<FieldError>()),
        };
        JsonElement fields = JsonSerializer.SerializeToElement(value, value.GetType(), options);
        writer.WriteStartObject();
        writer.WriteString("type", tag);
        foreach (JsonProperty member in fields.EnumerateObject())
        {
            if (member.NameEquals("type"))
            {
                continue;
            }

            member.WriteTo(writer);
        }

        writer.WriteEndObject();
    }
}
