// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using Axiam.Sdk.Management;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// Why a token is or is not currently usable — for display only. The authentication path never
/// surfaces this distinction on the wire.
/// </summary>
/// <remarks>
/// <para>
/// Each member carries the spelling the server uses on the wire via WireName, so the C# name
/// can follow C# conventions without changing what is sent. An unknown value throws rather than
/// silently becoming the zero member.
/// </para>
/// </remarks>
[JsonConverter(typeof(WireEnumConverter<ScimTokenStatus>))]
public enum ScimTokenStatus
{
    /// <summary>The server's <c>active</c> value.</summary>
    [WireName("active")]
    Active,

    /// <summary>The server's <c>expired</c> value.</summary>
    [WireName("expired")]
    Expired,

    /// <summary>The server's <c>revoked</c> value.</summary>
    [WireName("revoked")]
    Revoked,
}
