// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// The 'groups' arm of ScimTargetScope.
/// </summary>
public sealed record ScimTargetScopeGroups : ScimTargetScope
{
    /// <summary>
    /// Users who are direct members of any listed group.
    /// </summary>
    [JsonPropertyName("group_ids")]
    public required IReadOnlyList<Guid> GroupIds { get; init; }
}
