// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// A registered SCIM target, as the management API returns it. **The credential is never
/// returned**, and there is no member that says anything about it.
/// </summary>
public sealed record ScimTargetResponse
{
    /// <summary>
    /// How AXIAM authenticates to it (no credential).
    /// </summary>
    [JsonPropertyName("auth")]
    public required ScimTargetAuth Auth { get; init; }

    /// <summary>
    /// The downstream's SCIM service root.
    /// </summary>
    [JsonPropertyName("base_url")]
    public required string BaseUrl { get; init; }

    /// <summary>
    /// When the target was registered.
    /// </summary>
    [JsonPropertyName("created_at")]
    public required DateTimeOffset CreatedAt { get; init; }

    /// <summary>
    /// What happens downstream to a user who leaves scope or is no longer active (erasure
    /// always deletes).
    /// </summary>
    [JsonPropertyName("deprovision")]
    public required DeprovisionPolicy Deprovision { get; init; }

    /// <summary>
    /// Whether AXIAM pushes to it.
    /// </summary>
    [JsonPropertyName("enabled")]
    public required bool Enabled { get; init; }

    /// <summary>
    /// The target id.
    /// </summary>
    [JsonPropertyName("id")]
    public required Guid Id { get; init; }

    /// <summary>
    /// The name.
    /// </summary>
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    /// <summary>
    /// Whether groups are pushed too.
    /// </summary>
    [JsonPropertyName("push_groups")]
    public required bool PushGroups { get; init; }

    /// <summary>
    /// Which users it provisions.
    /// </summary>
    [JsonPropertyName("scope")]
    public required ScimTargetScope Scope { get; init; }

    /// <summary>
    /// the server's state field
    /// </summary>
    [JsonPropertyName("state")]
    public ScimTargetDeliveryState? State { get; init; }

    /// <summary>
    /// The owning tenant.
    /// </summary>
    [JsonPropertyName("tenant_id")]
    public required Guid TenantId { get; init; }

    /// <summary>
    /// When it was last written: the version an update is conditional on.
    /// </summary>
    [JsonPropertyName("updated_at")]
    public required DateTimeOffset UpdatedAt { get; init; }

    /// <summary>
    /// Which attribute becomes <c>userName</c>.
    /// </summary>
    [JsonPropertyName("user_name_from")]
    public required UserNameSource UserNameFrom { get; init; }
}
