// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// Fully resolved security settings (all fields present).
/// </summary>
public sealed record SecuritySettings
{
    /// <summary>
    /// the server's certificate field
    /// </summary>
    [JsonPropertyName("certificate")]
    public required CertificatePolicy Certificate { get; init; }

    /// <summary>
    /// the server's created_at field
    /// </summary>
    [JsonPropertyName("created_at")]
    public required DateTimeOffset CreatedAt { get; init; }

    /// <summary>
    /// the server's email field
    /// </summary>
    [JsonPropertyName("email")]
    public required EmailVerificationPolicy Email { get; init; }

    /// <summary>
    /// the server's id field
    /// </summary>
    [JsonPropertyName("id")]
    public required Guid Id { get; init; }

    /// <summary>
    /// the server's lockout field
    /// </summary>
    [JsonPropertyName("lockout")]
    public required LockoutPolicy Lockout { get; init; }

    /// <summary>
    /// the server's mfa field
    /// </summary>
    [JsonPropertyName("mfa")]
    public required MfaPolicy Mfa { get; init; }

    /// <summary>
    /// the server's notification field
    /// </summary>
    [JsonPropertyName("notification")]
    public required NotificationPolicy Notification { get; init; }

    /// <summary>
    /// the server's opaque field
    /// </summary>
    [JsonPropertyName("opaque")]
    public required OpaquePolicy Opaque { get; init; }

    /// <summary>
    /// the server's password field
    /// </summary>
    [JsonPropertyName("password")]
    public required PasswordPolicy Password { get; init; }

    /// <summary>
    /// the server's privacy field
    /// </summary>
    [JsonPropertyName("privacy")]
    public required PrivacyPolicy Privacy { get; init; }

    /// <summary>
    /// the server's scope field
    /// </summary>
    [JsonPropertyName("scope")]
    public required SettingsScope Scope { get; init; }

    /// <summary>
    /// the server's scope_id field
    /// </summary>
    [JsonPropertyName("scope_id")]
    public required Guid ScopeId { get; init; }

    /// <summary>
    /// the server's token field
    /// </summary>
    [JsonPropertyName("token")]
    public required TokenPolicy Token { get; init; }

    /// <summary>
    /// the server's updated_at field
    /// </summary>
    [JsonPropertyName("updated_at")]
    public required DateTimeOffset UpdatedAt { get; init; }
}
