// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// Public-safe service account representation.
/// </summary>
public sealed record ServiceAccountResponse
{
    /// <summary>
    /// the server's client_id field
    /// </summary>
    [JsonPropertyName("client_id")]
    public required string ClientId { get; init; }

    /// <summary>
    /// the server's created_at field
    /// </summary>
    [JsonPropertyName("created_at")]
    public required DateTimeOffset CreatedAt { get; init; }

    /// <summary>
    /// the server's description field
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; init; }

    /// <summary>
    /// the server's id field
    /// </summary>
    [JsonPropertyName("id")]
    public required Guid Id { get; init; }

    /// <summary>
    /// the server's name field
    /// </summary>
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    /// <summary>
    /// the server's status field
    /// </summary>
    [JsonPropertyName("status")]
    public required UserStatus Status { get; init; }

    /// <summary>
    /// the server's tenant_id field
    /// </summary>
    [JsonPropertyName("tenant_id")]
    public required Guid TenantId { get; init; }

    /// <summary>
    /// the server's updated_at field
    /// </summary>
    [JsonPropertyName("updated_at")]
    public required DateTimeOffset UpdatedAt { get; init; }
}
