// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using Axiam.Sdk.Core;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// <c>PUT /api/v1/tenants/{tenant_id}/directory</c> — a **replacement**. Every
/// <c>DirectoryConfig</c> member except <c>id</c>, <c>tenant_id</c> and the two timestamps,
/// plus the write-only <c>bind_secret</c>. An omitted optional member is **reset to its
/// default**, not kept.
/// </summary>
/// <remarks>
/// <para>
/// This body REPLACES rather than patches (&#167;27.4 rule 5): what you do not carry over from
/// a prior read is not preserved, it is overwritten. Every property is required, so forgetting
/// one is a compile error rather than a silent null on the wire. Read first,
/// <c>with</c>-expression the parts you mean to keep, write back.
/// </para>
/// </remarks>
public sealed record SetDirectoryConfig
{
    /// <summary>
    /// Where users are searched for.
    /// </summary>
    [JsonPropertyName("base_dn")]
    public required string BaseDn { get; init; }

    /// <summary>
    /// The service account the search runs as.
    /// </summary>
    [JsonPropertyName("bind_dn")]
    public required string BindDn { get; init; }

    /// <summary>
    /// The service account's password: **write-only**, 1 to 4096 octets. Required when the
    /// tenant has no configuration yet; on a replacement, absent means *keep the stored secret*
    /// — unless the write moves the connection (<c>url</c>, <c>start_tls</c>, <c>bind_dn</c> or
    /// <c>trust_anchors_pem</c>), which then requires it (<c>400</c>, P23W2-01). -- SECRET:
    /// redacted from ToString and from every rendering except the one request body it is sent
    /// in.
    /// </summary>
    [JsonPropertyName("bind_secret")]
    public Sensitive<string>? BindSecret { get; init; }

    /// <summary>
    /// A disabled directory serves no sign-in and is not synced.
    /// </summary>
    [JsonPropertyName("enabled")]
    public required bool Enabled { get; init; }

    /// <summary>
    /// Defaults to null.
    /// </summary>
    [JsonPropertyName("group_base_dn")]
    public string? GroupBaseDn { get; init; }

    /// <summary>
    /// Defaults to null.
    /// </summary>
    [JsonPropertyName("group_filter")]
    public string? GroupFilter { get; init; }

    /// <summary>
    /// At most 500; every <c>group_id</c> a group of the tenant. Default empty.
    /// </summary>
    [JsonPropertyName("group_mappings")]
    public IReadOnlyList<GroupMapping>? GroupMappings { get; init; }

    /// <summary>
    /// Defaults by <c>kind</c>.
    /// </summary>
    [JsonPropertyName("group_member_attribute")]
    public string? GroupMemberAttribute { get; init; }

    /// <summary>
    /// <c>0..=10</c>, default 5.
    /// </summary>
    [JsonPropertyName("group_nesting_depth")]
    public int? GroupNestingDepth { get; init; }

    /// <summary>
    /// Default false.
    /// </summary>
    [JsonPropertyName("jit_provisioning")]
    public bool? JitProvisioning { get; init; }

    /// <summary>
    /// Chooses defaults only.
    /// </summary>
    [JsonPropertyName("kind")]
    public required DirectoryKind Kind { get; init; }

    /// <summary>
    /// Upgrade an <c>ldap://</c> connection with StartTLS before any bind.
    /// </summary>
    [JsonPropertyName("start_tls")]
    public required bool StartTls { get; init; }

    /// <summary>
    /// <c>300..=86400</c>, default 3600.
    /// </summary>
    [JsonPropertyName("sync_interval_secs")]
    public long? SyncIntervalSecs { get; init; }

    /// <summary>
    /// At most 16 CA certificates in PEM. Default empty (the public roots).
    /// </summary>
    [JsonPropertyName("trust_anchors_pem")]
    public IReadOnlyList<string>? TrustAnchorsPem { get; init; }

    /// <summary>
    /// <c>ldaps://host[:port]</c>, or <c>ldap://host[:port]</c> with <c>start_tls</c>.
    /// </summary>
    [JsonPropertyName("url")]
    public required string Url { get; init; }

    /// <summary>
    /// the server's user_attribute_map field
    /// </summary>
    [JsonPropertyName("user_attribute_map")]
    public UserAttributeMap? UserAttributeMap { get; init; }

    /// <summary>
    /// One <c>{username}</c> placeholder in value position.
    /// </summary>
    [JsonPropertyName("user_filter")]
    public required string UserFilter { get; init; }
}
