// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// Input for setting organization-level security settings.
/// </summary>
/// <remarks>
/// <para>
/// This body REPLACES rather than patches (&#167;27.4 rule 5): what you do not carry over from
/// a prior read is not preserved, it is overwritten. Every property is required, so forgetting
/// one is a compile error rather than a silent null on the wire. Read first,
/// <c>with</c>-expression the parts you mean to keep, write back.
/// </para>
/// </remarks>
public sealed record SetOrgSettings
{
    /// <summary>
    /// the server's access_token_lifetime_secs field
    /// </summary>
    [JsonPropertyName("access_token_lifetime_secs")]
    public required long AccessTokenLifetimeSecs { get; init; }

    /// <summary>
    /// the server's admin_notifications_enabled field
    /// </summary>
    [JsonPropertyName("admin_notifications_enabled")]
    public required bool AdminNotificationsEnabled { get; init; }

    /// <summary>
    /// the server's default_cert_validity_days field
    /// </summary>
    [JsonPropertyName("default_cert_validity_days")]
    public required int DefaultCertValidityDays { get; init; }

    /// <summary>
    /// the server's deletion_grace_period_days field
    /// </summary>
    [JsonPropertyName("deletion_grace_period_days")]
    public int? DeletionGracePeriodDays { get; init; }

    /// <summary>
    /// the server's email_verification_grace_period_hours field
    /// </summary>
    [JsonPropertyName("email_verification_grace_period_hours")]
    public required int EmailVerificationGracePeriodHours { get; init; }

    /// <summary>
    /// the server's email_verification_required field
    /// </summary>
    [JsonPropertyName("email_verification_required")]
    public required bool EmailVerificationRequired { get; init; }

    /// <summary>
    /// the server's hibp_check_enabled field
    /// </summary>
    [JsonPropertyName("hibp_check_enabled")]
    public required bool HibpCheckEnabled { get; init; }

    /// <summary>
    /// the server's lockout_backoff_multiplier field
    /// </summary>
    [JsonPropertyName("lockout_backoff_multiplier")]
    public required double LockoutBackoffMultiplier { get; init; }

    /// <summary>
    /// the server's lockout_duration_secs field
    /// </summary>
    [JsonPropertyName("lockout_duration_secs")]
    public required long LockoutDurationSecs { get; init; }

    /// <summary>
    /// the server's max_cert_validity_days field
    /// </summary>
    [JsonPropertyName("max_cert_validity_days")]
    public required int MaxCertValidityDays { get; init; }

    /// <summary>
    /// the server's max_failed_login_attempts field
    /// </summary>
    [JsonPropertyName("max_failed_login_attempts")]
    public required int MaxFailedLoginAttempts { get; init; }

    /// <summary>
    /// the server's max_lockout_duration_secs field
    /// </summary>
    [JsonPropertyName("max_lockout_duration_secs")]
    public required long MaxLockoutDurationSecs { get; init; }

    /// <summary>
    /// the server's mfa_challenge_lifetime_secs field
    /// </summary>
    [JsonPropertyName("mfa_challenge_lifetime_secs")]
    public required long MfaChallengeLifetimeSecs { get; init; }

    /// <summary>
    /// the server's mfa_enforced field
    /// </summary>
    [JsonPropertyName("mfa_enforced")]
    public required bool MfaEnforced { get; init; }

    /// <summary>
    /// the server's min_length field
    /// </summary>
    [JsonPropertyName("min_length")]
    public required int MinLength { get; init; }

    /// <summary>
    /// the server's opaque_ksf field
    /// </summary>
    [JsonPropertyName("opaque_ksf")]
    public string? OpaqueKsf { get; init; }

    /// <summary>
    /// the server's opaque_mode field
    /// </summary>
    [JsonPropertyName("opaque_mode")]
    public string? OpaqueMode { get; init; }

    /// <summary>
    /// the server's opaque_suite field
    /// </summary>
    [JsonPropertyName("opaque_suite")]
    public string? OpaqueSuite { get; init; }

    /// <summary>
    /// the server's password_history_count field
    /// </summary>
    [JsonPropertyName("password_history_count")]
    public required int PasswordHistoryCount { get; init; }

    /// <summary>
    /// the server's refresh_token_lifetime_secs field
    /// </summary>
    [JsonPropertyName("refresh_token_lifetime_secs")]
    public required long RefreshTokenLifetimeSecs { get; init; }

    /// <summary>
    /// the server's require_digits field
    /// </summary>
    [JsonPropertyName("require_digits")]
    public required bool RequireDigits { get; init; }

    /// <summary>
    /// the server's require_lowercase field
    /// </summary>
    [JsonPropertyName("require_lowercase")]
    public required bool RequireLowercase { get; init; }

    /// <summary>
    /// the server's require_symbols field
    /// </summary>
    [JsonPropertyName("require_symbols")]
    public required bool RequireSymbols { get; init; }

    /// <summary>
    /// the server's require_uppercase field
    /// </summary>
    [JsonPropertyName("require_uppercase")]
    public required bool RequireUppercase { get; init; }

    /// <summary>
    /// the server's webauthn_user_verification field
    /// </summary>
    [JsonPropertyName("webauthn_user_verification")]
    public string? WebauthnUserVerification { get; init; }
}
