// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// Input for setting organization-level email config.
/// </summary>
/// <remarks>
/// <para>
/// This body REPLACES rather than patches (&#167;27.4 rule 5): what you do not carry over from
/// a prior read is not preserved, it is overwritten. <c>enabled</c>, <c>from_email</c>,
/// <c>from_name</c>, <c>provider</c> are required, so forgetting one is a compile error; an
/// optional property you leave unset is omitted from the wire, and the server then applies its
/// default rather than keeping the stored value, except where the operation documents
/// otherwise. Read first, <c>with</c>-expression the parts you mean to keep, write back.
/// </para>
/// </remarks>
public sealed record SetOrgEmailConfig
{
    /// <summary>
    /// the server's enabled field
    /// </summary>
    [JsonPropertyName("enabled")]
    public required bool Enabled { get; init; }

    /// <summary>
    /// the server's from_email field
    /// </summary>
    [JsonPropertyName("from_email")]
    public required string FromEmail { get; init; }

    /// <summary>
    /// the server's from_name field
    /// </summary>
    [JsonPropertyName("from_name")]
    public required string FromName { get; init; }

    /// <summary>
    /// the server's provider field
    /// </summary>
    [JsonPropertyName("provider")]
    public required ProviderConfig Provider { get; init; }

    /// <summary>
    /// the server's reply_to field
    /// </summary>
    [JsonPropertyName("reply_to")]
    public string? ReplyTo { get; init; }
}
