// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// A signed batch of audit log entries.
/// </summary>
public sealed record SignedAuditBatch
{
    /// <summary>
    /// the server's batch_id field
    /// </summary>
    [JsonPropertyName("batch_id")]
    public required Guid BatchId { get; init; }

    /// <summary>
    /// the server's entry_ids field
    /// </summary>
    [JsonPropertyName("entry_ids")]
    public required IReadOnlyList<Guid> EntryIds { get; init; }

    /// <summary>
    /// ASCII-armored PGP signed message containing the audit batch payload.
    /// </summary>
    [JsonPropertyName("signature_armored")]
    public required string SignatureArmored { get; init; }

    /// <summary>
    /// the server's signed_at field
    /// </summary>
    [JsonPropertyName("signed_at")]
    public required DateTimeOffset SignedAt { get; init; }

    /// <summary>
    /// the server's signing_key_id field
    /// </summary>
    [JsonPropertyName("signing_key_id")]
    public required Guid SigningKeyId { get; init; }

    /// <summary>
    /// the server's tenant_id field
    /// </summary>
    [JsonPropertyName("tenant_id")]
    public required Guid TenantId { get; init; }
}
