// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using Axiam.Sdk.Management;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// The six event types AXIAM transmits (G-5). Stored and sent as their event-type URIs;
/// [<c>Self::ALL</c>] is the canonical order every list AXIAM returns is sorted in.
/// </summary>
/// <remarks>
/// <para>
/// Each member carries the spelling the server uses on the wire via WireName, so the C# name
/// can follow C# conventions without changing what is sent.
/// </para>
/// <para>
/// An <b>open</b> enum. A value this SDK’s copy of the spec does not list decodes to
/// <c>SsfEventType.Unknown</c> rather than failing the response it arrived in (&#167;27.11 rule
/// 1) — a closed enum turns the next value the server adds into a parse error on the whole
/// list, taking down every record on the page over one field of one of them. A <c>switch</c>
/// over these members needs an <c>Unknown</c> arm.
/// </para>
/// </remarks>
[JsonConverter(typeof(WireEnumConverter<SsfEventType>))]
public enum SsfEventType
{
    /// <summary>
    /// The server's <c>https://schemas.openid.net/secevent/caep/event-type/session-revoked</c>
    /// value.
    /// </summary>
    [WireName("https://schemas.openid.net/secevent/caep/event-type/session-revoked")]
    SessionRevoked,

    /// <summary>
    /// The server's
    /// <c>https://schemas.openid.net/secevent/caep/event-type/credential-change</c> value.
    /// </summary>
    [WireName("https://schemas.openid.net/secevent/caep/event-type/credential-change")]
    CredentialChange,

    /// <summary>
    /// The server's
    /// <c>https://schemas.openid.net/secevent/caep/event-type/assurance-level-change</c> value.
    /// </summary>
    [WireName("https://schemas.openid.net/secevent/caep/event-type/assurance-level-change")]
    AssuranceLevelChange,

    /// <summary>
    /// The server's <c>https://schemas.openid.net/secevent/risc/event-type/account-disabled</c>
    /// value.
    /// </summary>
    [WireName("https://schemas.openid.net/secevent/risc/event-type/account-disabled")]
    AccountDisabled,

    /// <summary>
    /// The server's <c>https://schemas.openid.net/secevent/risc/event-type/account-enabled</c>
    /// value.
    /// </summary>
    [WireName("https://schemas.openid.net/secevent/risc/event-type/account-enabled")]
    AccountEnabled,

    /// <summary>
    /// The server's <c>https://schemas.openid.net/secevent/risc/event-type/account-purged</c>
    /// value.
    /// </summary>
    [WireName("https://schemas.openid.net/secevent/risc/event-type/account-purged")]
    AccountPurged,

    /// <summary>
    /// A value this SDK’s copy of the spec does not list.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Its wire spelling is the empty string, which no server value is: carrying an
    /// unrecognised value back into an update is refused by the server rather than silently
    /// written as a spelling it never used. Fifteen of these enums appear in request bodies,
    /// which is what makes that distinction worth having.
    /// </para>
    /// <para>
    /// It is deliberately <b>not</b> the zero member — defaulting to it would make “the server
    /// said nothing” and “the server said something new” the same value.
    /// </para>
    /// </remarks>
    [WireName("")]
    Unknown,
}
