// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// A registered SSF stream, as the management API returns it. **The push <c>Authorization</c>
/// header is never returned**; <c>authorization_header_set</c> says whether one is stored.
/// </summary>
public sealed record SsfStream
{
    /// <summary>
    /// The SET <c>aud</c>. Unique across the deployment.
    /// </summary>
    [JsonPropertyName("audience")]
    public required string Audience { get; init; }

    /// <summary>
    /// Whether a push <c>Authorization</c> header is stored.
    /// </summary>
    [JsonPropertyName("authorization_header_set")]
    public required bool AuthorizationHeaderSet { get; init; }

    /// <summary>
    /// When the stream was registered.
    /// </summary>
    [JsonPropertyName("created_at")]
    public required DateTimeOffset CreatedAt { get; init; }

    /// <summary>
    /// <c>push</c> (RFC 8935) or <c>poll</c> (RFC 8936).
    /// </summary>
    [JsonPropertyName("delivery_method")]
    public required SsfDeliveryMethod DeliveryMethod { get; init; }

    /// <summary>
    /// A description.
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; init; }

    /// <summary>
    /// The push endpoint, or null for a poll stream.
    /// </summary>
    [JsonPropertyName("endpoint_url")]
    public string? EndpointUrl { get; init; }

    /// <summary>
    /// The event types the receiver may have.
    /// </summary>
    [JsonPropertyName("events_allowed")]
    public required IReadOnlyList<SsfEventType> EventsAllowed { get; init; }

    /// <summary>
    /// What the stream carries: the intersection of the two.
    /// </summary>
    [JsonPropertyName("events_delivered")]
    public required IReadOnlyList<SsfEventType> EventsDelivered { get; init; }

    /// <summary>
    /// The event types the receiver asked for (a subset of <c>events_allowed</c>).
    /// </summary>
    [JsonPropertyName("events_requested")]
    public required IReadOnlyList<SsfEventType> EventsRequested { get; init; }

    /// <summary>
    /// The stream id, also the SSF <c>stream_id</c>.
    /// </summary>
    [JsonPropertyName("id")]
    public required Guid Id { get; init; }

    /// <summary>
    /// When the receiver last asked for a verification event, or null.
    /// </summary>
    [JsonPropertyName("last_verification_at")]
    public DateTimeOffset? LastVerificationAt { get; init; }

    /// <summary>
    /// The OAuth2 <c>client_id</c> whose client-credentials token (scope <c>ssf.manage</c>) is
    /// this stream's receiver on the stream management API.
    /// </summary>
    [JsonPropertyName("receiver_client_id")]
    public required string ReceiverClientId { get; init; }

    /// <summary>
    /// <c>enabled</c>, <c>paused</c> or <c>disabled</c>.
    /// </summary>
    [JsonPropertyName("status")]
    public required SsfStreamStatus Status { get; init; }

    /// <summary>
    /// Who set the status: <c>admin</c> or <c>receiver</c>.
    /// </summary>
    [JsonPropertyName("status_actor")]
    public required SsfStatusActor StatusActor { get; init; }

    /// <summary>
    /// Why, if anyone said.
    /// </summary>
    [JsonPropertyName("status_reason")]
    public string? StatusReason { get; init; }

    /// <summary>
    /// <c>iss_sub</c> (default) or <c>email</c>.
    /// </summary>
    [JsonPropertyName("subject_format")]
    public required SsfSubjectFormat SubjectFormat { get; init; }

    /// <summary>
    /// The owning tenant.
    /// </summary>
    [JsonPropertyName("tenant_id")]
    public required Guid TenantId { get; init; }

    /// <summary>
    /// Whether the tenant's transmitter is active: its <c>ssf_enabled</c> is on and the
    /// deployment does not make every tenant share one issuer (D-55). A stream of an inactive
    /// transmitter is kept, and carries nothing.
    /// </summary>
    [JsonPropertyName("transmitter_active")]
    public required bool TransmitterActive { get; init; }

    /// <summary>
    /// Why the transmitter is inactive, when it is.
    /// </summary>
    [JsonPropertyName("transmitter_inactive_reason")]
    public string? TransmitterInactiveReason { get; init; }

    /// <summary>
    /// When it was last written.
    /// </summary>
    [JsonPropertyName("updated_at")]
    public required DateTimeOffset UpdatedAt { get; init; }
}
