// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using Axiam.Sdk.Core;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// <c>create_stream</c> and <c>update_stream</c> (a **replacement**) body.
/// </summary>
/// <remarks>
/// <para>
/// This body REPLACES rather than patches (&#167;27.4 rule 5): what you do not carry over from
/// a prior read is not preserved, it is overwritten. Every property is required, so forgetting
/// one is a compile error rather than a silent null on the wire. Read first,
/// <c>with</c>-expression the parts you mean to keep, write back.
/// </para>
/// </remarks>
public sealed record SsfStreamInput
{
    /// <summary>
    /// 1–512 bytes; unique across the deployment.
    /// </summary>
    [JsonPropertyName("audience")]
    public required string Audience { get; init; }

    /// <summary>
    /// **Write-only.** The <c>Authorization</c> header value AXIAM sends to a push endpoint. On
    /// update, absent keeps the stored one — except that moving the endpoint to another origin
    /// requires it again. -- SECRET: redacted from ToString and from every rendering except the
    /// one request body it is sent in.
    /// </summary>
    [JsonPropertyName("authorization_header")]
    public Sensitive<string>? AuthorizationHeader { get; init; }

    /// <summary>
    /// On update: remove the stored header. Refused together with <c>authorization_header</c>.
    /// </summary>
    [JsonPropertyName("clear_authorization_header")]
    public bool? ClearAuthorizationHeader { get; init; }

    /// <summary>
    /// <c>push</c> or <c>poll</c>.
    /// </summary>
    [JsonPropertyName("delivery_method")]
    public required SsfDeliveryMethod DeliveryMethod { get; init; }

    /// <summary>
    /// At most 256 bytes.
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; init; }

    /// <summary>
    /// Required for <c>push</c> (an <c>https</c> URL under the outbound address policy),
    /// refused for <c>poll</c>.
    /// </summary>
    [JsonPropertyName("endpoint_url")]
    public string? EndpointUrl { get; init; }

    /// <summary>
    /// 1–6 event types.
    /// </summary>
    [JsonPropertyName("events_allowed")]
    public required IReadOnlyList<SsfEventType> EventsAllowed { get; init; }

    /// <summary>
    /// A subset of <c>events_allowed</c>; absent means all of them. The receiver may narrow it
    /// later, never widen it.
    /// </summary>
    [JsonPropertyName("events_requested")]
    public IReadOnlyList<SsfEventType>? EventsRequested { get; init; }

    /// <summary>
    /// An OAuth2 client of the tenant with the <c>client_credentials</c> grant and the
    /// <c>ssf.manage</c> scope.
    /// </summary>
    [JsonPropertyName("receiver_client_id")]
    public required string ReceiverClientId { get; init; }

    /// <summary>
    /// <c>enabled</c> by default.
    /// </summary>
    [JsonPropertyName("status")]
    public SsfStreamStatus? Status { get; init; }

    /// <summary>
    /// At most 256 bytes.
    /// </summary>
    [JsonPropertyName("status_reason")]
    public string? StatusReason { get; init; }

    /// <summary>
    /// <c>iss_sub</c> by default.
    /// </summary>
    [JsonPropertyName("subject_format")]
    public SsfSubjectFormat? SubjectFormat { get; init; }
}
