// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// A tenant is an isolated context within an organization. Each tenant has its own set of
/// users, roles, permissions, resources, certificates, and configuration. Tenants can represent
/// environments (dev/staging/prod) or separate business contexts.
/// </summary>
public sealed record Tenant
{
    /// <summary>
    /// the server's created_at field
    /// </summary>
    [JsonPropertyName("created_at")]
    public required DateTimeOffset CreatedAt { get; init; }

    /// <summary>
    /// the server's id field
    /// </summary>
    [JsonPropertyName("id")]
    public required Guid Id { get; init; }

    /// <summary>
    /// Whether this is an ordinary tenant or the organization's own scope.
    /// <c>#[serde(default)]</c> so every row written before organization scope existed reads
    /// back as [<c>TenantKind::Standard</c>], which is what it is.
    /// </summary>
    [JsonPropertyName("kind")]
    public TenantKind? Kind { get; init; }

    /// <summary>
    /// Arbitrary key-value metadata.
    /// </summary>
    [JsonPropertyName("metadata")]
    public required JsonElement Metadata { get; init; }

    /// <summary>
    /// Human-readable name.
    /// </summary>
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    /// <summary>
    /// The organization this tenant belongs to.
    /// </summary>
    [JsonPropertyName("organization_id")]
    public required Guid OrganizationId { get; init; }

    /// <summary>
    /// URL-safe unique identifier within the organization (e.g., <c>production</c>).
    /// </summary>
    [JsonPropertyName("slug")]
    public required string Slug { get; init; }

    /// <summary>
    /// Lifecycle status. New tenants default to [<c>TenantStatus::Active</c>].
    /// </summary>
    [JsonPropertyName("status")]
    public required TenantStatus Status { get; init; }

    /// <summary>
    /// the server's updated_at field
    /// </summary>
    [JsonPropertyName("updated_at")]
    public required DateTimeOffset UpdatedAt { get; init; }
}
