// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using Axiam.Sdk.Management;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// What a tenant *is*, as distinct from what state it is in. Reserved rather than inferred: an
/// organization has exactly one tenant of kind [<c>Self::Organization</c>], enforced by a
/// unique index rather than by convention. Deriving it from a magic slug or from "the oldest
/// tenant" would make the organization scope something an operator could rename or delete by
/// accident, and it is the scope the super-admin lives in.
/// </summary>
/// <remarks>
/// <para>
/// Each member carries the spelling the server uses on the wire via WireName, so the C# name
/// can follow C# conventions without changing what is sent.
/// </para>
/// <para>
/// An <b>open</b> enum. A value this SDK’s copy of the spec does not list decodes to
/// <c>TenantKind.Unknown</c> rather than failing the response it arrived in (&#167;27.11 rule
/// 1) — a closed enum turns the next value the server adds into a parse error on the whole
/// list, taking down every record on the page over one field of one of them. A <c>switch</c>
/// over these members needs an <c>Unknown</c> arm.
/// </para>
/// </remarks>
[JsonConverter(typeof(WireEnumConverter<TenantKind>))]
public enum TenantKind
{
    /// <summary>The server's <c>standard</c> value.</summary>
    [WireName("standard")]
    Standard,

    /// <summary>The server's <c>organization</c> value.</summary>
    [WireName("organization")]
    Organization,

    /// <summary>
    /// A value this SDK’s copy of the spec does not list.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Its wire spelling is the empty string, which no server value is: carrying an
    /// unrecognised value back into an update is refused by the server rather than silently
    /// written as a spelling it never used. Fifteen of these enums appear in request bodies,
    /// which is what makes that distinction worth having.
    /// </para>
    /// <para>
    /// It is deliberately <b>not</b> the zero member — defaulting to it would make “the server
    /// said nothing” and “the server said something new” the same value.
    /// </para>
    /// </remarks>
    [WireName("")]
    Unknown,
}
