// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// Partial tenant overrides. <c>None</c> = inherit from org baseline.
/// </summary>
/// <remarks>
/// <para>
/// Every property is optional, so this is a SPARSE body: what you leave unset is left
/// unchanged, and is omitted from the wire request entirely rather than sent as null
/// (&#167;27.4 rule 5). Naming the properties you mean to change is the whole API — there is no
/// builder because C# object initializers already are one, and no way to accidentally send a
/// field you did not name.
/// </para>
/// </remarks>
public sealed record TenantSettingsOverride
{
    /// <summary>
    /// the server's access_token_lifetime_secs field
    /// </summary>
    [JsonPropertyName("access_token_lifetime_secs")]
    public long? AccessTokenLifetimeSecs { get; init; }

    /// <summary>
    /// the server's admin_notifications_enabled field
    /// </summary>
    [JsonPropertyName("admin_notifications_enabled")]
    public bool? AdminNotificationsEnabled { get; init; }

    /// <summary>
    /// the server's default_cert_validity_days field
    /// </summary>
    [JsonPropertyName("default_cert_validity_days")]
    public int? DefaultCertValidityDays { get; init; }

    /// <summary>
    /// the server's deletion_grace_period_days field
    /// </summary>
    [JsonPropertyName("deletion_grace_period_days")]
    public int? DeletionGracePeriodDays { get; init; }

    /// <summary>
    /// the server's email_verification_grace_period_hours field
    /// </summary>
    [JsonPropertyName("email_verification_grace_period_hours")]
    public int? EmailVerificationGracePeriodHours { get; init; }

    /// <summary>
    /// the server's email_verification_required field
    /// </summary>
    [JsonPropertyName("email_verification_required")]
    public bool? EmailVerificationRequired { get; init; }

    /// <summary>
    /// the server's hibp_check_enabled field
    /// </summary>
    [JsonPropertyName("hibp_check_enabled")]
    public bool? HibpCheckEnabled { get; init; }

    /// <summary>
    /// the server's lockout_backoff_multiplier field
    /// </summary>
    [JsonPropertyName("lockout_backoff_multiplier")]
    public double? LockoutBackoffMultiplier { get; init; }

    /// <summary>
    /// the server's lockout_duration_secs field
    /// </summary>
    [JsonPropertyName("lockout_duration_secs")]
    public long? LockoutDurationSecs { get; init; }

    /// <summary>
    /// the server's max_cert_validity_days field
    /// </summary>
    [JsonPropertyName("max_cert_validity_days")]
    public int? MaxCertValidityDays { get; init; }

    /// <summary>
    /// the server's max_failed_login_attempts field
    /// </summary>
    [JsonPropertyName("max_failed_login_attempts")]
    public int? MaxFailedLoginAttempts { get; init; }

    /// <summary>
    /// the server's max_lockout_duration_secs field
    /// </summary>
    [JsonPropertyName("max_lockout_duration_secs")]
    public long? MaxLockoutDurationSecs { get; init; }

    /// <summary>
    /// the server's mfa_challenge_lifetime_secs field
    /// </summary>
    [JsonPropertyName("mfa_challenge_lifetime_secs")]
    public long? MfaChallengeLifetimeSecs { get; init; }

    /// <summary>
    /// the server's mfa_enforced field
    /// </summary>
    [JsonPropertyName("mfa_enforced")]
    public bool? MfaEnforced { get; init; }

    /// <summary>
    /// the server's min_length field
    /// </summary>
    [JsonPropertyName("min_length")]
    public int? MinLength { get; init; }

    /// <summary>
    /// the server's opaque_ksf field
    /// </summary>
    [JsonPropertyName("opaque_ksf")]
    public string? OpaqueKsf { get; init; }

    /// <summary>
    /// the server's opaque_mode field
    /// </summary>
    [JsonPropertyName("opaque_mode")]
    public string? OpaqueMode { get; init; }

    /// <summary>
    /// the server's opaque_suite field
    /// </summary>
    [JsonPropertyName("opaque_suite")]
    public string? OpaqueSuite { get; init; }

    /// <summary>
    /// the server's password_history_count field
    /// </summary>
    [JsonPropertyName("password_history_count")]
    public int? PasswordHistoryCount { get; init; }

    /// <summary>
    /// the server's refresh_token_lifetime_secs field
    /// </summary>
    [JsonPropertyName("refresh_token_lifetime_secs")]
    public long? RefreshTokenLifetimeSecs { get; init; }

    /// <summary>
    /// the server's require_digits field
    /// </summary>
    [JsonPropertyName("require_digits")]
    public bool? RequireDigits { get; init; }

    /// <summary>
    /// the server's require_lowercase field
    /// </summary>
    [JsonPropertyName("require_lowercase")]
    public bool? RequireLowercase { get; init; }

    /// <summary>
    /// the server's require_symbols field
    /// </summary>
    [JsonPropertyName("require_symbols")]
    public bool? RequireSymbols { get; init; }

    /// <summary>
    /// the server's require_uppercase field
    /// </summary>
    [JsonPropertyName("require_uppercase")]
    public bool? RequireUppercase { get; init; }
}
