// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// The UpdateOAuth2ClientRequest schema from the server's OpenAPI document.
/// </summary>
/// <remarks>
/// <para>
/// Every property is optional, so this is a SPARSE body: what you leave unset is left
/// unchanged, and is omitted from the wire request entirely rather than sent as null
/// (&#167;27.4 rule 5). Naming the properties you mean to change is the whole API — there is no
/// builder because C# object initializers already are one, and no way to accidentally send a
/// field you did not name.
/// </para>
/// </remarks>
public sealed record UpdateOAuth2ClientRequest
{
    /// <summary>
    /// Pass an empty string to clear a previously registered URI — the one edit an operator
    /// makes when an RP is decommissioned.
    /// </summary>
    [JsonPropertyName("backchannel_logout_uri")]
    public string? BackchannelLogoutUri { get; init; }

    /// <summary>
    /// the server's dpop_bound_access_tokens field
    /// </summary>
    [JsonPropertyName("dpop_bound_access_tokens")]
    public bool? DpopBoundAccessTokens { get; init; }

    /// <summary>
    /// the server's dpop_require_nonce field
    /// </summary>
    [JsonPropertyName("dpop_require_nonce")]
    public bool? DpopRequireNonce { get; init; }

    /// <summary>
    /// the server's grant_types field
    /// </summary>
    [JsonPropertyName("grant_types")]
    public IReadOnlyList<string>? GrantTypes { get; init; }

    /// <summary>
    /// X5.1 — see the create DTO. <c>Some("")</c> clears, so a client can be migrated from an
    /// inline key set to a published one.
    /// </summary>
    [JsonPropertyName("jwks")]
    public string? Jwks { get; init; }

    /// <summary>
    /// X5.1 — see the create DTO. <c>Some("")</c> clears.
    /// </summary>
    [JsonPropertyName("jwks_uri")]
    public string? JwksUri { get; init; }

    /// <summary>
    /// the server's name field
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; init; }

    /// <summary>
    /// the server's post_logout_redirect_uris field
    /// </summary>
    [JsonPropertyName("post_logout_redirect_uris")]
    public IReadOnlyList<string>? PostLogoutRedirectUris { get; init; }

    /// <summary>
    /// the server's profile field
    /// </summary>
    [JsonPropertyName("profile")]
    public ClientProfile? Profile { get; init; }

    /// <summary>
    /// the server's redirect_uris field
    /// </summary>
    [JsonPropertyName("redirect_uris")]
    public IReadOnlyList<string>? RedirectUris { get; init; }

    /// <summary>
    /// the server's require_par field
    /// </summary>
    [JsonPropertyName("require_par")]
    public bool? RequirePar { get; init; }

    /// <summary>
    /// the server's scopes field
    /// </summary>
    [JsonPropertyName("scopes")]
    public IReadOnlyList<string>? Scopes { get; init; }

    /// <summary>
    /// the server's self_signed_tls_client_auth_thumbprints field
    /// </summary>
    [JsonPropertyName("self_signed_tls_client_auth_thumbprints")]
    public IReadOnlyList<string>? SelfSignedTlsClientAuthThumbprints { get; init; }

    /// <summary>
    /// the server's tls_client_auth_san_dns field
    /// </summary>
    [JsonPropertyName("tls_client_auth_san_dns")]
    public string? TlsClientAuthSanDns { get; init; }

    /// <summary>
    /// the server's tls_client_auth_san_uri field
    /// </summary>
    [JsonPropertyName("tls_client_auth_san_uri")]
    public string? TlsClientAuthSanUri { get; init; }

    /// <summary>
    /// Pass an empty string to clear, as with <c>backchannel_logout_uri</c>.
    /// </summary>
    [JsonPropertyName("tls_client_auth_subject_dn")]
    public string? TlsClientAuthSubjectDn { get; init; }

    /// <summary>
    /// the server's tls_client_certificate_bound_access_tokens field
    /// </summary>
    [JsonPropertyName("tls_client_certificate_bound_access_tokens")]
    public bool? TlsClientCertificateBoundAccessTokens { get; init; }

    /// <summary>
    /// the server's token_endpoint_auth_method field
    /// </summary>
    [JsonPropertyName("token_endpoint_auth_method")]
    public ClientAuthMethod? TokenEndpointAuthMethod { get; init; }
}
