// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using Axiam.Sdk.Core;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// <c>PATCH /api/v1/tenants/{tenant_id}/directory</c> — a **sparse** update. Every member
/// optional: absent leaves the stored value, and for the two nullable members an explicit
/// <c>null</c> clears it.
/// </summary>
/// <remarks>
/// <para>
/// Every property is optional, so this is a SPARSE body: what you leave unset is left
/// unchanged, and is omitted from the wire request entirely rather than sent as null
/// (&#167;27.4 rule 5). Naming the properties you mean to change is the whole API — there is no
/// builder because C# object initializers already are one, and no way to accidentally send a
/// field you did not name.
/// </para>
/// </remarks>
public sealed record UpdateDirectoryConfig
{
    /// <summary>
    /// See [<c>SetDirectoryConfig::base_dn</c>].
    /// </summary>
    [JsonPropertyName("base_dn")]
    public string? BaseDn { get; init; }

    /// <summary>
    /// See [<c>SetDirectoryConfig::bind_dn</c>].
    /// </summary>
    [JsonPropertyName("bind_dn")]
    public string? BindDn { get; init; }

    /// <summary>
    /// See [<c>SetDirectoryConfig::bind_secret</c>]; absent keeps the stored secret, subject to
    /// the same P23W2-01 rule. -- SECRET: redacted from ToString and from every rendering
    /// except the one request body it is sent in.
    /// </summary>
    [JsonPropertyName("bind_secret")]
    public Sensitive<string>? BindSecret { get; init; }

    /// <summary>
    /// See [<c>SetDirectoryConfig::enabled</c>].
    /// </summary>
    [JsonPropertyName("enabled")]
    public bool? Enabled { get; init; }

    /// <summary>
    /// Explicit <c>null</c> clears it.
    /// </summary>
    [JsonPropertyName("group_base_dn")]
    public string? GroupBaseDn { get; init; }

    /// <summary>
    /// Explicit <c>null</c> clears it.
    /// </summary>
    [JsonPropertyName("group_filter")]
    public string? GroupFilter { get; init; }

    /// <summary>
    /// Replaces the whole table when present.
    /// </summary>
    [JsonPropertyName("group_mappings")]
    public IReadOnlyList<GroupMapping>? GroupMappings { get; init; }

    /// <summary>
    /// See [<c>SetDirectoryConfig::group_member_attribute</c>].
    /// </summary>
    [JsonPropertyName("group_member_attribute")]
    public string? GroupMemberAttribute { get; init; }

    /// <summary>
    /// See [<c>SetDirectoryConfig::group_nesting_depth</c>].
    /// </summary>
    [JsonPropertyName("group_nesting_depth")]
    public int? GroupNestingDepth { get; init; }

    /// <summary>
    /// See [<c>SetDirectoryConfig::jit_provisioning</c>].
    /// </summary>
    [JsonPropertyName("jit_provisioning")]
    public bool? JitProvisioning { get; init; }

    /// <summary>
    /// the server's kind field
    /// </summary>
    [JsonPropertyName("kind")]
    public DirectoryKind? Kind { get; init; }

    /// <summary>
    /// See [<c>SetDirectoryConfig::start_tls</c>].
    /// </summary>
    [JsonPropertyName("start_tls")]
    public bool? StartTls { get; init; }

    /// <summary>
    /// See [<c>SetDirectoryConfig::sync_interval_secs</c>].
    /// </summary>
    [JsonPropertyName("sync_interval_secs")]
    public long? SyncIntervalSecs { get; init; }

    /// <summary>
    /// Replaces the whole list when present.
    /// </summary>
    [JsonPropertyName("trust_anchors_pem")]
    public IReadOnlyList<string>? TrustAnchorsPem { get; init; }

    /// <summary>
    /// See [<c>SetDirectoryConfig::url</c>].
    /// </summary>
    [JsonPropertyName("url")]
    public string? Url { get; init; }

    /// <summary>
    /// the server's user_attribute_map field
    /// </summary>
    [JsonPropertyName("user_attribute_map")]
    public UserAttributeMap? UserAttributeMap { get; init; }

    /// <summary>
    /// See [<c>SetDirectoryConfig::user_filter</c>].
    /// </summary>
    [JsonPropertyName("user_filter")]
    public string? UserFilter { get; init; }
}
