// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using Axiam.Sdk.Core;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// The UpdateWebhookRequest schema from the server's OpenAPI document.
/// </summary>
/// <remarks>
/// <para>
/// Every property is optional, so this is a SPARSE body: what you leave unset is left
/// unchanged, and is omitted from the wire request entirely rather than sent as null
/// (&#167;27.4 rule 5). Naming the properties you mean to change is the whole API — there is no
/// builder because C# object initializers already are one, and no way to accidentally send a
/// field you did not name.
/// </para>
/// </remarks>
public sealed record UpdateWebhookRequest
{
    /// <summary>
    /// the server's enabled field
    /// </summary>
    [JsonPropertyName("enabled")]
    public bool? Enabled { get; init; }

    /// <summary>
    /// the server's events field
    /// </summary>
    [JsonPropertyName("events")]
    public IReadOnlyList<string>? Events { get; init; }

    /// <summary>
    /// the server's retry_policy field
    /// </summary>
    [JsonPropertyName("retry_policy")]
    public RetryPolicy? RetryPolicy { get; init; }

    /// <summary>
    /// New HMAC-SHA256 shared secret (D-02 secret rotation). Encrypted server-side with
    /// AES-256-GCM before storage; omit to leave the existing secret untouched. -- SECRET:
    /// redacted from ToString and from every rendering except the one request body it is sent
    /// in.
    /// </summary>
    [JsonPropertyName("secret")]
    public Sensitive<string>? Secret { get; init; }

    /// <summary>
    /// the server's url field
    /// </summary>
    [JsonPropertyName("url")]
    public string? Url { get; init; }
}
