// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using Axiam.Sdk.Core;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// The UpdateFederationConfigRequest schema from the server's OpenAPI document.
/// </summary>
/// <remarks>
/// <para>
/// Every property is optional, so this is a SPARSE body: what you leave unset is left
/// unchanged, and is omitted from the wire request entirely rather than sent as null
/// (&#167;27.4 rule 5). Naming the properties you mean to change is the whole API — there is no
/// builder because C# object initializers already are one, and no way to accidentally send a
/// field you did not name.
/// </para>
/// </remarks>
public sealed record UpdateFederationConfigRequest
{
    /// <summary>
    /// Whether tenants may inherit this organization-level provider.
    /// </summary>
    [JsonPropertyName("allow_tenant_inheritance")]
    public bool? AllowTenantInheritance { get; init; }

    /// <summary>
    /// Accepted signature algorithms (CQ-B40/REQ-14 AC-5).
    /// </summary>
    [JsonPropertyName("allowed_algorithms")]
    public IReadOnlyList<string>? AllowedAlgorithms { get; init; }

    /// <summary>
    /// Accepted external IdP tenants for a templated issuer. Replaced wholesale.
    /// </summary>
    [JsonPropertyName("allowed_issuer_tenants")]
    public IReadOnlyList<string>? AllowedIssuerTenants { get; init; }

    /// <summary>
    /// Apple Key ID. <c>Some(None)</c> clears it.
    /// </summary>
    [JsonPropertyName("apple_key_id")]
    public string? AppleKeyId { get; init; }

    /// <summary>
    /// Apple Team ID. <c>Some(None)</c> clears it.
    /// </summary>
    [JsonPropertyName("apple_team_id")]
    public string? AppleTeamId { get; init; }

    /// <summary>
    /// the server's attribute_map field
    /// </summary>
    [JsonPropertyName("attribute_map")]
    public JsonElement? AttributeMap { get; init; }

    /// <summary>
    /// OAuth2-variant authorization endpoint. <c>Some(None)</c> clears it.
    /// </summary>
    [JsonPropertyName("authorization_endpoint")]
    public string? AuthorizationEndpoint { get; init; }

    /// <summary>
    /// Sign-in-button icon for a generic provider. <c>Some(None)</c> clears it.
    /// </summary>
    [JsonPropertyName("button_icon")]
    public string? ButtonIcon { get; init; }

    /// <summary>
    /// the server's client_id field
    /// </summary>
    [JsonPropertyName("client_id")]
    public string? ClientId { get; init; }

    /// <summary>
    /// the server's client_secret field -- SECRET: redacted from ToString and from every
    /// rendering except the one request body it is sent in.
    /// </summary>
    [JsonPropertyName("client_secret")]
    public Sensitive<string>? ClientSecret { get; init; }

    /// <summary>
    /// the server's enabled field
    /// </summary>
    [JsonPropertyName("enabled")]
    public bool? Enabled { get; init; }

    /// <summary>
    /// PEM-encoded X.509 certificate for verifying SAML assertions (CQ-B40/REQ-14 AC-5).
    /// <c>Some(None)</c> clears the stored cert.
    /// </summary>
    [JsonPropertyName("idp_signing_cert_pem")]
    public string? IdpSigningCertPem { get; init; }

    /// <summary>
    /// the server's metadata_url field
    /// </summary>
    [JsonPropertyName("metadata_url")]
    public string? MetadataUrl { get; init; }

    /// <summary>
    /// the server's provider field
    /// </summary>
    [JsonPropertyName("provider")]
    public string? Provider { get; init; }

    /// <summary>
    /// Operator-chosen identifier for a <c>generic_*</c> kind. <c>Some(None)</c> clears it.
    /// </summary>
    [JsonPropertyName("provider_slug")]
    public string? ProviderSlug { get; init; }

    /// <summary>
    /// Send PKCE on the authorization request.
    /// </summary>
    [JsonPropertyName("require_pkce")]
    public bool? RequirePkce { get; init; }

    /// <summary>
    /// Scopes to request. Replaced wholesale; empty restores the per-kind default.
    /// </summary>
    [JsonPropertyName("scopes")]
    public IReadOnlyList<string>? Scopes { get; init; }

    /// <summary>
    /// OAuth2-variant token endpoint. <c>Some(None)</c> clears it.
    /// </summary>
    [JsonPropertyName("token_endpoint")]
    public string? TokenEndpoint { get; init; }

    /// <summary>
    /// the server's token_exchange field
    /// </summary>
    [JsonPropertyName("token_exchange")]
    public TokenExchangeTrustRequest? TokenExchange { get; init; }

    /// <summary>
    /// OAuth2-variant userinfo endpoint. <c>Some(None)</c> clears it.
    /// </summary>
    [JsonPropertyName("userinfo_endpoint")]
    public string? UserinfoEndpoint { get; init; }
}
