// <auto-generated>
// Generated by scripts/gen_management.py from management-registry.json and openapi.json.
// DO NOT EDIT -- your changes will be overwritten. Regenerate with
// `python3 scripts/gen_management.py`; CI verifies the committed output is current.
// </auto-generated>

#nullable enable

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Axiam.Sdk.Management.Models;

/// <summary>
/// Which directory attribute feeds each AXIAM user field.
/// </summary>
public sealed record UserAttributeMap
{
    /// <summary>
    /// The attribute holding the human-readable name.
    /// </summary>
    [JsonPropertyName("display_name")]
    public required string DisplayName { get; init; }

    /// <summary>
    /// The attribute holding the e-mail address.
    /// </summary>
    [JsonPropertyName("email")]
    public required string Email { get; init; }

    /// <summary>
    /// The attribute holding the immutable entry identifier (<c>entryUUID</c>,
    /// <c>objectGUID</c>).
    /// </summary>
    [JsonPropertyName("external_id")]
    public required string ExternalId { get; init; }

    /// <summary>
    /// The attribute holding the login name (<c>uid</c>, <c>sAMAccountName</c>).
    /// </summary>
    [JsonPropertyName("username")]
    public required string Username { get; init; }
}
